### ISSUE TITLE
Provide priority settings to prioritize prefixes/suffixes in certain groups

### ISSUE THREAD

**Issue by me4502** [PEXPlugins/PermissionsEx#1577]
Hi,

Basically I'm needing a way to make certain groups be prioritized with suffixes. I have a group for guards, and one for donors. If someone is a member of both, the last group they were added to is the suffix they have. Alongside this, it would be nice that if the priority is less than 0, it overwrites the prefixes and suffixes set in the user specific settings.

I was going to submit a PR for this, just looking for feedback on the idea first.

**Comment by macdja38** [comment]
I love this idea. it would be very useful to me.

**Comment by ryantheleach** [comment]
+1, if permissions have weights options should have weights.

Your original idea about giving groups weights in general though seems flawed, it creates yet another level of weight calculation that the user needs to be aware of, would it be more subtle then permission weights? it would clearly need to be more powerful then the implicit weighting of ordering.

https://forums.spongepowered.org/t/permissionsex-v2-0-api-5/6198/1205

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
