### ISSUE TITLE
NullPointerException on checking user's group

### ISSUE THREAD

**Issue by rocky143** [PEXPlugins/PermissionsEx#1805]
I am using latest spigot build along with latest pex that I last downloaded from pex jenkins about 15 days ago, version 1.23. Here is the error I am getting: http://pastebin.com/kcRinAeu
This does not happen all the time, only once the server has restated and has been running for a few hours. 

Edit: This usually happens when I am checking user's group, adding/setting them to a group, etc. Also, I can confirm that this issue only happens when I am checking an offline player. I checked myself and several other online players, they seem to work fine.

Additional information. Since this issue is related to offline players so I though I would point this out. I am using BungeeCord and I have every setting required for pex to run correctly. I have other servers on the network that are not having this issue.

**Comment by zml2008** [comment]
Your error report is a bit useless due to not containing the actual location of the error. I've fixed the commands manager error logging code to work properly.

Please download the fixed version from http://get.your.minions.at.aoeu.xyz/PermissionsEx-1.23.1-SNAPSHOT.jar and post further errors you get from PEX.

**Comment by zml2008** [comment]
No response in over a month, closing
