### ISSUE TITLE
Extend Timed group/permissions.

### ISSUE THREAD

**Issue by Sinestessia** [PEXPlugins/PermissionsEx#1985]
I cant find a way to extend ( add time ) to a given timed perimssion or group.
Like in a given VIP rank of ex 30 days, being abble to add 3 days for winning prizes or joining events etc to the player.

**Comment by zml2008** [comment]
I'll look at implementing this once I reimplement timed permissions on Sponge.

**Comment by Stormbow** [comment]
I think this is a really good idea.  (And I don't even use timed anything on my server.)

**Comment by zml2008** [comment]
yeah, it makes sense to have, but also a new feature (and PEX 1.x is in feature freeze indefinitely)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
