### ISSUE TITLE
Default group being reset

### ISSUE THREAD

**Issue by HeroCC** [PEXPlugins/PermissionsEx#2003]
Randomly, without any console output, my default group resets. I use SQL, NetEvents, and Java 8 with BungeeCord. I can provide logs, but I found nothing useful in them. Thanks for the help!

PEX: 1.23.2
Netevents: 1.0
Java: 8
Spigot: git-Spigot-870264a-0a645a2

**Comment by HeroCC** [comment]
Heh, I just googled this problem, still having it BTW and found my old ticket. Anybody know what could be going wrong?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
