### ISSUE TITLE
SQL error on startup

### ISSUE THREAD

**Issue by Vengea** [PEXPlugins/PermissionsEx#2012]
### Description

Our server has upgraded to Bungee and Im trying to get PEX work with multiple servers, but this error comes up and I dont know why. I thing it has something to do with prefix, so I have screenshoted all the prefixes in the database: 
http://gyazo.com/cd24c13d3dcaa1da727eade0e8e063c8
### Detailed Information

[Is available here](https://gist.github.com/2f6a92ecfaf5116dc37e)

**Comment by jiongjionger** [comment]
I have same issue. When i set a permissions with player, sometimes it cannot sync to the other sever(with PEX and MYSQL)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
