### ISSUE TITLE
Rank order

### ISSUE THREAD

**Issue by SecretlyJealous** [PEXPlugins/PermissionsEx#2047]
I think it would be very convenient if members of a default group were all listed together on the permissions.yml, this would make it easier to clean out the default users. At the moment having too much users in the permissions.yml seems to be causing a huge amount of lag and the cleanup command requires you to enable logging which also creates lag that can be seen on timings. I think this neat addition will solve this issue for most users.

**Comment by zml2008** [comment]
The current arrangement is done for performance reasons: When you have a user id, it's faster + simpler to get the user's parents from the user's sections, rather than having to check every group to see if the group contains the player.

Make sure your create-user-records setting is set to false, and that should prevent users from being added to your permissions file unnecessarily.

Unfortunately the performance issues you are experiencing are due to PEX 1.x's architecture and cannot be fixed without a mostly complete rewrite. This is what I have done with PEX 2 for Sponge though.

**Comment by SecretlyJealous** [comment]
I've got create-user-records set to false to prevent players from being added to the file unnecessarily however I give my players limited worldedit permissions for 24 hours upon voting, after the time is up the permission is revoked but the user is still in the file. I don't plan on moving from spigot to sponge anytime soon, is there any other alternative method you could recommend me?
