### ISSUE TITLE
Cauldron 1.7.10 | Crash

### ISSUE THREAD

**Issue by Pr0totype2** [PEXPlugins/PermissionsEx#2056]
Well ehm, I'm using Cauldron 1.7.10, but I get this error:

http://hastebin.com/qugihuqome.dos

Using PermissionsEx 1.7.10:
http://dl2.azminecraft.info/index.php?act=download&id=1420350195&hash=2147483647

**Comment by zml2008** [comment]
This seems like an issue that's cauldron specific. Since I am not particularly familiar with cauldron and cauldron is no longer maintained, I can't give you too much help. The things that might work are 1) Make sure you don't have multiple PEX jars (especially not like a PEX for forge jar) and 2) remove all your mods and plugins and add them back to see which one causes the error (start with coremods -- those can cause weird issues sometimes :/)
