### ISSUE TITLE
How do you bypass OP permissions?

### ISSUE THREAD

**Issue by MrEminent42** [PEXPlugins/PermissionsEx#2076]
This isn't really a bug, more of a question on how you did something.

With PermissionsEX, you can set a Config option to allow-ops or not. If you set it to false, it will only let ops run the command if they have the actual permission registered under their name. Would you mind sharing how you do this with me?

Thanks,
Mr. Eminent

**Comment by Stormbow** [comment]
OP is a [Vanilla Permission](http://wiki.bukkit.org/Vanilla_permissions), and for some reason, we're not-always able to allow or disallow those.  You'd negate those as you would negate any other permission, IF you gave them to a group through a wildcard of some sort.  If you have not given them the permission node, they should not have access to it (but I'm betting they do, since it's been bugged for many months and I haven't been able to figure out how to handle those myself either).

**Comment by MrEminent42** [comment]
No that's not what I mean xD. I meant how did zml bypass OP's permissions? Like you can disallow ops to use the PEX commands?

**Comment by zml2008** [comment]
PEX checks permissions for its commands directly through the permissions database -- it doesn't go through Bukkit. If you want to do this in your own plugin, you'll want to register the permission you're checking as PermissionDefault.FALSE, which will not automatically give the permission to ops.
