### ISSUE TITLE
SQL with only groups

### ISSUE THREAD

**Issue by XLPmc** [PEXPlugins/PermissionsEx#2077]
Hi there,
I want to connect my groups on my bungeecord is there a possebillity to use filebackend with only groups?

**Comment by zml2008** [comment]
There's a MultiBackend that exists for this. However, it's currently experimental and in the process of being rewritten for the new version of  PEX, so I have been holding off on writing documentation for it. Feel free to take a look at [the code](https://github.com/PEXPlugins/PermissionsEx/blob/1.23.x/src/main/java/ru/tehkode/permissions/backends/MultiBackend.java#L35), but you'll be on your own with regards to support since there are some issues that mean I'm not comfortable releasing this for general use.
