### ISSUE TITLE
Bungee-side permissionsEX

### ISSUE THREAD

**Issue by Slaand** [PEXPlugins/PermissionsEx#2092]
Hello, please? :D It's would be nice

**Comment by xaoseric** [comment]
You mean something like this? https://github.com/weaondara/BungeePerms 
If that is what your talking about, i can look into implementing the bungee side permissionsEX

**Comment by Slaand** [comment]
Yes yes! And I think mysql support is needed, then all perms will work from bungee and spigot :3
P.S. Sorry im bad at english :+1:

**Comment by zml2008** [comment]
PEX2.0 is implementation-abstract -- there are currently spigot and sponge versions. a bungee version could be added by anybody interested.

**Comment by xaoseric** [comment]
@zml2008 I'll send a push once i get some of the bungee side working :)

**Comment by zml2008** [comment]
Awesome! Would be a useful addition to have.

I'll also need to rethink how cache invalidations will be synced across active instances in 2.0. Currently I'm thinking about replacing the current NetEvents-based system with one that is backend-specific -- meaning each backend handles its own update notifications -- so file will monitor the permissions file for modifications, sql will be notified about changes to the database (hopefully, I'm not sure about the best way to do this with the database)

**Comment by xaoseric** [comment]
@zml2008 the only plugin that comes close to matching pex with bungee support is BungeePerms (https://github.com/weaondara/BungeePerms), but the owner of that project seems to be inactive. Spigot has a few wiki articles on bungeecord development (https://www.spigotmc.org/wiki/bungeecord/) if you want to look through them.

On the Bukkit side of things, we will probably need to add a config option that enables bungee support. Sense bungeecord has a plugin channel option, for communicating between servers, all we would need to do is use that ideally. If you have skype, feel free to pm me, and i'll message you my skype, because that would be easier for communication.

**Comment by zml2008** [comment]
I don't use skype -- but PEX is on IRC, #permissionsex on irc.esper.net, and I hang around there, so poke me there to talk.
