### ISSUE TITLE
Dropper bug of Modifyworld can let player have restricted items

### ISSUE THREAD

**Issue by CatMe0w** [PEXPlugins/PermissionsEx#2132]
Modifyworld rule: When players craft a restricted item, this item will drop out the inventory.
So a griefer placed a dropper under his feet, then he crafted a restricted item, the item dropped out and into the dropper.
Next, he can TAKE OUT this item without the restrict of Modifyworld! 
And he can to hold this item to interact any blocks at one time.

This bug is dangerous for many cauldron servers, I hope you can fix it in time.

**Comment by Stormbow** [comment]
Have you used the PEX debug mode to ensure all of the related permissions are correctly negated?

**Comment by Snipershotmaster** [comment]
I prefer to use essentials and worldguard for protection, but Stormbow might be right.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
