### ISSUE TITLE
Default rank deploy in MySQL after restart.

### ISSUE THREAD

**Issue by paperrain** [PEXPlugins/PermissionsEx#2151]
Each time a server is restarted, the plugin PEX reinserted the default rank in the database.

Spigot: 1.8.7
PEX: Latest in Bukkit.

**Comment by zml2008** [comment]
this issue was fixed a long time ago. What is your actual PEX version?

**Comment by paperrain** [comment]
PermissionsEx v1.23.3
http://i.imgur.com/9f6RTva.png

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
