### ISSUE TITLE
Clarification: Is ModifyWorld part of PEX?

### ISSUE THREAD

**Issue by FrozenBeard** [PEXPlugins/PermissionsEx#2173]
This is really confusing me, a lot of the docs show modifyworld permissions, but that plugin seems seperate, Are they cobined in later versions of Pex? I have not added the ModifyWorld plugin, as the only option I need to toggle is building.
Im trying to figure out how to only allow building on 1 rank, at present my default rank has
 - modifyworld.*, which is very confusing as I don't have this plugin installed.

**Comment by zml2008** [comment]
No, it's a separate plugin. It used to be included in PEX, which is why some of its permissions are used as defaults.

If you don't have modifyworld installed, those permissions will have no effect. To toggle building you'll have to find a plugin that can restrict building and look at its documentation.

**Comment by FrozenBeard** [comment]
Fantastic, thank you for the clarification. Its confusing as the documentation lists it many times as examples. I think essentials comes with a build permission for me to use.
