### ISSUE TITLE
PEX long Startup

### ISSUE THREAD

**Issue by logtainment** [PEXPlugins/PermissionsEx#2174]
Hi,
after this message:

[05:54:42 INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.3
[05:54:42 INFO]: [PermissionsEx] Initializing sql backend
[05:54:42 INFO]: [PermissionsEx] Successfully connected to SQL database

PermissionsEx need 2 Minutes to startup. What is this? When i reload the Server crash at this position!

**Comment by CzEMC** [comment]
PemissionsEx takes a long time to download all the permission nodes from the SQL database. Possible bottlenecks could be: SQL Processing time, Latency, or your hosts internet connection/CPU Speed.

When you /reload, (which is highly not recommended) pex will basically do this process again, and your servers watchdog will think your server has crashed because pex is taking its time getting permissions from the SQL database. The watchdog is terminating your server.

**Comment by Stormbow** [comment]
It should be noted that the /reload command is not PEX related and has crashed servers for more than 7 years.
