### ISSUE TITLE
MySQL Database will be resetted

### ISSUE THREAD

**Issue by essemX** [PEXPlugins/PermissionsEx#2181]
hey,
every time i add a new server/restart one on my network with permissionsex (v 1.23.3) and the same database informations it resetts the whole database 

if you need more information or its not a bug, let me know

**Comment by CzEMC** [comment]
We will need some debug information.

So your saying you have a existing database that has some servers already connected to it and when you add another brand-new server it resets the entire database? (Thus the already connected servers don't have their permissions anymore)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
