### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by tteeee** [PEXPlugins/PermissionsEx#2185]
### Description

[Insert description of issue here]
### Detailed Information

[Is available here](https://gist.github.com/157335a1f5e3cbc27b1f)

**Comment by CzEMC** [comment]
Similar to #2193

Follow my instructions that I've posted on #2193 and reply here on your results.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
