### ISSUE TITLE
PEX 2.0 Enhancement request: Automatic rank promotions

### ISSUE THREAD

**Issue by Nutmegan** [PEXPlugins/PermissionsEx#2233]
It looks like something to allow for lifetime durations was in the works at some point in the past, but I don't see anything that would allow for groups to have a lifetime value before promoting a user up to the next rank on the ladder automatically. When/if you ever decide to get back to that, I think this type of feature would be very handy.

**Comment by Stormbow** [comment]
Lifetimes are for users to have permissions or groups for a specific amount of time, and when the lifetime expires, the permissions/groups are removed.

**Comment by Stormbow** [comment]
There are plugins that monitor user play time and then allow promotions, [AutoRank](http://dev.bukkit.org/bukkit-plugins/autorank/) for example.

**Comment by Nutmegan** [comment]
I get it. Most likely one of our server devs will implement something like this on top of our PEX implementation. I just thought I would ask here first as it seemed very tightly related to the idea of ranks and ladders and it was possible something may already be planned. Thanks for the input.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
