### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by captincreeper1** [PEXPlugins/PermissionsEx#2253]
I am working on installing this for my spongeforge server and cannot seem to get this working please help me :)

**Comment by Stormbow** [comment]
Google and YouTube are your friends.  :)  Watch [this](https://www.youtube.com/watch?v=hxVqlXK7bg0).

**Comment by zml2008** [comment]
That tutorial is for 1.8.8, which Sponge doesn't support yet.

Because Sponge is still in very active development, there aren't a ton of tutorials around yet. The general setup is like a forge 1.8 server, where you install [Sponge](https://files.minecraftforge.net/spongeforge) and [PEX](https://ci.yawk.at/view/PermissionsEx/job/PermissionsEx/lastSuccessfulBuild/artifact/PermissionsEx-Sponge.jar) as mods. Also make sure to create `config/permisisonsex/permissions{.json,ex.conf}` (shell glob) before starting the server -- there's currently a little bug with how files are created.

**Comment by captincreeper1** [comment]
O)k i tried that but it still did not work?

**Comment by captincreeper1** [comment]
None of the commands are rendering? does it need any sort of support plugin?

**Comment by captincreeper1** [comment]
wait you do not want to put the config file inside of the config folder?
