### ISSUE TITLE
PEX sponge doesn't work

### ISSUE THREAD

**Issue by Likton** [PEXPlugins/PermissionsEx#2254]
Hi!

I'm trying to run a sponge server with your plugin for permissions. But, I'm in trouble. Indeed, when I push the command I can see that the plugin (PermissionsEx) is loaded (green lightened), but the "/pex" command is unknown.
Report to this pic :
http://puu.sh/lRL5Q/e88b6aac79.png

I'm running the PermissionsEX-Sponge.jar (the lastet I can download on Jenkins).

Thanks for any help you could bring me to fix this issue. :)

**Comment by zml2008** [comment]
In Sponge there is no distinction between enabled and disabled plugins -- so everything is green even if an error occurs while loading (this is a FML limitation).

Make sure you create the necessary files in config/permissionsex -> `permissionsex.conf` and `permissions.json` -- those aren't currently automatically created due to a bug.

**Comment by Likton** [comment]
Ho! Okay! thanks :)

But the cmd which doesn't work IG, is an issue due to this missing configuration(s) ?
