### ISSUE TITLE
Possible Enhancement to the /pex info command for default group identification

### ISSUE THREAD

**Issue by sibomots** [PEXPlugins/PermissionsEx#2261]
As discussed on IRC, this issue is a placeholder for a proposed addition/feature to display the membership to a group deemed default.

Repro case:
Setup non-trivial permission file with Foo being a default group.
new player joins server
new player chats and the plugin correctly routes handlers for chat prefix to that group
invoking /pex user Joe info does not show membership to the default group.

If it's worthwhile to add/change the behavior of the info query, please consider it.

Thank you.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
