### ISSUE TITLE
Support for 1.7? [Bug?]

### ISSUE THREAD

**Issue by CzEMC** [PEXPlugins/PermissionsEx#2270]
Can the 1.8 version for pex become backwards compatible for 1.7? Since I have a 1.7 only network that uses MySQL based permissions for all of its servers, the 1.7 version crashes the entire server when adding/removing one permission node from it. However, I have created a 1.8 only server who's soul purpose is to edit permission nodes. The 1.8 and 1.7 servers are both connected to the same MySQL database. The 1.8 Server does not experience a crash when I edit a permission node. I would really like to keep 1.7 on my network (I know its unstable, however, most of the other plugins I use are discontinued.)

Other Information:
+ This happens on all my other 1.7 servers connected to the MySQL database.
+ EzRanksLite does not recognize some groups that are not created with the 1.7 server, however, the 1.8 server recognize them.
+ (Might not be related:) When I do /pex backend file & /pex import sql on the 1.8 server, it crashes or doesn't get all groups.

If you would like the logs when I issue "/pex group Default add permission.node" ask below, or if you need any other information.

Does this have to do with the scheme_version in the MySQL database? If you need the scheme_version, you may ask for that as well.

Thanks!
 - CzE
Lead Administrator of ClashNetwork

**Comment by zml2008** [comment]
1.22 and 1.23 are the same except for 1.7 and 1.8 compatibility (respectively), so you shouldn't see any differences. Maybe some implementation differences in the server?

Keep in mind that you may have some value tearing across servers since each server will have its own cache -- you'll have to do /pex reload whenever you change group settings (user data should be refreshed on each login)

**Comment by CzEMC** [comment]
Okay, thanks for the information.

Closes #2270
