### ISSUE TITLE
PermissionsEx some groups cannot chat

### ISSUE THREAD

**Issue by rockmanvnx6** [PEXPlugins/PermissionsEx#2281]
I'm using bukkit 1.8.8, permissionsEx and chatEx lasted version.
The problem is users in groups "Stone" and "Admin" cannot send messages, the messages only display when they are OP.
There is no crash showed in the log, my log: http://pastebin.com/gaJ7FaEi
PermissionsEx.yml : http://pastebin.com/8FivxWSG
I have been dealing with this problem for a week and I could not find the solutions although i've been searching on google, try to delete groups and recreated again. I really need a help, thanks
* The messages still display on the log chat of chatEx but it doesn't display on the screen as well as the git console.

The group cannot send messages in here are Stone and Admin

**Comment by zml2008** [comment]
Your permissions file doesn't seem to have anything blocking chat -- for that you probably want to check with the ChatEx dev.

Also do be aware that in your permissions file you've given everyone Iron and above permission to do anything -- since you gave them permissions.* they can assign themselves permissions however they want.

**Comment by rockmanvnx6** [comment]
what's another choice apart from ChatEx, it's no longer supported anymore.
