### ISSUE TITLE
Permissions not reloaded for online player using NetEvents

### ISSUE THREAD

**Issue by idkw** [PEXPlugins/PermissionsEx#2288]
### Issue

When using NetEvents plugins, if I add a permission node of an online player from the master NetEvents server, the permissions of the player aren't reloaded.
It only reloads the player's permissions if he's not online.
### How to reproduce

**Scenario 1 : player (testPlayer) online**  
1. Login on server 2 with testPlayer
2. Command from server 2 (netevents slave)
   `/pex user testPlayer check test.node` -> null  
3. Command from server 1 (netevents master) 
   `/pex user testPlayer add test.node`
4. Command from server 2 (netevents slave)
   `/pex user testPlayer check test.node` -> null  

_Result : testPlayer's permissions weren't updated_

**Scenario 2 : player (testPlayer) offline**
1. Command from server 2 (netevents slave)
   `/pex user testPlayer check test.node` -> null   
2. Command from server 1 (netevents master) 
   `/pex user testPlayer add test.node`
3. Command from server 2 (netevents slave)
   `/pex user testPlayer check test.node` -> testPlayer has test.node

_Result: testPlayer's permissions were updated_
### What I expected

The expected behavior should be that in both scenarios (player offline or online) it should update the player's permissions with the new permission node.

**Comment by CzEMC** [comment]
For senecio 1, after you have issued the command to set the players permission, can you issue "/pex reload" and feed back results?

**Comment by idkw** [comment]
yes if I issue /pex reload, the check test.node works the same as in scenario 2 but it should work without doing this reload, otherwise it's useless :/

**Comment by CzEMC** [comment]
Well, NetEvents doesn't edit PermissionEx's permissions in memory. The reason why pex reload is fixing it is because pex is replacing the permissions in memory with the ones on file. When a player joins (thus scenario 2) pex will commit that players permissions to memory. In scenario 1, the player is logged in and pex will not continuously to search for new permissions.

A developer will either have to change NetEvents API to change whats in memory, or you can change your plugin that handles global command handling. I use ExecuteEverywhere for global command handling. (Requires A redis server to work)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
