### ISSUE TITLE
Lag with Magicspells

### ISSUE THREAD

**Issue by LaughNgamez** [PEXPlugins/PermissionsEx#2296]
I've used the plugin Magicspells for years at this point and it works wonders, unfortunately after recently switching to PEX I noticed a combination of the two causes a noticeable 1-5 second lag when a player joins.

I've tested clearing all the configs of PEX & using MySQL and none of these seem to remedy it. Magicspells worked fine with other Permission plugins but only pex throws this CPU spike when someone joins.

Any help approaching this issue is greatly appreciated, I've done timings reports and all they display is the connection handler event being high. Through process of elimination and much testing I determined this was PEX causing the issue with Magicspells. 

I'm wondering if there's anything to be done as I have around 1k Magicspells "spells" with the "always-granted: true" option set. This means all users have access to these spells and I imagine it's what is causing the lag. A player joining, it checking the 1k spells causing the lag.

Removing a portion of the spells removes a portion of the lag although there has to be 0 spells for it to not be noticeable. I know this could be seen as a Magicspells problem the thing is though that Groupmanager does not cause the issue nor do other permission plugins.

Help with this is greatly appreciated and I'm willing to work to fix this issue in any way. I've been dealing with other issues for a while now and switching to PEX fixed them all until this popped up. I'm willing to donate to the project if needed to fix this issue as I'm frankly fed up with months of different lag busting.

**Comment by KanjiOkami** [comment]
I am having this exact problem and as far as I can tell from turning debugging on in Pex it is because on player join Pex is doing things like this:

[02:50:48] [Server thread/INFO]: [PermissionsEx] Updating superperms for player Darrius_Morgoth
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.tempgrant.woodwisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.grant.woodwisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.tempgrant.aoe_wisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.grant.aoe_wisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.tempgrant.missile_wisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.grant.missile_wisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.tempgrant.multi_wisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.grant.multi_wisp', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.tempgrant.effwisp1', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.grant.effwisp1', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.tempgrant.effwisp2', no match found (CACHE MISS)
[02:50:48] [Server thread/INFO]: [PermissionsEx] User Darrius_Morgoth checked for permission 'magicspells.grant.effwisp2', no match found (CACHE MISS)

And thats not even a fraction of the output. I dont know why it does it or what it means and ive been searching for a long time for a way to fix it so you are not alone with the problem.

**Comment by CzEMC** [comment]
I'm assuming the magicspells plugin still checks permissions regardless of the config option. And yes, your lag spike is caused by pex downloading permissions from its MySQL server. Sadly, this is a bottleneck that is not yet planned to be fixed.

Perhaps, contact the developer if he/she can add a config option to not check for the said 1K permissions?

**Comment by KanjiOkami** [comment]
Sadly he announced he wont be working on it much outside of an as he needs it basis so there may never be a resolution then.

**Comment by CzEMC** [comment]
A file might be a bit faster, considering that pex will not have to check 1K permissions from a SQL server. And that it can relay on memory.

**Comment by KanjiOkami** [comment]
It isnt much better, that log snippet is from using a file and it still has a decent delay on player join and when using c list as it goes though all the nodes.

**Comment by LaughNgamez** [comment]
This occurs with File or MYSQL other permissions plugins don't have this problem

**Comment by CzEMC** [comment]
Other permissions plugins don't have the lag issue?

This might be a thing @zml2008 will have to look into

**Comment by KanjiOkami** [comment]
I can somewhat confirm this after some initial tests with bperms. Its a pain to change to but the fact that lag is reduced is reason enough to deal with it. Ill definitely come back to PEx in the future f its changed.

**Comment by LaughNgamez** [comment]
This is still an issue hopefully it can be looked into, only PEX has this issue.

**Comment by LaughNgamez** [comment]
Hopefully based god @zml2008 can fix this, I'd be so happy.

**Comment by KanjiOkami** [comment]
I dont know if this will help but we started using Massivelag so I thought I would share the log it makes of the lag.

It seems to come in two parts. The first upon initial login and the second seems to be mostly permissions based.

[MassiveLag Log.txt](https://github.com/PEXPlugins/PermissionsEx/files/149581/MassiveLag.Log.txt)

**Comment by LaughNgamez** [comment]
Hopefully this can be fixed

**Comment by KanjiOkami** [comment]
Just out of curiosity, is there anything else that could be provided to help with this in some way?

**Comment by TheComputerGeek2** [comment]
Better management of your magicspells configuration would be effective in reducing lag, make sure to make spells as helper spells when applicable, that is one of the most dramatic performance boost changes you can make. Hit me up on the magicspells forums if you need further help with it.

**Comment by LaughNgamez** [comment]
@TheComputerGeek2 That comment isn't relevant here. Its already been made perfectly apparent that this issue only happens on PEX and not other perms plugins.

**Comment by zml2008** [comment]
Unfortunately checking lots of different permissions is basically the worst case scenario for PEX's permissions checking logic in 1.x. I'm not sure if there's any trivial way to resolve this without the architectural changes in 2.x.

**Comment by KanjiOkami** [comment]
@zml2008 I take it that 2.x isnt for versions of bukkit or not for the version we are running?

**Comment by LaughNgamez** [comment]
@zml2008 @KanjiOkami Is there any luck with PEX 2.0 fixing this issue? It would be greatly appreciated if it's possible to work on 1.9 spigot.

**Comment by KanjiOkami** [comment]
Ive barely been able to get past the enormous changes between version between the two. It way too jarring for me, most of my old pex setup doesnt work. Though i am also not the most capable with setting up so maybe give it a shot yourself. I personally dont like the way just about every part of the plugin has changed. From commands, nodes, formatting, etc. It feels like a whole new plugin to be honest. 

No insult intended though, I just wasnt expecting so many changes.

**Comment by TheRonDee** [comment]
I'm having the same exact problem, has anyone found a solution to this problem?

**Comment by TheComputerGeek2** [comment]
It should be possible to mitigate this issue slightly by configuring magicspells to have some spells share permissions as it sounds like the issue is pex having to check a bunch of different perms. Each spell in magicspells can be configured with an option called permission-name. you can use that option to make several spells share the same node. An explanation of how the option works can be found here http://nisovin.com/magicspells/spellconfiguration#general_spell_options

I noticed that in one of the debug log sections, a lot of the permissions being checked seemed to be components of one main spell and wouldn't have any reason to need a separate permission.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
