### ISSUE TITLE
Unable to remove context

### ISSUE THREAD

**Issue by bloodmc** [PEXPlugins/PermissionsEx#2320]
It seems I'm only able to clear out permissions for a context using the following code

`
player.getSubjectData().clearPermissions(ImmutableSet.of(claim.getContext()));
`

I see no way to wipe out a context from a permissions file. In GriefPrevention, players can delete claims which is the context I use in PEX. Upon deletion I want to remove all references to the context in the permissions file.

**Comment by zml2008** [comment]
part of this done by cleaning up empty context segments.

other part is exposing bulk operations so data (such as contexts) can be removed from all subjects.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
