### ISSUE TITLE
[Question] PEX API in my plugin?

### ISSUE THREAD

**Issue by Kev575** [PEXPlugins/PermissionsEx#2324]
Hey everyone,
I have a question. Am I allowed to add PEX support to my plugin, but in another way you think.
I'm currently coding at my spigot plugin KevsPermissions [GitHub](https://github.com/Kev575/KevsPermissions) [SpigotMC](https://www.spigotmc.org/resources/kevspermissions.16549/).
I would create the class PermissionsEx.java and add every method from the original one.
First of all - would that work?
And the more important one - am I allowed to do that?

Kind Regards
Kev575 :)

**Comment by zml2008** [comment]
In theory that would work -- but doing that has some chance of requiring your plugin to be released under the GPLv2 or later (mostly depending on how various court cases on the copyrightability of APIs get resolved (Speaking from US copyright law here) iirc). Also, it's probably a bad idea since PEX 1.x's API is not that great (and requires implementing a bunch of other classes too) -- just providing an implementation of Vault services is probably the best way to go, since that's an actual API designed to be implemented by multiple permissions plugins.

**Comment by Kev575** [comment]
Thanks ;)

**Comment by Kev575** [comment]
Wait!
I don't have to change my license, I guess.
I just want to create a class called PermissionsEx, add the functions from the original one and return my methods.
Do I really have to change my license? There would no code from PEX...
