### ISSUE TITLE
"Unless this server is configured to integrate with a supported proxy"

### ISSUE THREAD

**Issue by JohOply** [PEXPlugins/PermissionsEx#2333]
Hi guys

I have this error, but the link doesn't work

[11:45:21 WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs _may not be stable_!

Can you help me please?

**Comment by zml2008** [comment]
Whoops! That URL shortener is down now I guess -- It's supposed to point to https://github.com/PEXPlugins/PermissionsEx/wiki/Migration-and-UUIDs#uuid-support--top

I'll fix that eventually.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
