### ISSUE TITLE
PermissionsEx remove some permissions (MySQL) /!\

### ISSUE THREAD

**Issue by Blamo27** [PEXPlugins/PermissionsEx#2347]
Hello,
My PermissionsEx is set to save the data in a MySQL database.
When I run "/pex reload", some permissions can be randomly removed.
I think It's because I have a lot of permissions => max(id) = 7000
The auto_incrementation is very strange ... 6000 to 7000 for example
Can you help me ? Thanks you.

**Comment by Stormbow** [comment]
Are you using McMyAdmin control panel?

**Comment by Blamo27** [comment]
I'm not using McMyAdmin .. :/

**Comment by BlackRavenMC** [comment]
Same problem

**Comment by Blamo27** [comment]
@Stormbow I'm not using McMyAdmin

**Comment by Blamo27** [comment]
@Stormbow Is it a PermissionsEx issue ?

**Comment by Stormbow** [comment]
I don't think it's a PEX issue.  Zml may know more.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
