### ISSUE TITLE
[PEX 1.9] PermissionsEx permissions not working when changing world directory

### ISSUE THREAD

**Issue by HMlol** [PEXPlugins/PermissionsEx#2348]
I've been trying to set up PermissionsEx for 1.9, but I can't seem to get it working.

For instance: I can't acces any of the PEX commands, altough all the permissions are given to the 'Owner' rank. It also won't register any other permission of these mods:
- UltimatePluginHider
- Vault

The only permission that does work is - modifyworld.*...

I linked a .zip file with the server log and the permissions.yml file, is there something I did wrong or something?

[Help   (07032016).zip](https://github.com/PEXPlugins/PermissionsEx/files/161913/Help.07032016.zip)

**Comment by Stormbow** [comment]
You can massively reduce the overall length of your file by using global permissions instead of giving the same permission nodes to every group on every world, and by giving your staff ranks permissions.* instead of trying to list all of the PEX nodes.

Use [Debug Mode](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/84760-minecraft-pex-troubleshooting-guide/?post=2) to find out where you're missing permissions.

**Comment by HMlol** [comment]
Thanks for the tips, cleaned the permissions file up with inheritance and such, but haven't tested anything yet

**Comment by HMlol** [comment]
I've just tested the new permissions.yml... The debug mentions a so called "Cache Miss" with about every command I try... The commands also don't work, unless you're in OP.

Am I doing something wrong here or?
[Help   (08032016).zip](https://github.com/PEXPlugins/PermissionsEx/files/163757/Help.08032016.zip)

**Comment by Stormbow** [comment]
Where did you get your "Essentials" download?  It could be a version compatibility issue since the 'real' (original) "Essentials" was discontinued at version 1.8.1 because ["bukkit is dead"](https://twitter.com/KHobbits/status/649391453945339904).

**Comment by HMlol** [comment]
Dear Stormbow,

I've just switched to spigot 1.9, but PermissionsEx is still giving the 'Cache Miss' problem...

**Comment by Stormbow** [comment]
Ok, let me see your new console log and your permissions.yml that uses the condensed permission lists.

**Comment by HMlol** [comment]
I only have the worlds Survival, Survival_the_end and Survival_nether as of right now, and i'm planning to add more worlds, so that's why there are no global permissions set. 

Also, does it matter that the location of the world is changed? (not in the server folder itself, but in my C:\Users\Install\AppData\Roaming\.minecraft\saves folder)

I've added the permission.yml file, together with the latest.log file, as per your request.
[Help   (10032016).zip](https://github.com/PEXPlugins/PermissionsEx/files/167744/Help.10032016.zip)

**Comment by Stormbow** [comment]
I've never moved the world folders, so I'm not sure that's a good idea at all.  I've even less of an idea on how that could impact all of your plugins...

The 'latest.log' in your zip file is corrupted and can't be extracted.  I tried downloading it a few times.

One thing I need to make sure of here, now that I thought of it, you're getting your permissions.yml file from inside the PermissionsEx folder, right?  Not using the permissions.yml file in your server's root directory, right?

**Comment by HMlol** [comment]
Okay, I'll send the files again later, because I'm away now...

I am getting the permissions.yyml file from /plugins/PermissionsEx/permissions.yml

The server is setup like this:

**Comment by HMlol** [comment]
Sooo, just tested a few things on my server and there seems to be a problem with the inheritance system in PermissionsEx.
I've updated my file and it should theoretically work... But it doesn't...
PermissionsEx notes in the log that it started successfully and that there are no problems to report...
But all the prefixes and suffixes are gone...

Here are the maps which contain the server and the worlds, to give you guys an overview in how my server is currently set up. That will also give you the latest.log and the permissions.yml file.
NOTE: The latest test was done on the 'normal' server, NOT the 'beta' one...
NOTE 2: I've gotten rid of the actual files inside the worlds folder, otherwise I couldn't upload the file.
[Help   (16032016).zip](https://github.com/PEXPlugins/PermissionsEx/files/176758/Help.16032016.zip)

**Comment by Stormbow** [comment]
Which chat management plugin are you using to get your prefixes/suffixes displayed in-game?  (PEX itself doesn't display them, just gives you a place to store the info for other plugins to access.)

**Comment by HMlol** [comment]
Vault is installed as a Chat manager, so that should be alright.

I did also delete the plugin jars to make the file lighter to make it able to upload.

The installed plugins are:
(- Essentials on the Beta one)
- PasswordProtect
- PermissionsEx
- Vault

**Comment by HMlol** [comment]
Did some more tests, and it seems that the group inheritance doesn't work... Don't know why tough...

Added some more logs which show the problem, the 17_1.log.gz is with the group inheritance, the rest of the logs without the group inheritance system.

The old problem still remains, no permissions are granted, even tough they are listed...
[Help   (17032016.zip](https://github.com/PEXPlugins/PermissionsEx/files/178251/Help.17032016.zip)

**Comment by Stormbow** [comment]
Ok..  I've never seen anyone at all that uses Vault as their chat manager, so I don't know anything about that or if it even works anywhere on any server.  Since it's not functional as a chat manager on your server, I'm guessing you'll need a different chat manager.

Did you move your world folders back into their original/regular location before this testing?

Your "not working" permissions.yml file has no global permissions at all for the "Owner" group, and ~~essentials.help~~ on the world named "Survival" only, and the debug output doesn't show me which world you're on when attempting the command.  Same for Tml32 and being in the "Friend" group.

So, you're probably gong to need @zml2008 to come in here and troubleshoot this because I personally don't think PEX is functional on 1.9 servers.  I haven't seen any servers running 1.9 and a fully functional (or even partly functional) PEX yet.

**Comment by Stormbow** [comment]
(Damn ticket wouldn't update properly.  Had to close/open/reassign it multiple times to get it listed correctly.)

**Comment by HMlol** [comment]
Vault functions fine, its definitely Pex messing things up.
We test all the commands on the "Survival" world, so that should be fine.
Also, Pex functions fine on 1.9 servers, it only messes up big time when changing the location of the worlds folder.

Now, I've got the worlds setup on a different location so my beta and normal server can run the same worlds without copy and pasting...

So, once again, the server runs fine as long as you don't change the location of the worlds folder.

It's almost like Pex doesn't find the worlds its self, but I cant set it up properly. 
Here's how I've done it in the server.properties file:
world: ../Server (Spigot 1.9) Worlds/Surival

Now, for Pex this doesn't work,so IMO there are two main thing to consider:
- Either make a way to follow a path to the right directory like in the server.properties file:

groups:
    pvp:
        options:
prefix: ' '
    suffix: ' '
    

- Or make an option in the config where you can change the target folder.

**Comment by zml2008** [comment]
On March 18, 2016 9:16:01 AM PDT, Harm <notifications@github.com> wrote:
>Reopened #2348.
>
>---
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PEXPlugins/PermissionsEx/issues/2348#event-595116558

This seems like a spigot bug - I'm travelling, could you report it to them? (Link to this issue when you do).

**Comment by HMlol** [comment]
I've just reported it: 
https://hub.spigotmc.org/jira/browse/PLUG-134

**Comment by HMlol** [comment]
The bug reported to spigot is closed, saying that the system is faulty on the plugin side...

**Comment by Stormbow** [comment]
I was under the impression that the issue was that permissions were not being distributed to multiworld folders when the path was changed.  The way you posted it over at Spigot was that the issue was prefixes were not being distributed to multiworlds.  I could have told you PEX doesn't have support for multiworld prefixes/suffixes.  :X

**Comment by HMlol** [comment]
The problem is --> The PermissionsEx per world permissions stop working as soon as you change the file locations of the worlds. The spigot team says this the plugin's fault, and that it doesn't have anything to do with the spigot builds.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
