### ISSUE TITLE
PermissionsEx stall problem [1.22.10]

### ISSUE THREAD

**Issue by linkinkov** [PEXPlugins/PermissionsEx#2350]
My problem that i have 7-10 server connected to one database (for read permission), all server connected to the remote server. Can implement some cache or something else to fixed it.
Stall report (by sampler 1.58): http://pastebin.com/95RcdcRA

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
