### ISSUE TITLE
Feature: /pex user <user> add <permission>[ permission2 permission3 ...etc]

### ISSUE THREAD

**Issue by leasoncre** [PEXPlugins/PermissionsEx#2353]
1.can you add support for adding/removing multiple permission nodes in one command please? 
[outdated and defunct groupmanager can do this, why not pex? o.O]

separate multiple permissions with a space or comma?
-when removing, ignore perms the user doesn't already have.

**Comment by leasoncre** [comment]
Q: can you add a test so when adding permissions you have to have a 'dot' in the permissions node?

ie: 'testnode' is not a valid permission node in any plugin (as far as i know)m but 'test.node' would be valid.
can this be checked before adding permission nodes? (would help prevent accidentally adding groups as permissions by accident, for example)

**Comment by lasercar** [comment]
The permissions would need to be separated by commas, because the next argument after the space is used for adding a permission for a specific world. `/pex user <user> add permission world`
This same idea could also works for adding multiple comma-separated worlds too!

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
