### ISSUE TITLE
Feature: messages.yml

### ISSUE THREAD

**Issue by leasoncre** [PEXPlugins/PermissionsEx#2355]
implement a messages.yml -or- en.yml file so users can changes the messages that are received when commands/messages are executed/sent.
+would be great for foreign languages!

personally, i'd like to change some simpler things: like making the plugin message prefix shorter.

**Comment by zml2008** [comment]
PEX2 has been designed to support localization, and can be localized with gettext po files.

This mechanism could pretty easily be extended to support user-customizable messages

**Comment by leasoncre** [comment]
idk what 'gettext po' is, but it sounds like ya'll already planned what i suggested :)

**Comment by zml2008** [comment]
po files are a relatively standard localization file format (basically means a bunch of fancy tools and sites exist to make it easier to work with the format)

**Comment by Mishyy** [comment]
I haven't seen anything about this being added yet, was it just forgotten about, a lot of people want this.

**Comment by Stormbow** [comment]
> I haven't seen anything about this being added yet, was it just forgotten about, a lot of people want this.

PEX 2 is still in development.  That's about all I can tell ya.  (I mostly handle PEX 1 issues, and there won't be any more major features added to PEX 1.)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
