### ISSUE TITLE
Can't connect my second server

### ISSUE THREAD

**Issue by titivermeesch** [PEXPlugins/PermissionsEx#2360]
Hi there,

I have a problem while connecting my second server on the sql database.
I installed pex on the hub and faction server and connecting them to the same sql database.
The problem is that the ranks are only working on the hub and on the faction server it generate an error. Please help me. (PS : he says in the console "Succesfull connected to the sql database )
![screen sql error](https://cloud.githubusercontent.com/assets/12189066/13887601/ecd1b87c-ed3c-11e5-8781-c93e1d0ecca3.png)

**Comment by titivermeesch** [comment]
bump

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
