### ISSUE TITLE
/promote /demote commands don't-work

### ISSUE THREAD

**Issue by leasoncre** [PEXPlugins/PermissionsEx#2362]
First, it DOES work, BUT, only the original command, not the aliases
`/pex promote <username> <Ladder>` & `/pex demote <username> <Ladder>` work perfectly
however:
`/promote` and `/demote` do not work beyond a bad help format

examples of the issues:
1. bad help info/no help
`/pex promote` (nothing or anything after; that is invalid)
prints: "Error in command syntax. Check command help."
should say: `/pex promote <user> <ladder> - Promotes <user> to next group`
(same thing for /pex demote)

2. bad command:
`/promote`
prints: "Usage:",`/promote <user> - Promotes <user> to next group`
should say: "/promote <user> <ladder> - Promotes <user> to next group"

`/promote <username>`
prints: "Promotion error: User are not in this ladder" [[what is this actually supposed to mean? the promoter isn't in the group, or the promotee isn't in the group? (i assume the latter)]]
should say: `/promote <user> <ladder> - Promotes <user> to next group`

`/promote <username> <ladder>`
prints: "Error in command syntax. Check command help." (EVEN IF IT'S A VALID LADDER)
should actually work...

3. Please make the ladder name NOT case SeNsItIvE. (or any command that may also have this issue)

thanks.
PS. noticed alot of grammatical errors like "user are not", if a messages.yml is instituted in the futures it would be easier to fix these, rather than writing bug reports for silly grammar things :)

```
git-Spigot-f04e043-622014a (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
PermissionsEx version 1.23.4
```

**Comment by Stormbow** [comment]
Some good suggestions.

use ``` (3 grave accents, the key left of 1 on standard English keyboards) before and after commands and permission nodes to retain the formatting in this tickets system.  For example:

```permission.mode``` and ```/promote <user> <ladder>```

If you look at your post, you'll see that a very large majority of what you intended to say is missing when compared to the 'edit' text.

**Comment by zml2008** [comment]
Looking at [the code](https://github.com/PEXPlugins/PermissionsEx/blob/1.23.x/src/main/java/ru/tehkode/permissions/bukkit/commands/PromotionCommands.java#L159), it seems that the exact same code is executed for the two aliases. The only difference here is that the `[ladder]` optional argument was left out, I presume unintentionally. This has been fixed in the 1.x branches (not built automatically, but will make it into the next release).

However, the bad usage messages (and assorted grammatical errors/fixed translations) are a limitation of 1.x's command system. These are being improved in 2.x.

Making the ladder name case-insensitive won't be done for 1.x, but it has been done for 2.x.
