### ISSUE TITLE
permissions for pex need work (or updating on wiki)

### ISSUE THREAD

**Issue by leasoncre** [PEXPlugins/PermissionsEx#2363]
https://github.com/PEXPlugins/PermissionsEx/wiki/Commands

**[[Feel free to skip to the one-line summary at the end]]**

i've been using this to set permissions (for pex) for my admins. but it looks like alot of these commands' permission nodes give more than i want. or the page hasn't been updated in forever.

ie: 
if i want to let my admins list a user's info with `'/pex user <user>'`, i also have to allow them access to: `'/pex user <user> add <permission>'`, which i do NOT want.
`"permissions.manage.users.permissions"` i assume is the 'node' and what the heck is with the `".<user>"` at the end?

i believe the different commands should have more per-command node defining
`permissions.manage.users.permissions.add` - /pex user <user> add <perm>
`permissions.manage.users.permissions.list` - /pex user <user> \AND\ /pex user <user> list
`permissions.manage.users.permissions.remove` - /pex user <user> remove <perm>
`permissions.manage.users.permissions.set` - /pex user <user> set <option> <value>

there are more instances like this one on the page (Alot imo) that confuse me and are over-generalized like the above (not specific enough node). please help/fix.

PS. who puts `'<user>'` in a permission node?, i can see it for a group, but specifying a single user is probably the dumbest thing ever. also very confusing that it says this after nearly EVERY node on the page. if it does work per-user in the node, great, but it's listed as the end-all of every node, and Required?! even dumber)

PS. the html on that chart should be set to auto width, description column is quite squished in most of the tables.

**Summary: more specific permission nodes, clearer/more-refined wiki.**

] Edit by Stormbow: code markup around permission nodes added. [

**Comment by Stormbow** [comment]
What page are you talking about that has these errors in them?

**Comment by Stormbow** [comment]
```permissions.manage.users.permissions.<users>``` is the complete permission node; ```<users>``` is replaced with an exact user's name.  This is particularly for servers who want specific control over specific users granted to specific admins.

The suggested changes may or may not be added to PEX 2.0; @zml2008 will be the one who decides on that matter.  But, to be completely frank, anyone who can not be trusted to be given admin access to a server, should not be given admin access to a server.  Not even a little bit of admin access.  (That's my personal opinion, of course.  ![2 cents](http://img.photobucket.com/albums/v298/Stormbow/2_cents.gif))  It should also be noted that if someone needed to check a user or group for a permission, there are already permission nodes in place for those activities.

Calling something "dumb" because you, personally, do not have a reason to use it is actually "dumb" itself.  ;-)

The github website doesn't allow for table formatting that you're suggesting.  The entirety of the usable space is as wide as you see it.  I'd know-- I've made changes to those pages many, many times trying to get the tables wider.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
