### ISSUE TITLE
Re: Previous fix

### ISSUE THREAD

**Issue by Nentify** [PEXPlugins/PermissionsEx#2381]
https://github.com/PEXPlugins/PermissionsEx/issues/2274

Can this be fixed?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
