### ISSUE TITLE
Unknown column 'prefix' in 'field list'

### ISSUE THREAD

**Issue by Wyja** [PEXPlugins/PermissionsEx#2384]
Hey Guys.
PermissionsEx has worked but we must clear the MySql tables and reload the Permissions.yml new. Now - after the reupload of the yml in a cleared Database, PermissionsEX says : [PermissionsEx] Error occurred with PermissionsEx! Please post it to http://git.io/<html><body>You are being <a href="https://git.io/create">redirected</a>.</body></html>. Full error:
ru.tehkode.permissions.exceptions.PermissionBackendException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'prefix' in 'field list'

We got a actualy MySql version. we have set the Schema-Version in the permission.yml to 1. See please here : schema-version: 1 and we have no double data of this in our database. PermissionsEx worked fine bevor we have cleared the Tables and reuploaded the Permissions yml.

Here the whole Error:  http://pastebin.com/SEzb60H7

Thx

**Comment by Stormbow** [comment]
This error comes up when you have 2 schema-version entries in your database.  Keep the entry which is 'schema-version: 1' and delete the other.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
