### ISSUE TITLE
Spigot 1.9 and PEX 1.23.4

### ISSUE THREAD

**Issue by Stormbow** [PEXPlugins/PermissionsEx#2385]
PEX does not function properly in this instance.  MANY people are coming to the forums with this problem and I have no solution for it.  The permissions.yml files are correct.  The config.yml files are correct.  But PEX still does not function properly on these servers.

[One example case.](http://dev.bukkit.org/bukkit-plugins/permissionsex/forum/116099-permissions-ex-1-23-4-and-spigot-1-9/)

**Comment by bys1** [comment]
What is the problem exactly? Can I update my server to 1.9.2 or not?

**Comment by TNTUP** [comment]
Bad timings on 1.9.2 with PEX 1.23.4 @ Spigot 1.9.2: https://timings.spigotmc.org/?url=15766846

**Comment by Stormbow** [comment]
Preliminary reports indicate that EVERY group MUST now have an inheritance, even if the set is empty (inheritance: []).

Try this on your 1.9 servers and post the results.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
