### ISSUE TITLE
[2.0] Groups disappears

### ISSUE THREAD

**Issue by Zartec** [PEXPlugins/PermissionsEx#2404]
If i try to remove and add Groups via

Remove:
`SubjectData data = _permission.getUserSubjects().get(_player.getIdentifier()).getSubjectData();
        data.removeParent(SubjectData.GLOBAL_CONTEXT, _permission.getGroupSubjects().get(group));`

Add:
`SubjectData data = _permission.getUserSubjects().get(_player.getIdentifier()).getSubjectData();
        data.addParent(SubjectData.GLOBAL_CONTEXT, _permission.getGroupSubjects().get(group));`

`_permission is an Sponge provided PermissionService`

somtimes the new group disappears from users cached Subject.
The parent entry for the group still exists inside `permissions.json` and returns back after `/pex reload`.

PermissionsEx: 2.0-SNAPSHOT Build 123
SpongeAPI: 4.1.0-SNAPSHOT-3e39b9c
MinecraftForge: 11.15.1.1808

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
