### ISSUE TITLE
Empty groups "doesn't exist" when listing members

### ISSUE THREAD

**Issue by Plumeex** [PEXPlugins/PermissionsEx#2406]
Hi, small issue I noticed when checking the members of a group.

My group has no members, but works fine (its information is displayed with `/pex group myGroup`).
However when I used `/pex group myGroup users`, the command returned:
`Group "myGroup" doesn't exist`.

I tried with other (non-empty) groups and their members were listed fine.
So, the issue here is that you would expect a message like "This group has no members", instead of "doesn't exist".

PermissionsEx version 1.23.4

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
