### ISSUE TITLE
Regex permission returning null

### ISSUE THREAD

**Issue by BlackBeltPanda** [PEXPlugins/PermissionsEx#2410]
Using PermissionsEx 1.23.4 with MySQL.

I gave a group these permissions:
- libsdisguises.disguise.(pig_zombie|spider|creeper|cave_spider)
- libsdisguises.disguise.endermite
- libsdisguises.disguise.wolf.(setsitting|settamed|setcollarcolor)
- libsdisguises.disguise.(wolf|chicken)

Players in that group are unable to use the pig_zombie, spider, creeper, cave_spider, and chicken disguises. They are able to use the endermite and wolf disguises.

When I use "/pex user <user> check libsdisguises.disguise.creeper" on a player in that group, it returns, "Permission "null" has not been set for "Player"".

With "/pex user <user> check libsdisguises.disguise.endermite", it returns, "Player has "libsdisguises.disguise.endermite"".

With "/pex user <user> check libsdisguises.disguise.wolf", it returns, "Player has "libsdisguises.disguise.(chicken|wolf)"".

With "/pex user <user> check libsdisguises.disguise.chicken", it returns, "Player has "libsdisguises.disguise.(chicken|wolf)"".

**Comment by Stormbow** [comment]
I don't believe you can use `.(pig_zombie|spider|creeper|cave_spider)` in PEX.  Does the group work if all of those creatures are listed on their own node?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
