### ISSUE TITLE
OP all permissions?

### ISSUE THREAD

**Issue by P0Pss** [PEXPlugins/PermissionsEx#2418]
Is there anyway to give op all the permissions to pex or gives a rank all the permissions rather than having to write up all the permissions?

**Comment by Stormbow** [comment]
First and foremost, don't use /op on anyone.  The OP command is intended for vanilla servers that have no plugins at all.  Using that command on someone can make you think the server (that is using plugins) is setup correctly when it actually is not.

If you want to give all permissions from every plugin on the server to someone: `/pex user <user> add * [world]`

If you want to give all permissions from every plugin on the server to a group: `/pex group <group> add * [world]`

`<user>` and `<group>` must be replaced with a username or a group name.
`[world]` would be replaced with an exact world name, if you're using multiworld or multiverse settings.

Keep in mind that both of the above commands also give the user/group permission nodes that are not wanted, such as a vanish plugin's permission node that makes them join the server silently (not announcing that joined) and invisibly (unable to interact with anything on the server, no breaking blocks, picking up items, etc.).

If you're the server owner, you may want to give yourself all of the permission nodes from a specific plugin, like all of the PEX commands so that you can use all of those commands while you're testing groups on the server.  In that case, you would use the following command: `/pex user <user> add permissions.*`
