### ISSUE TITLE
user-add-groups-last: false - Adds last Group when it should be Denying this.

### ISSUE THREAD

**Issue by ZachryWilsn** [PEXPlugins/PermissionsEx#2427]
This is part of my config.

  **user-add-groups-last: false
  log-players: false**

As you can see the setting is to false.
Yet when I promoted or demoted a player they still have the last group.
Example:  

**GroupA
GroupB
GroupC**

If in A then promoted to C you will have A,B, and C. This should not happen and is causing
some complications to say the least.

Please take some time to fix this basic feature of your plugin.

**Comment by zml2008** [comment]
The `user-add-groups-last` option only changes whether new groups are added to the top or bottom of the parents list. You should be using the `group set` command rather than `group add` to only have one group for a user.

If you're using PEX's promote and demote commands this is probably PEX having some synchronization issues, and if you're using another plugin with the correct command it could also be a synchronization issue, but either way the options you're mentioning do not do what you think they do.

**Comment by ZachryWilsn** [comment]
The issue Im having is when Auto-Rank promotes a player.
Im assuming this is done via a /promote command.
When I /promote a player the group stack and same for when demoting.
The keep there Top group and also the lower Group.

Example:

If player was in GroupC then demoted to A they would be in C and A.

I never had this happen until 1.9 came along.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
