### ISSUE TITLE
[2.0-Bukkit] NullPointerException on load; empty permissions.json

### ISSUE THREAD

**Issue by jansennerd10** [PEXPlugins/PermissionsEx#2430]
Hello!

I recently updated Spigot from 1.9.2 to 1.9.4, and at the same time updated PEX to build #125. Now when I start my server, a NullPointerException is thrown when PEX tries to load. It appears PEX tried to convert my permissions.yml to permissions.json, but the new permissions.json file is empty. <s>My server won't let me connect anymore, which I realize may or may not be related.</s> _Update: My server is letting me connect now, so that issue appears unrelated after all._

I updated PEX to build #128, but this did not fix the problem.

I've attached recent server logs (since the original update) and PEX configuration files. When you have time, would you mind taking a look? (It's entirely possible I messed something up.)

Thank you so much for all your work on this plugin! Please let me know if more information would be helpful.

Environment details:
OS: Windows Server 2012
Java: 8 update 91 (64-bit)
MC: Spigot 1.9.4
PEX: build #128

[PEX Issue.zip](https://github.com/PEXPlugins/PermissionsEx/files/294822/PEX.Issue.zip)

**Comment by zml2008** [comment]
This has been fixed in 8ef4d5e. You'll have to delete the `permissions.json` and rename `permissions.yml.legacy-backup` back to `permissions.yml` -- there was an issue causing PEX to think it hadn't converted yet when it had, and try to convert a file that didn't exist anymore (`permissions.yml`), which it interpreted as an empty file, overwriting the `permissions.json`.
