### ISSUE TITLE
Cannot edit commandblocks

### ISSUE THREAD

**Issue by Inscrutable** [PEXPlugins/PermissionsEx#2439]
I have encountered some problems with commandblocks when using a recent build of PermissionsEx (Build #129) on the Sponge Community Server. I'm in the GOD group with perm default true, and I can't edit commandblocks. I'm in creative mode, but the GUI doesn't even open. Opping myself ingame or via console gives me a warning about PEX replacing the op/deop commands. 
This has been happening on SpongeVanilla bleeding builds for 1.9.4, and is now happening on SV 1.10.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
