### ISSUE TITLE
Lost userdata after player changed username

### ISSUE THREAD

**Issue by lifehome** [PEXPlugins/PermissionsEx#2440]
# Situation

Similar to #2232, my server has appeared a weird situation. A player has already played on my server for quite a period, and suddenly he reported that he lost every dime of permission. I checked on the PermissionsEX plugin, using `/pex user <playerName> info` the commands returned nothing.
# Bug

After `a previously logged in player` changed the username, PermissionsEx cannot retrieve the data.

**Comment by Stormbow** [comment]
As far as I know, user data is retrieved by the UUID since Minecraft 1.7.9 and higher.  If your server is 1.7.9+ and running in offline mode, it doesn't have UUIDs.  In that case, you should be aware that PEX does not support offline mode and you should encourage your users to not use hacked/torrented/illegally downloaded Minecraft clients and to buy the game.  ;-)

**Comment by Stormbow** [comment]
@zml2008 can answer as to how the info is accessed by PEX.

**Comment by lifehome** [comment]
I'm sorry that I failed to mention my server is in online mode, Spigot 1.10.

**Comment by zml2008** [comment]
Are you on 1.x or 2.x?

**Comment by lifehome** [comment]
2.x snapshot

**Comment by zml2008** [comment]
Ok, can you pastebin the permissions.json or upload the permissions.mv.db?

**Comment by lifehome** [comment]
Here it is:

https://gist.github.com/lifehome/cf8d1460991541fd76aa6d6f6d402546

**Comment by zml2008** [comment]
So the permissions file you posted only has you listed as a user. Is that the actual file you're running your server with?

**Comment by lifehome** [comment]
Yes indeed, no matter how many times I restart the server.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
