### ISSUE TITLE
Permission node for ranking others to a specific rank

### ISSUE THREAD

**Issue by SnowBlitzz** [PEXPlugins/PermissionsEx#2449]
A specific permission node to allow a certain group to rank other players up to a specific rank would be nice. What I mean here is for example I want my admin group to be able to do/pex user <user> parent add group Member and /pex user <user> parent remove group Member but not be able to do /pex user <user> parent add group AnotherRank

The bukkit version used to have this so hopefully it will get added soon.

**Comment by Stormbow** [comment]
"The bukkit version" of what "used to have this"?

As far as I can tell, you're talking about adding inheritances to groups.  ("parrent" is for inheritance, not "ranking others to a specific rank".)  The setting of inheritances is the job of the server owner/admin, not users on the server.

**Comment by zml2008** [comment]
This is an issue for PEX 2.0.

**Comment by SnowBlitzz** [comment]
Yeah what zml said. Sorry for not wording it properly. Couldn't find the right terms.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
