### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by timr2000** [PEXPlugins/PermissionsEx#2463]
Only appears on startup: http://pastebin.com/7Cu0C27C

**Comment by Stormbow** [comment]
`Unknown column 'prefix' in 'field list'` means you have 2 `schema-version` lines in your database, if I remember correctly.  Remove one; keep the one which is `schema-version: 1`.

**Comment by timr2000** [comment]
cant find a schema version in my mysql?

**Comment by Stormbow** [comment]
That would definitely be a problem then.  Check your permissions.yml file for the proper formatting.  For PEX 1.9+ it should follow [this basic outline](http://pastebin.com/8ZSHxauG).  If you're using PEX 2.x you'll need zml's help since I haven't used that version yet and don't know anything about it.

**Comment by Stormbow** [comment]
I'm guessing you found it.  Problem solved?
