### ISSUE TITLE
McMyAdmin and PEX

### ISSUE THREAD

**Issue by Pijanista** [PEXPlugins/PermissionsEx#2466]
I know this is fault of McMyAdmin but idk what are chance that they fix this:

So McMyAdmin put "Prefix, Suffix and Default" outside "Options"  and reload config, so that means it loses prefix,suffix until server restart. After server restart PEX automatically put "Prefix ,Suffix and Default" under "Options" is there possibilty to make it preffix and suffix compatible that they don't have to be under Options or when you do /pex reload it automatically put it under Options so there is no need for server restart.

Best regards.

**Comment by zml2008** [comment]
PhonicUK (dev of MCMA) is generally pretty responsive to issues (and knows where to get a hold of me if he has any questions about PEX), so if you brought this up with him he'd most likely be able to fix things. However, first you should make sure you or your server host have got the latest version of MCMA, since he might've already fixed things and you/your server host just are on an older version.

**Comment by Pijanista** [comment]
Thanks for fast answer, i did contact about this on their forums. But this is obvious old bug on mcmyadmin because there is guy with same problem in 2014...

https://bukkit.org/threads/permissoinsex-prefixs-breaks-upon-mcmyadmin-modifications.286905/

And ofcourse i'm using past mcma pro version.

**Comment by zml2008** [comment]
Ok, then you should update to MCMA3 -- that seems to be where the development is going.
