### ISSUE TITLE
Claimflags made by GriefPrevention are reset upon restart

### ISSUE THREAD

**Issue by SharkROAR** [PEXPlugins/PermissionsEx#2489]
So, I'm having this really weird issue where after a server restart, groups, permissions, prefixes, etc. are non existent any more, but, as soon as I do a /pex reload, everything is fine again...

How is this possible?

**Comment by Stormbow** [comment]
What version of Minecraft are you running?

What version of PEX are you using?

What are you using for your server host or console?

**Comment by SharkROAR** [comment]
Problem solved apart from the fact that claimflags made by grief prevention are reset upon restart.. 

blood said it is saved with PEX, so I was hoping you could maybe help me out?

Versions:
GriefPrevention: 35
PEX: 131
Minecraft: 1.8.9
SpongeForge: 1595
Forge: 1890
Server: Debian Linux

**Comment by Stormbow** [comment]
Ah, ok.  PEX 2.x issue.  @zml2008 will have to help you out.

**Comment by SharkROAR** [comment]
All right, thanks :)

**Comment by zml2008** [comment]
@bloodmc could you point out the relevant parts of GP where you do the setting permissions? I feel like GP is probably just accidentally overwriting permission values somewhere, or I'm just not familiar enough with how GP works to be able to understand this issue fully.

**Comment by bloodmc** [comment]
https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/FlatFileDataStore.java#L201

https://github.com/MinecraftPortCentral/GriefPrevention/blob/master/src/me/ryanhamshire/griefprevention/GPPermissionHandler.java

@zml2008  I've only heard about this issue when users are using the PEX database instead of file mode.

**Comment by SharkROAR** [comment]
@bloodmc That seems to be correct. I've recently switched from MySQL to file mode, and the issue seems to be gone (for now at least).

**Comment by bloodmc** [comment]
@zml2008 This is probably the same issue as #2457

**Comment by zml2008** [comment]
Hm, there was a bug with parents in 131 that was fixed in the 1.10.2 builds. Maybe that's what is causing this issue?

**Comment by bloodmc** [comment]
@zml2008 Can you provide an updated 1.8.9 PEX jar then with the latest fixes to see if it works?

**Comment by zml2008** [comment]
Ok, https://minions.aoeu.xyz/zml/pex-api4.jar has the latest PEX changes for 1.8.9. Try it and see if things work better

**Comment by bloodmc** [comment]
@SharkROAR Have you tried the version above to see if it fixes your DB issue?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
