### ISSUE TITLE
BUG AND FEATURE REQUEST

### ISSUE THREAD

**Issue by RAZERMC** [PEXPlugins/PermissionsEx#2490]
When you do reload pex via command the temporary permission (not group) resets too. players looses temporary perms when plugin is reloaded

Please save the temporary permission to file/sql

make main groups and subgroups 
  - main group is priority on prefixes
  - subgroup you will only inherit the permission not the prefix

when adding a group to a player (not group set) the player looses the default group permission
- work around is add the default inheritance to the sub group

**Comment by Ironic8b498** [comment]
If you have not done this already would like to see a way to use weights per world, I'm running older software that is not suppose to run on a bungee server and if I can have different weights for ranks per world I would be able to set citizen on a world to the dominate rank and another world it to another rank to be considered primary

**Comment by zml2008** [comment]
These are all intentional design decisions in PEX 1.x. The first issue can be worked around by setting permissions on a group, then adding that group as a temporary group.

The second issue will hopefully be resolved in PEX 2.0 with more flexible weight handling.

The last issue is resolved in PEX 2.0: the default group is always applied to users
