### ISSUE TITLE
Sorry, cant figure out where else to post:

### ISSUE THREAD

**Issue by bardkin** [PEXPlugins/PermissionsEx#2494]
Just want to know what the latest forge sponge version PEX 2.0 will work on and where can I find it? (I have the one from the sponge site that is marked for 1.9+..)

thanks

**Comment by zml2008** [comment]
PEX itself is independent of forge version -- it just uses Sponge (and sponge's plugin compatibility versioning, currently requiring API 5). That means that you'll want to get the matching Sponge forge mod, which lists its compatible forge version on the Sponge download page.

**Comment by bardkin** [comment]
So it will work with the latest version of Sponge (ver. 1.10.2026) then?

**Comment by zml2008** [comment]
When you download Sponge, the jar you are given will have both the api version and forge version listed, as described [in the documentation](https://docs.spongepowered.org/master/en/server/getting-started/implementations/spongeforge.html#reading-the-download-filename). Since PEX works with API 5, it'll work with whatever the latest 1.10 build of Sponge is.

**Comment by bardkin** [comment]
Awesome! thanks!
