### ISSUE TITLE
Lang file for sponge plugin

### ISSUE THREAD

**Issue by iTeeLion** [PEXPlugins/PermissionsEx#2496]
Hi! Add the lang file/class pleace. I wanna translate your plugin ^_^

**Comment by zml2008** [comment]
Localization files are split up by module, for core, bukkit, and Sponge.

Core: https://github.com/PEXPlugins/PermissionsEx/blob/master/permissionsex-core/src/main/po/keys.pot
bukkit: https://github.com/PEXPlugins/PermissionsEx/blob/master/permissionsex-bukkit/src/main/po/keys.pot
Sponge: https://github.com/PEXPlugins/PermissionsEx/blob/master/permissionsex-sponge/src/main/po/keys.pot

They aren't actually used at the moment since gettext is a bit broken, but those files are kept up to date with changes to PEX's messages.
