### ISSUE TITLE
PermissionEx Sponge - Group ladder not working correctly

### ISSUE THREAD

**Issue by MatteCarra** [PEXPlugins/PermissionsEx#2500]
I created a group Trainer (`pex group Trainer def false`)
I set it as default ( `pex default user parent add group Trainer` )
I created a child group GymLeader ( `pex group GymLeader parent add group Trainer` )
I wrote this command: `pex rank Trainer add group GymLeader`

Then I have assigned to deluxe rank Trainer ( `pex user deluxe parent add group Trainer` )
promote user deluxe -> ... was already at the top of ladder default

What did I do wrong?
Thanks for help!

**Comment by MrFoolz** [comment]
I'm wondering the same thing. However I cannot find a response anywhere on the internet pertaining to this issue?

**Comment by Stormbow** [comment]
None of the commands used in the Original Post are actual [PEX Commands](https://github.com/PEXPlugins/PermissionsEx/wiki/Commands).

**Comment by zml2008** [comment]
These are commands for PEX 2.0, which has different commands.

**Comment by Stormbow** [comment]
Ahhh, ok.  I saw that August 2016 stamp and thought this was old potatoes.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
