### ISSUE TITLE
Players have to relog to get permissions

### ISSUE THREAD

**Issue by FallenServer** [PEXPlugins/PermissionsEx#2509]
Hey guys I run PermissionEx. I have a problem whenever i /pex group (group name) add (permission) players have to relog to get the permission. Also whenever I give a player a timed permission whenever they relog it goes away... And Another bug is that when players rank up to C,D,E sometimes it will put them back down a rank and they will have to relog to fix it.

My pex config http://hastebin.com/fifapuwuzu.sm

Spigot = https://gyazo.com/e3fff2c8df4e9ae3a7eacb3ec2b9957d

Using PEX version 1.23.4

I use Spigot.1.8.8 R1

**Comment by Stormbow** [comment]
Some servers cache the changes being made to the permissions.yml file and the changes aren't reflected in the file until the server is stopped fully and restarted.  To get around this, after you've made changes to the permissions.yml file (by using commands or by editing it in Notepad), you should use the `/pex reload` command to refresh the permissions currently active on the server and this typically also refreshes the file, adding any recent changes.  (Though, you can't have the file open in Notepad or another program because the changes won't be displayed there unless you manually revert to the saved file, which brings up the most recent version of the file as if you'd just opened it yourself.)

Timed permissions are intentionally temporary.  They may be different in PEX 2.x, but as far as PEX 1.x goes (which you're using), they're not going to be saved if the user leaves the server.  I believe the workaround for this is to use temporary groups instead of temporary permissions, but the specifics of that process elude me and are somewhere here in the [Closed Tickets](https://github.com/PEXPlugins/PermissionsEx/issues?q=is%3Aissue+is%3Aclosed) collection as many people report this as a bug when it's actually not.

Since PEX itself doesn't contain any automated promotions, demotions, or other group-setting functionality, the "users in the wrong group" issue isn't actually a PEX issue.  Can you give me more details about this situation?

**Comment by Stormbow** [comment]
I'm guessing this "problem" is resolved since no comment for 5 days.
