### ISSUE TITLE
[Sponge SQL] Contexts not getting saved to database.

### ISSUE THREAD

**Issue by cartman-2000** [PEXPlugins/PermissionsEx#2512]
While using mysql as a back end, the contexts aren't getting saved to the database, which causes the contexts to be lost on the next reload/restart.

**Comment by rockmacaca** [comment]
+1

They also don't seem to have any effect while they are still in memory. After reloading or restarting, the permissions are still there, but with the context.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
