### ISSUE TITLE
Permissions 'none' add to player

### ISSUE THREAD

**Issue by essentiial** [PEXPlugins/PermissionsEx#2517]
Hello,

Since I am the last days of my server skyblock in 1.8 with the latest version of your plugin adds it to me by both UUID without reason .. the concern being that in the long therm the file may be a non-negligible weight:

   c6595875-0d23-33af-be4c-a56024be2755:
     permissions:
     - none

you have an idea of where could it come?

Regards,

**Comment by zml2008** [comment]
"both UUID"? What does that mean?

Either you have another broken plugin, or you're like trying to run 2.x commands on 1.x, which wouldn't work.

**Comment by BlackBeltPanda** [comment]
If you're using uSkyBlock, check the challenge rewards for a permission reward that gives the player the permission "none". Remove or comment out that reward and it should stop doing that.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
