### ISSUE TITLE
Players not losing permissions after being removed from a group

### ISSUE THREAD

**Issue by Wolfman750** [PEXPlugins/PermissionsEx#2522]
there is an issue where once you are removed from a group you still have that groups permissions I just tested it with the admin group (group that gives all perms)

I set myself as admin tested that I had all commands and perms then removed myself from the admin group and I was no longer in the group but I sill had all the permissions of the group

**Comment by Wolfman750** [comment]
using Pex sponge for 1.8.9

**Comment by Wolfman750** [comment]
any idea when this might be fixed?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
