### ISSUE TITLE
Problem with Special Characters in SQL DB Password

### ISSUE THREAD

**Issue by munchicken** [PEXPlugins/PermissionsEx#2524]
Sorry, I haven't had time to thoroughly isolate this issue, but I just wanted to let you know about it.  I was unable to connect to my external db server:

ru.tehkode.permissions.exceptions.PermissionBackendException: Unable to connect to SQL database
...
Caused by: java.sql.SQLException: Access denied for user 'my_username'@'myhost.com' (using password: NO)

I went through and double-checked everything, but then the "using password NO" caught my attention.  Because I did have my password in the config.  The password I was using was 12 characters long, using alphanumeric characters as well as the following special characters "#]!&" (it was auto-generated from my  db host).  I changed it to an 8 character long password, including only alphanumeric characters and now it works fine.

**Comment by Haarolean** [comment]
Was the password quoted? Like "password: 'mysuperpass'"?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
