### ISSUE TITLE
[Sponge] PEX Issues

### ISSUE THREAD

**Issue by pchard** [PEXPlugins/PermissionsEx#2537]
Hi.

I have a slight issue with PEX on Sponge.

Using the latest version of Forge, Sponge and PEX for 1.10.2.

When following this documentation: https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md

I get this:

https://gyazo.com/98e59215aa8d5f39c08e34e38d0321cd

**Comment by zml2008** [comment]
That is like as unspecific as you can get. Which command are you running that gives you that error message?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
