### ISSUE TITLE
PermissionsEx in Singleplayer Dev setup fails to give permissions on first run.

### ISSUE THREAD

**Issue by ryantheleach** [PEXPlugins/PermissionsEx#2540]
From the Tutorial https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md

```
. However, the default configuration gives all permissions to users connecting from the same host as the server (so if you're running a local server you'll automatically be able to run anything from ingame). 
```

This is either not correct resulting in incorrect documentation, or having a context of local-ip:127.0.0.1 is not enough to support a single player lan environment.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
