### ISSUE TITLE
Create group command?

### ISSUE THREAD

**Issue by ryantheleach** [PEXPlugins/PermissionsEx#2541]
Is there any way to create an empty group in pex without adding a permission, without add a parent?

I can already see someone asking "Why do you want to do this?" 

By implicitly creating groups every time one isn't found, you are making the plugin harder for new users.

You mis-spell or mis-remember a group name? group created.

It might be good for advanced users who don't want the tedium, but when you are starting out getting an error message "that group does not yet exist, did you mean Moderator?" instead of "Added parent member to group mod"

Another instance:

`/promote Player811 econ` instead of `/promote user Player811 econ` creates a new subjecttype called Player811

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
