### ISSUE TITLE
Difference in SQL

### ISSUE THREAD

**Issue by LoreCase** [PEXPlugins/PermissionsEx#2543]
In every server i have, the sql for pex is synced. But my kitpvp server doesnt sync it, it knows im a owner but everyone else is still default rank. Why isnt it working as all the other servers?

**Comment by SlimaKCoder** [comment]
@LoreCase 
My sister have a dog named Fred. Fred barks when he is in my house, in my sister house, in my friend house, but doesn't bark when he is in my girlfriend home. Why isn't he barking as in all other houses?

**Comment by Stormbow** [comment]
@SlimaKCoder That has nothing to do with PermissionEx.  Don't hijack other people's threads.

**Comment by SlimaKCoder** [comment]
@Stormbow Main sense of my previous post is that nobody can know what the author have in mind. He needs to provide logs, configs, screenshots, etc. He also didn't prove us that his problem is really related to PEX, so our posts are smilar in this case. I don't want hijack this thread, but when I see topics like this.... I'm starting to think that they are posted by girls and with conviction that anybody will guess what she is writing about.

**Comment by zml2008** [comment]
Are all the servers online mode?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
