### ISSUE TITLE
[PEX 2.x] Server Crashes On Startup

### ISSUE THREAD

**Issue by T1T4N5** [PEXPlugins/PermissionsEx#2544]
Whenever I download ANY version of PermissionsEx, my server crashes.
It's when I install and my server loads, not when I download.

Error Logs:

http://pastebin.com/a7dZWCYM

**Comment by Stormbow** [comment]
It is important to note here that "downloading" PermissionsEx (or anything else, for that matter) has nothing at all to do with "server crashes".  These are two completely separate processes on a computer that do not interact with each other in any way at all.

Now that we have that established, you're going to have to wait for @zml2008 to reply to this post because it has to do with PEX 2.x and Sponge, which I don't handle because I'm not using it myself.

**Comment by zml2008** [comment]
There were some changes in allowed characters in plugin names in Sponge -- this issue has been resolved with a recent change.
