### ISSUE TITLE
Permission for adding player to own group

### ISSUE THREAD

**Issue by realKSMC** [PEXPlugins/PermissionsEx#2554]
How to give an player the permission to add or remove new users to his own group?

I need the permission like `permissionex.parent.add.group.<group>`.

Thx for help!
Greetz,
yololetsplay

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
