### ISSUE TITLE
MySQL - Unknown Column

### ISSUE THREAD

**Issue by LetsPeee** [PEXPlugins/PermissionsEx#2557]
Hey,

Currently this Exception was thrown by the PermissionsEx Plugin and I don't know how to fix it: http://pastebin.com/vqWMDr3v

thx for your help.

**Comment by Stormbow** [comment]
I think this means you have 2 x 'schema-version' lines in your database.  Keep the one which is 'schema-version: 1' and delete the other.

**Comment by LetsPeee** [comment]
Hey Stormbow,

Tanks for yourself really fast reply, I will test it as soon as possible.

**Comment by Stormbow** [comment]
I don't handle SQL issues since I haven't used it in about 4 years and have forgotten pretty much everything, but I'm about 90% sure that's the solution for this particular error.  If you find out I'm right, you can close this ticket.  If I'm wrong, we'll wait for zml to answer.

**Comment by LetsPeee** [comment]
Hey Stormbow, 

first of all - sorry for my absolutely bad writing style yesterday - my smartphone tried to correct me ;)

But now to the exception: 

- I got one "schema-version: 1" line in my config.yml

I could not find any other similar lines...

**Comment by Stormbow** [comment]
Ok, hang tight.  @zml2008 will be along in a while to answer.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
