### ISSUE TITLE
Pex 2.0 Users not staying in groups

### ISSUE THREAD

**Issue by ewm2000** [PEXPlugins/PermissionsEx#2561]
Every time I restart the Server My file is ok but my users dont remain in the groups they are set to. Why is this happening?

**Comment by FabianOphoff** [comment]
Having the same problem over here

28.11 20:51:19 [Server] Server thread/ERROR [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=permissionsex, name=PermissionsEx, version=2.0-SNAPSHOT-b145, source=/mods/PermissionsEx-Sponge.jar}

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
