### ISSUE TITLE
2 prefixes

### ISSUE THREAD

**Issue by rodnicho** [PEXPlugins/PermissionsEx#2563]
Hello, I would like to know how I can put 2 rank prefix as "[A]" and Modetateur "[Moderator]" I try Essential Chat but its not work, I use Chatex but its function has one day and when a player speaks the other player does not see it as the example image:  [Clic here](http://prntscr.com/cxo0zj)

**Comment by Stormbow** [comment]
ChatEx isn't supported by PEX— none of the 'ChatManager' clones and offshoots are —so you'd need a different chat management plugin to handle what you're after.  EssentialsChat and EssentialsXChat won't do it either since they're both setup to use one prefix, as far as I've ever seen.  Beyond that, you're on your own, unfortunately.
