### ISSUE TITLE
Getting PEX to work.

### ISSUE THREAD

**Issue by angryhippo979** [PEXPlugins/PermissionsEx#2568]
I run my server on Java 8 and cauldron within the files as this was the only way to get some mods to work along with plugins. Now every plugin I have installed on my server works except for PEX. 

Why is this because I would like to use PEX over GroupManager but I can't due to this problem.

Thanks

**Comment by zml2008** [comment]
Cauldron servers will not be supported because cauldron is not supported. The currently recommended way of combining mods with plugins is to use Sponge, a new API that replaces bukkit and that is built with mod compatibility in mind (the original cauldron developer is involved in developing Sponge as well).
