### ISSUE TITLE
pex blocks /op command

### ISSUE THREAD

**Issue by xf57212** [PEXPlugins/PermissionsEx#2572]
when trying to op myself from the console i get the following:
[23:30:52] [Server thread/INFO] [io.github.hsyyid.essentialcmds]: [Server] executed command op backcab
[23:30:52] [Server thread/INFO]: PermissionsEx replaces the server op/deop commands. Use PEX commands to manage permissions instead!
[23:30:52] [Server thread/INFO]: Usage: /op user

please unblock the op command. minecraft requires you to be op and in creative mode in order to use command blocks. with the op command blocked, command blocks cannot be used.

**Comment by xf57212** [comment]
https://github.com/PEXPlugins/PermissionsEx/blob/8bb458873a1f621afe785a6d1851ca551511a75d/permissionsex-sponge/src/main/java/ninja/leaping/permissionsex/sponge/PermissionsExPlugin.java#L187-L200

simply removing those lines wil fix it

and proof that you do in fact need to be op to modify a command block just in case you don't believe me: http://minecraft.gamepedia.com/Command_Block#Modification states "In multiplayer, command blocks can only be edited successfully by operators in creative mode"

FYI, the only reason you should ever prevent a command is if a server owner disables it in a configuration file, it causes problems for part of your plugin (e.x. teleporting out of a minigame), or it is a default minecraft command that you want to do something extra with (in this case the command should still do what it was designed to do, but add extra functionality).

**Comment by zml2008** [comment]
No, the requirement of op status to edit a command block should be considered a Sponge issue. Sponge's permission system is designed to entirely replace the op system, so when PEX (or another permissions plugin) is installed that permissions plugin will be checked instead of the ops list. PEX overrides the MC op command to avoid confusion from users who try to op somebody and have it not work in most cases.

Until sponge is fixed, you can explicitly request the MC op command by using the command `/minecraft:op` instead.
