### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Darkfield** [PEXPlugins/PermissionsEx#2574]
Hello,

for(PermissionUser pu : PermissionsEx.getPermissionManager().getUsers()){
                    pu.setPrefix(null, null);
}
Crashes server. jesus what happened to pex? It used to be fast and high quality.

[PermissionsEx] version [1.23.4]
Spigot 1.8.9 with protocolhack.

[16:18:04 INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[16:18:34 WARN]: [PermissionsEx] All backend tasks not completed after 30 seconds, waiting 2 minutes.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
