### ISSUE TITLE
Empty user fields causing huge file size and slowdown.

### ISSUE THREAD

**Issue by Darkfield** [PEXPlugins/PermissionsEx#2578]
Hello, there are plenty fields of like:

  f47c7bd3-89a9-3a9f-88f6-b3f58374e906:
    options:
      name: Mczippon
  dae62c07-092c-32b2-a084-ef211dbc44b8:
    options:
      name: JustDeivy

How to prune them?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
