### ISSUE TITLE
Crash possibly related to tab complete?

### ISSUE THREAD

**Issue by SecretlyJealous** [PEXPlugins/PermissionsEx#2579]
Crash: http://hastebin.com/eqewisiter.md
Not quite sure what caused this crash but it seems to mention permissionsex and tab completion.

**Comment by BlackBeltPanda** [comment]
https://github.com/PaperMC/Paper/issues/461#issuecomment-258022414

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
