### ISSUE TITLE
getKnownSubjects only returns values from cache

### ISSUE THREAD

**Issue by simon816** [PEXPlugins/PermissionsEx#2580]
In PEX 2.0 snapshot build 145, calling `getKnownSubjects` doesn't contain known `SubjectCollection`s, because they haven't been accessed before.
example: call `getKnownSubjects()`, notice that the key `group` (`SUBJECTS_GROUP`) does not exist.
Call `getGroupSubjects()` and then `getKnownSubjects()` again. now it's included.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
