### ISSUE TITLE
Not possible get user groups via command

### ISSUE THREAD

**Issue by Sitmobedaf** [PEXPlugins/PermissionsEx#2581]
If use MySQL:
At use /pex user <nick> PEX give a default group, but i know that this player have another group!

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
