### ISSUE TITLE
Cleaning up [API?]

### ISSUE THREAD

**Issue by Darkfield** [PEXPlugins/PermissionsEx#2582]
Hello, how do I cleanup PEX file? There plenty of lines with empty user fields just this:

  a02d199e-2efe-3420-b354-3b07b3392401:
    options:
      name: Teddy151

It's not needed. Can I do that with API?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
