### ISSUE TITLE
Issue within plugin interaction

### ISSUE THREAD

**Issue by EternalUF** [PEXPlugins/PermissionsEx#2584]
Hello, I am having issues with my server currently and there is a possibility the issue might be between the interaction of Quicksell and PermissionsEx. When two or more users are on the server and one interacts with the CommandNPC to trigger Quicksell the server crashes from CPU load. Could someone help me pinpoint if this is a PermissionEx problem or somewhere else?

http://pastebin.com/QNwgp678

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
