### ISSUE TITLE
MYSQL Bug

### ISSUE THREAD

**Issue by LartyHD** [PEXPlugins/PermissionsEx#2586]
Here:
http://minilebenmc.de/Bugs/pex/1.png
http://minilebenmc.de/Bugs/pex/2.png

**Comment by RubeVi** [comment]
Try deleting all the tables related to PEX (permissions, permissions_entity and permissions_inheritance). Let the plugin remake the tables

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
