### ISSUE TITLE
PermissionEx Sponge crash

### ISSUE THREAD

**Issue by FabianOphoff** [PEXPlugins/PermissionsEx#2589]
Hi reader,

I've been using PermissionEx for minecraft 1.10.2, all setup and working, players join and can use commands, prefix works, but after a restart of the server it breaks down, no permissions are granted to default players and prefixes disappear!

Need help soon

Thanks!

**Comment by zml2008** [comment]
"it breaks down" explain

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
