### ISSUE TITLE
CPU Load Crashing

### ISSUE THREAD

**Issue by EternalUF** [PEXPlugins/PermissionsEx#2591]
Hello,  When two or more users are on the server and one interacts with the CommandNPC to trigger Quicksell the server crashes from CPU load. I am sure Pex is the issue, since I have removed Pex and the issue did not occur.

http://pastebin.com/QNwgp678

**Comment by zml2008** [comment]
PEX version?

**Comment by EternalUF** [comment]
I'm currently running Pex 1.23.4, but the server was previously running on 1.23.3.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
