### ISSUE TITLE
Bukkit website has deleted the forums entirely?

### ISSUE THREAD

**Issue by Stormbow** [PEXPlugins/PermissionsEx#2596]
All of the Guides and Troubleshooting posts that I had created on the Bukkit website appear to be gone completely since there is no access to the forums that were there, as far as I can tell.

Are you seeing this also?

**Comment by Stormbow** [comment]
Hey there,


The forums aren’t deleted; all of the data still exists on the old database. Unfortunately there wasn’t time to complete that feature on the new sites before the end of our timetable to decommission the old sites, so they will temporarily be unavailable. The project forums will make a return, however, so please bear with us during the transition.


We’re very sorry for the inconvenience!


Take care,
Torhal

**Comment by zml2008** [comment]
ok, good to know -- I've also pinged folks in #bukkitdev

gotta love curse messing up things again

**Comment by AncientTom** [comment]
Thank you very much for continuing the maintenance and updates on PEX which I have been using since 2012. I am trying to set up a new server with a late build of spigot 1.11.2 and have a problem of PEX not adding the default group to a new player's entry in the permissions.yml file when PEX creates their record in it.

I have posted this issue to the Spigot server plugin forum several days ago and not even a comment was added there. The Spigot forums are almost useless because there are so many posting in the same category and thread updates shove others back up to the top of the list, within a day or two my issue is shoved several pages down in the list of threads.

My question is since PEX forum on bukkit still is not back up, where is the best place to post PEX issues?

**Comment by Stormbow** [comment]
> My question is since PEX forum on bukkit still is not back up, where is the best place to post PEX issues?

This is the official ticket location for PEX, so here is fine.  (But you should have started your own ticket, instead of adding to an old one.)

> PEX not adding the default group to a new player's entry in the permissions.yml file when PEX creates their record in it.

This is actually working as intended in PEX 1.x because PEX knows that any user not showing a group in the `users:` section belongs to whichever group is `default: true`.  This is so server owners who are using PEX don't have to manually move hundreds or thousands of users from and old `default: true` group into whatever new `default: true` group the server changes to.

**Comment by AncientTom** [comment]
My server is not working this way. New players are not getting any permissions at all. I will start a new thread here as"PEX not adding new players to the default group.". Thanks.

**Comment by zml2008** [comment]
Without a maintained plugin, we have no need of a forum, so this issue is no longer a problem.
