### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by bobbyspelt** [PEXPlugins/PermissionsEx#2599]
i had a quistion 
i have downloaded your plugin pex 
fore my server
i extely maked the program first in the permmission file 
but i wanted to conect more server's that was later
but it isent copieng the stuf in side of the permission.yml to the mysql 
kan you make the plugin so it would do that or tell me how to dot that
plz
 
thanks
 
Bobby

**Comment by frizzbee30** [comment]
Did the set up create the table ok?  Did you run 'pex import file'?  You can run pex backend sql on the fly to see if it uses the table.

The info is a bit spread out, but it is such a feature rich plugin I think the documentation just naturally fragmented a bit :)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
