### ISSUE TITLE
Pex Prefix Problem

### ISSUE THREAD

**Issue by GoCardsPlays** [PEXPlugins/PermissionsEx#2630]
Whenever I try to give a group a prefix it won't work. I know i'm using the correct commands and putting the right stuff in the folder to do so (I think). Any help. The prefixes won't show up

**Comment by Stormbow** [comment]
Do you have a chat management plugin like EssentialsXChat?  (Requires Spigot server, EssentialsX, and Vault.)

PEX just gives you a place to store the information; PEX doesn't display them in-game.

**Comment by XantiFuchs** [comment]
Hey i got the same problem and i'm using EssentialsXChat 2.0.1

They still won't give me a prefix

**Comment by Stormbow** [comment]
@XantiFuchs Be sure you've actually set up the EssentialsXChat config.yml file correctly and you have the Vault.jar installed in your plugins folder too.  I can't link you to a guide on EssentialsXChat configuration anymore because the Bukkit website changed without warning and they deleted the forums that I had all the PEX guides posted in.
