### ISSUE TITLE
Pex just doesnt work

### ISSUE THREAD

**Issue by PrimePrismatic** [PEXPlugins/PermissionsEx#2632]
I have followed many tutorials and ive copied it. Pex just doesnt load my permissions or prefixes. I need help. Im using the lastest version of pex for 1.11 It just doesnt work. I have everything correct it just doesnt read it. i have essentialsX and essentialsXchat but it doesnt work.
[permissions.zip](https://github.com/PEXPlugins/PermissionsEx/files/679258/permissions.zip)

**Comment by Stormbow** [comment]
* You don't actually have a permissions.yml file.  Follow [this example](http://pastebin.com/8ZSHxauG).

* Be sure you have [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) installed.  EssentialsXChat requires it.

**Comment by PrimePrismatic** [comment]
i cant install vault it doesnt let me its not a high enough version for my server

**Comment by PrimePrismatic** [comment]
I have fixed all the backend and permissions problems. Now just my prefixs wont show up. I have installed vault and essentialsxchat and it wont work

**Comment by Stormbow** [comment]
Did you look at the example file I linked to you?  There is _much_, _much_ more info in that file than in the permissions file you showed me.

PEX is disabled when there are problems in the permissions.yml file.  See my previous post about how to fix those.  The "config.yml" and "permissions.yml" files are both considered "config" files.  Since your permissions.yml file was missing the `groups:` section and `schema-version: 1` line entirely, the file is invalid and PEX is disabled.

And it's important to know that Vault doesn't have version update requirements.  The version found online will work with all server versions.

Keep in mind, also, that if your server.properties file has `online-mode=false' in it, PEX will never function properly because PEX does not support hacked/illegal clients or servers (which require that setting).

**Comment by Stormbow** [comment]
Looks like this issue is closed.
