### ISSUE TITLE
Ranks starting with the same letter

### ISSUE THREAD

**Issue by BushRaptor12** [PEXPlugins/PermissionsEx#2636]
In my prison server, I have an "Owner" rank and an "O" rank. The plugin deleted the "O" rank once I made the "Owner" rank. When I tried making "O" again, it said rank "O" already exists. Help!

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
