### ISSUE TITLE
Pex 2 update?

### ISSUE THREAD

**Issue by EmanYm** [PEXPlugins/PermissionsEx#2638]
So it's been close to two year since #1945 was posted (opened on Mar 18, 2015, closed on Apr 16, 2015).  I was wondering if any progress has been made on development or documentation for those of us that are using it.

The only source I have to go on is the ticket 1949 and [this post](https://forums.spongepowered.org/t/guide-pex-quick-command-reference/8738) by MoeBoy76 on spongepowered.org from back in July 2015.

I am still sort of stumbling around in the dark with most of what I'm doing when working with Pex2.  I figured there would have been some kind of update by now.

**Comment by Stormbow** [comment]
There is a working version that many people are using these days.  I haven't gotten into it myself.  @zml2008 can give you more details though.

**Comment by EmanYm** [comment]
There's not really much more detail I can give.  I was just asking if any progress has been made on documentation of PEX 2 in almost two years since the posting of issue 1945.

**Comment by zml2008** [comment]
There's the doc/ folder in the repository, with some basic documentation. The documentation has been expanded somewhat in the `feature/segments` branch to cover the (currently incomplete) changes made in that branch.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
