### ISSUE TITLE
Permissions are not changing until reconnect

### ISSUE THREAD

**Issue by MrOnlineCoder** [PEXPlugins/PermissionsEx#2642]
Hello. I noticed that if I change user's group from Admin to Member for example, he still can use /ban or /kick until reconnect or /pex reload. Member doesn't have permissions for kick and ban commands.
Why does this happen?

Server: git-Bukkit-1.7.2-R0.3.2
PEX version: 1.21.3

Thanks,
MrOnlineCoder

**Comment by Stormbow** [comment]
More than likely it's a server host issue.  Many server hosts load the permissions.yml file (and other config files) into memory and runs from memory to operate the server.  Any changes made to the config files (including the permissions.yml config file) are made to the file, but not to the information that's stored in memory.  So while the permissions.yml file and PEX think the the user is a "Member", they're still in memory as an "Admin".  The only solution I've found to this type of "bad server host" problem is to stop the server entirely and start it again.  (Sometimes the 'restart' server commands just reads from what's in memory too, so the server has to be stopped completely.  And the `/reload` command has been broken since the dawn of time, so it should always be avoided— it will reload all of the server plugins, but after 2-3 uses of that command, the server ends up crashing.  For that reason, PEX has `/pex reload`, but if the server host reads from memory, the pex reload command is useless too.)

**Comment by MrOnlineCoder** [comment]
Thanks for reply. I made a plugin that implements /rank command with some additions that executes pex user <user> group set.  I tried to execute pex reload command after that, but then no changes happen. I will try to change server software

**Comment by Stormbow** [comment]
If this is a programming issue between your plugin and PEX, we'll need @zml2008 to fill in the details since I don't do any of the programming for PEX.

**Comment by frizzbee30** [comment]
we have found the same issue after moving over from grpmanager, not looked if it persist's into timed permissions or not, hopefully not.

**Comment by Stormbow** [comment]
Does this problem persist when using PEX 1.23.4?

**Comment by Stormbow** [comment]
Problem must be solved.  You're welcome. :)
