### ISSUE TITLE
Pex Groups Merging!!!!

### ISSUE THREAD

**Issue by iHildy** [PEXPlugins/PermissionsEx#2649]
dummy commands dont work heres perm.yml: How i like (before restart): http://pastebin.com/MMkQEGSa How i dont like(after restart): http://pastebin.com/FsnMiCqF

Plz help me and figure out why its merging!

**Comment by Stormbow** [comment]
Does your server.properties file have `online-mode=false`?

Which version of PEX are you using?

Are there any errors being shown in your server console when you start the server?  (Copy the server log from the moment you start the server through where you see a message similar to "Done!" and the server has finished loading.  Pastebin that log for me to look at please.)

**Comment by iHildy** [comment]
I changed it to false

im using: PermissionsEx-1.23.4

pastbin: http://pastebin.com/QRmRCKGh

**Comment by Stormbow** [comment]
It should be set to true.  Some people change it to false to run hacked servers and let people with pirated/illegal copies of Minecraft play on the server.

And PEX doesn't support that stuff.  >.>

It looks like a couple of your plugins are not updated for Minecraft 1.11.2, which you're running.

Change the server.properties file back to true and post another server log for me please.

**Comment by iHildy** [comment]
Set it to true.

Heres pastebin: http://pastebin.com/S74ExY2b

**Comment by Stormbow** [comment]
> 2017-01-15 18:06:40 | [RAW] *** Error, this build is outdated ***

Your Spigot file is outdated.  You will need to download a new version, _after_ you delete the one you currently have installed.

> 2017-01-15 18:06:59 | [ERROR] Could not load 'plugins/iControlU_v1.9.8 (1).jar' in folder 'plugins'

This type of error usually means you have 2 copies of the plugin's .jar file installed.  Make sure you only have 1 copy of each plugin .jar file installed on the server.

>2017-01-15 18:06:59 | [ERROR] Could not load 'plugins/ServerEssentials.jar' in folder 'plugins'

Your ServerEssentials plugin is outdated.

>2017-01-15 18:07:00 | [WARN] [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported 

>2017-01-15 18:07:00 | [WARN] **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!

The server is still being run in offline mode, which PEX does not support.

>2017-01-15 18:07:02 | [ERROR] Error occurred while enabling MOTDColor v0.5 (Is it up to date?)

> 2017-01-15 18:07:03 | [ERROR] Error occurred while enabling BigBrother v1.11.0-SNAPSHOT (Is it up to date?)

>2017-01-15 18:07:06 | [ERROR] Error occurred while enabling ChatProtectionPlus v1.0.1 (Is it up to date?)

>2017-01-15 18:07:06 | [ERROR] Error occurred while enabling EssentialsChat v2.13.1 (Is it up to date?)

Plugins are outdated.

"EssentialsChat" can not be used on any server beyond Minecraft 1.8 because the author abandoned the project.

>2017-01-15 18:07:06 | [ERROR] Permission node 'schema-version' in permissions.yml is invalid

Error found in your permissions.yml file.  It will not matter if your file is perfect and that you fix all of the errors I mention here if you keep trying to run the server in offline mode.  (`online-mode=false`)  PEX will never function correctly, no matter what you do, with that setting.

**Comment by iHildy** [comment]
What?

**Comment by Stormbow** [comment]
I have edited my previous comment to include more details.

**Comment by iHildy** [comment]
What is the error?

**Comment by Stormbow** [comment]
All of the the stuff I quoted above.

Most importantly:

1. The server is still running in offline mode.  If you don't run the server with `online-mode=true', PEX will never function correctly and you can ignore #2 below.

2. There is a critical error in your permissions.yml file.  The link in my previous comment (with all the quoted errors and how you fix them) will show you how your file is wrong.

**Comment by iHildy** [comment]
I set it to true for real this time. pastebin: http://pastebin.com/aTzhRsRa

**Comment by Stormbow** [comment]
Did you read my other post, with all the other errors you need to fix?

**Comment by iHildy** [comment]
I dont have 2 icu .jars

EssentialsChat works just fine

I have the same version of spigot on my private server and every thing works just fine (it has less ranks/groups) <----- that might be the problem i think PEX has a limit of groups/ranks

**Comment by Stormbow** [comment]
What number of groups are you trying to use?

I have seen people with Prison Pokemon servers that have A to Z as group names, and then another 3 dozen Pokemon group names.

**Comment by Stormbow** [comment]
The longest functional PEX file I have worked on was over 18,000 lines of text.

**Comment by Stormbow** [comment]
So, as far as I can tell, PEX doesn't have a "group/ranks limit" like you're suggesting.

**Comment by iHildy** [comment]
Here is the permisions.yml http://pastebin.com/MMkQEGSa

**Comment by Stormbow** [comment]
Your file is many hundreds of lines longer than it needs to be because you're not using inheritances.  (And, on a side note, PEX requires an inheritance section in every group as of Minecraft 1.9.  If you don't have those inheritance sections, PEX will also not function correctly.)

Permissions like `essentials.afk.auto` and `essentials.afk` don't need to be given to every group.

If you look at [this example](http://pastebin.com/8ZSHxauG) and replace `permission.node.one` with `essentials.afk` (a node you want everyone to have, for example), the way that example has inheritances set up, everyone in the entire file gets that permission node.  Admins inherit all the nodes that Mods have, Mods inherit everything Members have, and Members inherit everything that Guests have.  So, Admins also have everything that Guests have, without having to list all of those unnecessary lines of text.

**Comment by Stormbow** [comment]
Also, since your server is running in offline mode, the `users:` section is not populating with your UUID, and PEX is never going to function correctly.

**Comment by iHildy** [comment]
Ok I will set up inheritance it might be a while

**Comment by Stormbow** [comment]
Ok.  Once you get those done, test the server again.  If you've really changed it to `online-mode=true`, PEX should load and your UUID should appear in the file.  If not, PEX will continue to malfunction.

**Comment by Stormbow** [comment]
[Log 1[(http://pastebin.com/S74ExY2b) - Server is in offline mode.
[Log 2](http://pastebin.com/aTzhRsRa) - Server is in offline mode.

Notice how all the timestamps between these 2 logs are identical.

Notice how you can hit CTRL+F and find "offline mode" in both of those files, with the exact same timestamp for both of them, and both times it's on line 66.

Any time someone requests a console log, that means you need to stop the server completely, start the server, and copy everything printed on the console— from the moment the server starts, all the way down to where the server stops printing text on the screen and/or you see a message similar to "Done!".

**Comment by iHildy** [comment]
ok

Here is new log (hope it works) : http://pastebin.com/S9e2G6gA

**Comment by iHildy** [comment]
After restart: http://pastebin.com/DQf2Wd0E

**Comment by Stormbow** [comment]
Well... We got PEX working.  Sort of.  :-/

I have never seen a server cut apart the permissions.yml file like that.

Are you sure you're **stopping** the server completely and not just **restarting** the server?  Some server hosts are absolutely terrible because they load the file into memory and only read from that.  The only way to get the fresh permissions.yml file contents onto those servers is the stop the server completely.  Then to start it again.  Stop and start is a completely different functional process than restarting for these bad server hosts.

**Comment by iHildy** [comment]
I dont do restart I edit txt stop server start server (is that good?)

**Comment by Stormbow** [comment]
You're using text commands to stop it and start it?  That would be good then.

I can't imagine any other reason that the permissions.yml file would go from [this](http://pastebin.com/MMkQEGSa) (about 760 lines) down to [this](http://pastebin.com/MMkQEGSa) (about 360 lines).

Give me some time to look at these files more closely...

**Comment by Stormbow** [comment]
FORMATTING!

Some of your groups are indented too far.

Give me a couple more minutes...

**Comment by iHildy** [comment]
No i edit the files the log in do /stop go to console and start it

ok reply when ready

**Comment by iHildy** [comment]
Then*

**Comment by Stormbow** [comment]
I also found 10 times that you used the tab key in your file.  YAML (.yml) files can't have any tab key usages in them, unless the tab key is only inserting spaces.

Try [this paste](http://pastebin.com/raGFxJPh).

Stop the server.  Replace your permissions.yml file with the contents of the above paste.  Start the server.

Then stop the server and open the permissions.yml file in Notepad to see if it's been butchered again.

**Comment by Stormbow** [comment]
I'm taking off for dinner.  I'll check back in here about 60 minutes from now.

**Comment by iHildy** [comment]
OK

**Comment by iHildy** [comment]
Havent tested it full seems to work.

**Comment by Stormbow** [comment]
The file's not chopped up?  Excellent!

Feel free to post again here if and other wonky  stuff happens.  :)
