### ISSUE TITLE
New thread. Pex on MySQL

### ISSUE THREAD

**Issue by lastyoda** [PEXPlugins/PermissionsEx#2653]
Hello,

I made a topic earlier but that was closed because I don't have enough patience.
So, I want to ask you guys for a favour again.
I want to use my pex serverwide (4 servers) so I want to connect it to a proxy. But when I change the backend in the config.yml to sql, the plugin crashes. I didn't do anything else then just change it and restart the server.
I hope you will still help me. Thanks

**Comment by lastyoda** [comment]
I use Minecraftpanel for the server hosting, I don't know if that has anything to do with the problem.
Sorry for my behaviour yesterday, I was just annoyed by the crashes all the time haha

**Comment by lastyoda** [comment]
Can someone help me?

**Comment by Stormbow** [comment]
For an SQL issue, you'll need to wait for @zml2008 to respond.  I'm not familiar enough with SQL myself.

**Comment by Stormbow** [comment]
Be sure to post your PEX version and any other potentially useful information you have.

**Comment by lastyoda** [comment]
Pex version: 1.23.4
Is it useful to know my other plugins?

**Comment by zml2008** [comment]
"the plugin crashes" does not give enough information for us to help you. You'd have to paste the stacktrace you get.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
