### ISSUE TITLE
Pex Exporting Problem

### ISSUE THREAD

**Issue by SwiftSwamp** [PEXPlugins/PermissionsEx#2662]
Hey,

So I've had this issue for a while and it's crucial for me to have this done.
I've been trying to export my PEX Database from MySQL to Flatfile for a while and when I do it it seems to always cap at about 7,000 lines in the flat file. 

Steps I'm doing:
* Will startup with sql set as the backend
* Will type into console /pex backend file
* Will type /pex import sql

Then I'll check the flatfile and it'll always be about 160,000 bytes in size, however when I check it there's a LOT of ranks missing and it never exports the default rank for some reason.  There's about 20,000 players with permissions / ranks, however in the export there's only about exactly 4,000 each time. Thoughts? 

I'm using the latest Spigot 1.8.8 build with PEX v1.23.4

**Comment by rayyates** [comment]
Can you post the MySQL statement you are using and I'll see if I can find the problem.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
