### ISSUE TITLE
Sponge/Bungee Fault - defaults have all perms

### ISSUE THREAD

**Issue by SirRicharalar** [PEXPlugins/PermissionsEx#2663]
So I started Bungee today and I was told to make my server go offline and let Bungee do all the connecting of servers. Im not sure if this offline mode causes pex to not work properly, ranks are still there, but you will have access to all commands regardless if you have a rank or not.

In offline mode, players work of username and not UUID.

**Comment by Stormbow** [comment]
PEX 1.x will not function correctly with `online-mode=false`.

Bungeecord can be run with the server in online mode.  I don't know how it's done since I don't run multiple connected servers, but it can be done.

Maybe @zml2008 can tell you more.

**Comment by zml2008** [comment]
When Bungee and Sponge are set up properly, Bungee passes the player UUIDs through to the server that has been set to offline mode so that the server is effectively in online mode. The process to set this up is a bit more complicated in Sponge -- I believe you need either a special plugin in Bungee or to use Waterfall proxy (a fork of bungee), but the Sponge docs may have more detailed instructions.
