### ISSUE TITLE
Pex Mysql doesnt work 

### ISSUE THREAD

**Issue by zorvi** [PEXPlugins/PermissionsEx#2666]
Hi il tried to setup pex for bungee mode but Doesnt work i hope you can help me.
Error's pastebin: http://pastebin.com/t7zbFp0Y

**Comment by Stormbow** [comment]
Are you using Bungeecord?

If yes, you will need to talk to that plugin's authors to get instructions on how to set up your servers when you have your server.properties file set to `online-mode=false` because PEX _requires_ that setting to be set to true.  PEX will not function correctly when that setting is false, and many bungeecord servers _can_ have that set to true— I just don't know how to do it since I have never used Bungeecord.

If no, you will need to change the server.properties file to `online-mode=true` in order for PEX to function correctly.

We (the PEX plugin, the author/programmer zml2008, and myself) do not support servers running in offline mode.  We know that offline mode is required for hacked/illegal servers and clients, and do not support those either.

**Comment by zorvi** [comment]
Yes il use Bungee

**Comment by Stormbow** [comment]
OK.  You will need to go talk to them about how to set up your server correctly then.

**Comment by zorvi** [comment]
Ok need il ask Zml?

**Comment by Stormbow** [comment]
Ask for Bungeecord help [over here](https://github.com/SpigotMC/BungeeCord/issues).
