### ISSUE TITLE
Pex 2.0 Options should be case insensitive

### ISSUE THREAD

**Issue by Katrix-** [PEXPlugins/PermissionsEx#2667]
In Sponge options are supposed to be case insensitive, but from what I can see, the case does matter when using PEX.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
