### ISSUE TITLE
My default permissions that I have set for some reason won't work :(

### ISSUE THREAD

**Issue by SakuchanVA** [PEXPlugins/PermissionsEx#2676]
groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
    - essentials.balance
    - essentials.eco
    - essentials.eco.loan
    - essentials.pay
    - essentials.sell
    - essentials.setworth
    - essentials.worth
    - essentials.afk
    - essentials.afk.auto
    - essentials.help
    - essentials.helpop
    - essentials.helpop.receive
    - essentials.ignore
    - essentials.info
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.nick
    - essentails.msg
    - essentials.recipe
    - essentials.rules
    - essentials.suicide
    - essentials.spawn
    - essentials.back
    - essentials.back.ondeath
    - essentials.delhome
    - essentials.home
    - essentials.sethome
    - essentials.sethome.multiple
    - essentials.sethome.multiple.[set name]
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.warp
    - essentials.warp.list
    - essentials.warps.*
    - essentials.warps.[warpname]
    - essentials.signs.use.gamemode
schema-version: 1

That is what is in my permissions.yml in PermissionsEX but ... They work for like a bit, then if I reset my server they no longer work... Help..? >~<

**Comment by Stormbow** [comment]
Which version of Minecraft are you running?

Which version of PermissionsEx are you running?

Are there any errors in the console log?  (If yes, copy the log to [Pastebin](http://pastebin.com) and leave the link in this thread.)

Is the server running in online mode?  (The server.properties file must have `online-mode=true`.)

Does your permissions.yml file follow [this example](http://pastebin.com/8ZSHxauG)?  (The indentation must all be correct; option settings must all be in the options section; every group must have an inheritance; see line 19 if a group isn't inheriting permissions from another group; the `schema-version: 1` line must be above the `users:` section; you must not use the tab key anywhere in your file.)

Since your file parses cleanly— what _exactly_ is not working the way you expected it to work?

**Comment by SakuchanVA** [comment]
PermissionsEX 1.23.4 and I made the server for 1.11.2
and no there has not been any errors, maybe a few warnings but thats it.
online mode is set at true.
I have never used the tab key, only spaces and enter. When I first put permissionsex the schema-version: 1 was right where it was to begin with. I also watched the tutorial on server.pro on how to set permissionsex up and I made sure to follow step by step so I am just slightly frustrated a bit and upset that it keeps messing up for some reason.

**Comment by Stormbow** [comment]
Ahhhhhh...  "Server.pro"... I just spent 6 hours getting a server to work for someone yesterday because that server host is truly. seriously. terrible.  And I don't say that lightly or often about server hosts.

(One thing I forgot to mention in my previous post is that 2 of your permission nodes— `essentials.sethome.multiple.[set name]` and `essentials.warps.[warpname]` need actual names instead of those bracketed bits, [set name] and [warpname].)

What _exactly_ is not working as you expect it to work?

**Comment by SakuchanVA** [comment]
@Stormbow Basic permissions... They keep messing up and they somehow disable everything which doesnt allow nonop to do anything. :|

**Comment by SakuchanVA** [comment]
the server permissions.yml ? or the permissionsex permissions.yml? because what I sent was permissionsex permissions.yml :| and my server one is empty

**Comment by Stormbow** [comment]
The permissions.yml file in your servers root directory should be completely empty.  (I don't know of any reason that file would ever be used.)

I'd like to see the PEX file, inside the PermissionsEx folder.

**Comment by SakuchanVA** [comment]
@Stormbow I have no pex file ....

**Comment by Stormbow** [comment]
Can you show me a screenshot of the server files?

**Comment by SakuchanVA** [comment]
Yeah 
![idk](https://cloud.githubusercontent.com/assets/24511656/23109115/e7e72e58-f6e3-11e6-8e8a-31ca7bbc491a.PNG)

**Comment by SakuchanVA** [comment]
![shdfuh](https://cloud.githubusercontent.com/assets/24511656/23109129/03b39342-f6e4-11e6-98ea-5467d50efeb7.PNG)

**Comment by Stormbow** [comment]
I see, you were confused.

The "PEX file" is the "permissions.yml file" that you showed me in the first screenshot.  Copy the contents of that file to [Pastebin](http://pastebin.com) for me to check for problems.

**Comment by Stormbow** [comment]
Any permissions.yml file on the server other than that one should be completely empty.

**Comment by Stormbow** [comment]
No response in more than 7 days. Issue must be resolved.
