### ISSUE TITLE
Having trouble with PEX priorities.

### ISSUE THREAD

**Issue by Corcustos** [PEXPlugins/PermissionsEx#2680]
I've looked over the help wiki for PEX, many outdated guides, and I've not been able to figure this out. The goal is to have three ladders: user, donator, and staff. I want the staff ladder to have the highest priority, and user to have the lowest. If someone in the user ladder becomes a staff member, I want the staff tag to have priority, or to be displayed alongside the user ladder prefixes. Users have grey chat, donators have white chat, and staff have colored chat. I want donators/staff to still be able to rank up through the user ladder, but still have the colored chat from the staff ranks, or white chat if they're a donator. I'm using /pex user (user) group add (group), and the remove command as well. If I remove a user rank and add it back, or give them a new rank, it overrides the staff and donator ranks turning them into secondary ranks. I want to prevent this.

Here is the config I'm using: http://pastebin.com/qTK99sV0

This has become a large barrier for me in creating my server the way I want. I know it's possible, I just don't know how. I just can't figure it out. If anyone can help me to do this, or provide an alternative way, that would be much appreciated. If any extra info is needed, just ask.

I'm using the latest 1.8 builds for PEX, Essentials, and Spigot.

**Comment by Stormbow** [comment]
> I want the staff ladder to have the highest priority, and user to have the lowest.

> I'm using /pex user (user) group add (group), and the remove command as well. If I remove a user rank and add it back, or give them a new rank, it overrides the staff and donator ranks turning them into secondary ranks.

The first quote is accomplished by— and the second quote is prevented by —the use of _weight values_.  You can see them in action [right here](http://pastebin.com/8ZSHxauG).

> I want the staff tag to have priority, or to be displayed alongside the user ladder prefixes.

I'm not entirely sure what you mean by this, but if you mean you want chat to look like this:

[Staff] [User] Stormbow: words that I typed

then you'll have to look for another plugin that can display more than 1 `{GROUP}` variable, and I don't know if such a thing actually exists.

> Users have grey chat, donators have white chat, and staff have colored chat. 

Here are links so you can read more about [chat formatting](http://minecraft.gamepedia.com/Formatting_codes) and [color codes](http://minecraft.gamepedia.com/Formatting_codes#Color_codes).

At the end of each group's `prefix:` or `suffix:`, you will add one of the above color codes.  For example, if you want the group named "User1" to have the prefix of "[User1]" and chat in gray, you would have the following as their prefix:

`prefix: '[User1] &7'

(Pay close attention to the extra space after the closing bracket.  It's an apostrophe, [User1], a space, &7, and another apostrophe.  This separates the title from the username on most servers, so it's not `[User1]Stormbow: words`, it's `[User1] Stormbow: words`, which looks much cleaner.)

> I want donators/staff to still be able to rank up through the user ladder, but still have the colored chat from the staff ranks, or white chat if they're a donator.

As I have your server setup [in this example file that I made for you](http://pastebin.com/NPKNT8vA), every new player on the server will be a User1.  They may be promoted to User10 (`/pex promote Stormbow user` a total of 9 times), and then they will have to be manually moved into a staff rank with `/pex user Stormbow group set Staff1`.  From there, they may be promoted to Staff5 (`/pex promote Stormbow staff` a total of 4 times).

Keep in mind that if a user is in both a "user" ladder group and the "staff" ladder group, you're being redundant.  All of the the higher ranks gain the permissions of all of the lower ranks through inheritance.  (A user who is in "Staff5" gains all of the staff permissions from inheriting down the "staff" ladder chain— Staff5 inherits from Staff4, which inherits from Staff3, which inherits from Staff2, which inherits from Staff1.  And because "Staff1" inherits from "User10— which inherits from User9, which inherits from User 8, etc. —all of the Staff ladder groups also have all the User ladder permissions..)

I also added an "Owner" group because no server should be without one.

**Comment by Corcustos** [comment]
Staff5 is essentially the owner rank. I know how to do everything else, the weight variable fixes everything that I was trying to get. I'll test it out later and let you know if it works. I wasn't aware that the weight variable even existed. As for the color formatting, I didn't say I didn't know how to do that. I said they have those chats, and I wanted the ranks to keep higher priority chat colors. Honestly, all you had to do was tell me that there was a weight variable. You went above and beyond, so thank you for that. That was all I needed.

(Also, when I try to use the /pex promote command it says they aren't high enough rank to be promoted in that ladder or something of the sort.)

**Comment by Stormbow** [comment]
You're welcome. :)

If you get a chance, post again in this thread to let me know how the test went.

As for the promote command, I'd need specific examples of the permissions.yml file being used, the group of the person using the command, the group that the target of the command is in, and the exact command being typed to properly address that issue.

**Comment by Corcustos** [comment]
It works perfectly, thank you. I can't believe I've missed the weight system this entire time. As for the promotion commands, I don't really need it to work as I can still add and remove ranks while the weight takes care of the rest of my problems.

**Comment by Stormbow** [comment]
Excellent.  Feel free to come on back and post again if you run into any other PEX problems or questions.  :)
