### ISSUE TITLE
PEX error! Please help :/

### ISSUE THREAD

**Issue by jsayers603** [PEXPlugins/PermissionsEx#2682]
I'm new to dealing with plugin errors, and I'm not sure what info people need to try to figure out my error, so I put some stuff on this link... http://pastebin.com/Gxz2ZSqi

Thanks SO MUCH to whoever can figure this out for me :)

- Jessica

**Comment by Stormbow** [comment]
Hi Jessica,

I'm not 100% familiar with that error, but I think it looks like you may be using an outdated version of Spigot (line 66 and 65 of your error log) and there may be an error in the config.yml file (lines 37 through 11).  (Spigot is kinda weird like that— the console log is printed upside down compared to other server wrappers, so the stuff listed in the log is actually happening from the bottom of the log upwards.)

When I look at your permissions.yml file, I see only one error: `essentials,home` has a comma in it instead of a period.  (That's on line 106 in your link.)

Change out that comma for a period and give the server another test before anything else.  If there are still errors in the log, then you can try updating Spigot.

Let me know how it goes. :)

**Comment by jsayers603** [comment]
@Stormbow thanks for all the help. I'm not sure if you were right but I did fix this error. I appreciate you for trying to help :) Thanks
