### ISSUE TITLE
Guys can you please tell me what is wrong with this. The plugin is not working

### ISSUE THREAD

**Issue by fmg02** [PEXPlugins/PermissionsEx#2690]
**] Edit by Stormbow: Moved wall of text / permissions.yml file to [Pastebin](http://pastebin.com/SwKTF0tD). [**

**Comment by Stormbow** [comment]
First and foremost, the server must be running with the server.properties file set to `online-mode=true` unless you're running a Bungeecord plugin.  (If you are using Bungeecord, you need to read their documentation to learn how to set up the server correctly.)

Next, see [this example]9http://pastebin.com/8ZSHxauG) for a fairly complete file.

• Every group _must_ have an inheritance section.  See line 19 of the example above to put an inheritance in your "member" group.

Also, since you're using inheritances, you do not need to give the same permission nodes to every single group.  Putting nodes like `essentials.tell` and `essentials.home` (along with many others) in every group just makes your file excessively long.

• Negated permissions are `- -permission.node` and not `- - permission.node` as you have it in your file.  (No space between the 2nd hyphen and the node name.)  Also, negated permissions _must_ be listed at the top of the permissions list for any group that uses negations.  (i.e., Your "Head_Staff" group needs the negation above the global wildcard.)

• Remove the multiworld settings you mistakenly programmed into the "Head_Staff" group.

♦ Avoid using special characters in the group names because some plugins (like Essentials) can have problems recognizing those groups.  (e.g., T_Admin should be replaced with TAdmin and Head_Admin should be HeadAdmin; you can keep the prefixes the way you want them.)  Fix all of the group names to be sure they can be found by other plugins.  (PEX can handle these just fine, but other plugins won't be able to find them, so it's best to program the permissions.yml file with those other plugin limitations in mind.)

♦ Keep in mind that the `build: false` option setting (in the "BADRAP" group) won't do anything unless you're using the EssentialsXAntibuild.jar file on the server.

After addressing all of the above issues, test the server and if there are still problems, post again in this thread with _very specific details_ about what is not working the way you had expected it to work.  If a command is not working, tell me the exact command you are typing, the exact error message(s) you're seeing in the console, etc.

Use [Pastebin](http://pastebin.com) to share information so the formatting is not corrupted as you saw in your first post here.

**Comment by Stormbow** [comment]
There were no "fatal" errors in your file aside from the missing inheritance section(s).

**Comment by Stormbow** [comment]
I'm assuming this issue is resolved since OP hasn't responded in more than a week.
