### ISSUE TITLE
Pex disables every time I reload/restart server

### ISSUE THREAD

**Issue by AnonymousHitman** [PEXPlugins/PermissionsEx#2691]
Whenever I go to reload my server or restart it, the plugin disabled. All the files stay in the plugins folder but it just stops working. Any help would be great, thanks.

**Comment by Stormbow** [comment]
Are you referring to the `/reload` or `/restart` command?  If yes, avoid using those commands because they've been known to crash servers for at least the past 7 years.  They are default commands that come with Minecraft, but they've never been reliable to use.

If you have a specific plugin that uses those commands, the commands should function properly as long as the plugin version matches your Minecraft version.

If you are not using a reload/restart plugin, the best you can do is stop the server and start it again.  (As far as I know, anyway.  I've never used a reload/restart plugin.)

**Note:** If you are making changes to Essentials or PermissionsEx, you can use the commands /essreload and /pexreload to reload those plugins specifically.

If there are any error messages in the server startup log, use [Pastebin](http://pastebin.com) and show me the full log.

**Comment by AnonymousHitman** [comment]
http://pastebin.com/C3k9UdiJ

**Comment by AnonymousHitman** [comment]
I restarted the server without doing /restart or /reload and it still disables

**Comment by AnonymousHitman** [comment]
Ive never had this problem with groupmanager....

**Comment by Stormbow** [comment]
You didn't say you're trying to use SQL.

Why is the entire console log one line of text?

**Comment by Stormbow** [comment]
All I can see so far is that there's some kind of database connection error, the SilkSpawners plugin has been downloaded 5 times, and the PEX .jar file may have been corrupted when you downloaded it.  (You should also be using 1.23.4 from [right here](https://dev.bukkit.org/projects/permissionsex/files/909154).)

**Comment by Stormbow** [comment]
No response in more than 7 days. Issue must be resolved.
