### ISSUE TITLE
Error at boot-up trying to upgrade to PEX 2.0

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2694]
My problem has nothing to do with offline mode, it won't run even if I run just a stand alone spigot server. If I delete the PEX folder it starts up fine, even with my setting to run on BungeeCord. So the issues has to do with converting old perms to new format, that's why I need to figure out how to setup me as OP which the commands don't seem to work.

**Comment by Ironic8b498** [comment]
in console when I type "pex group admin def true" the servers freezes and then crashes. Also when I type "/pex user <name> parent add group admin" and "/pex default user parent add group default"

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
