### ISSUE TITLE
PEX Prefixes not working

### ISSUE THREAD

**Issue by Raff64spr** [PEXPlugins/PermissionsEx#2696]
I set the prefixes for the groups but even if i'm in them they don't work.
I'm using EssentialsChatX as chat manager.
Plugins List
![screenshot_1](https://cloud.githubusercontent.com/assets/16598984/23041145/2c924328-f494-11e6-926f-dc3baf2261f3.png)

**Comment by Stormbow** [comment]
If you're using EssentialsX (and EssentialsXChat) on a Spigot server, you don't need ChatManager.  Having 2 chat management plugins will mess you up.

It's important to note, also, that "ChatManager" is not supported by PEX.  The original "Chat Manager" plugin was discontinued and literally dozens of authors took that code, made their own "Chat Manager" plugin (keeping the name of the old plugin, but using their own coding changes over time) and it became too much of a pain in the ass to keep PEX compatible with all of them.

You're also using Multiverse, which has some prefix handling built in.  So between the EssentialsX config.yml and the Multiverse config file(s), you'll have some stuff to setup to get the prefixes to display in-game the way that you like them.

----

On an unrelated side note, if the EssentialsKitManager plugin does something that Essentials does not do, keep it.  Otherwise, it's just wasting space on your server because Essentials and EssentialsX have truly _amazing_ kit management capabilities already.  Likewise with the OpenInv plugin.  Essentials and EssentialsX allow you to see into other players inventory.

**Comment by Stormbow** [comment]
The EssentialsX files that are required for a Spigot server are:

* [EssentialsX-2.0.1.jar](https://ci.drtshock.net/job/essentialsx/)
* [EssentialsXChat-2.0.1.jar](https://ci.drtshock.net/job/essentialsx/)

**Comment by Raff64spr** [comment]
I removed ChatManager but it's the same

**Comment by Stormbow** [comment]
Did you edit/setup either of the config files I said needed to be setup?

**Comment by Raff64spr** [comment]
In Multiverse i set prefixchat to false

**Comment by Stormbow** [comment]
Are you copying small parts of the file to Pastebin?  (Why would you do that?)

My Essentials (not EssentialsX) config.yml is much, much, _**much**_ longer than yours.  And EssentialsX is based directly on Essentials, keeping the files very, very similar.  You didn't even copy either of the chat sections, if you have the correct config file on your server.

**Comment by Stormbow** [comment]
See [this example](http://pastebin.com/eHCCcNuY) for snippets of the correct sections you should be editing in the EssentialsX config.yml file.

I don't use Multiverse, so you're on your own configuring that file.

**Comment by Raff64spr** [comment]
It's working now, thank you

**Comment by Stormbow** [comment]
Excellent. :)

You're welcome.
