### ISSUE TITLE
Setting up PEX 2.0

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2703]
Stormbow You assigned zml2008 to a few issues I had latest one was last week, I have not had an issue with your response or help. zml2008 has not been active in the month of February is there anyone else that can help with my issues Pex 2.0 or should I just try to make PermissionsEx-1.23.4 work. With an update to one of my plugins I was able to make 1.23.4 fix the reason I needed to use PEX 2.0 but I now have an issue with essentials chat not seeing all the groups a player is in. So group formatting is not working on all servers, any ideas? A better chat format plugin, or a setting to make essentials chat to work, either way works for me.

**Comment by Stormbow** [comment]
Unfortunately, I'm not doing any of the programming for 2.x and I haven't actually even used it myself yet, so I assign all of the 2.x tickets to him.  It's also been about 5 years or so since I used SQL, so I've forgotten pretty much everything about SQL that I did learn in the one month I did use it, so I assign those to zml too.  That should explain why I don't comment on some tickets and just assign zml to them— he's _the_ guy behind PEX; I'm just a "guru" for 1.x versions.

Zml brought me in to handle the 1.x issues and some documentation for 1.x a few years ago after I went through about a hundred or so posts on the original 1.x forums that I could answer.  I wrote up a lot of really good, detailed guides that used very clear instructions and explanations, then Bukkit went and deleted the forums without any warning at all, so I lost all of the PEX guides and tutorials as well as the EssentialsChat/EssentialsXChat/Prefix guide I'd written up.

I can tell you that PEX 2.x is "still in development" and there haven't been any "official" releases yet.  The builds that people have been using are strictly "development builds" to the best of my knowledge.  That said, I'd recommend to anyone that they try to make 1.23.4 work for their permission needs for the time being.

I assume Zml is a very busy guy in real life, with a whole lot of stuff going on, so he doesn't get as much time to come in and work on PEX as he would like to.  I know it's tough, but try to hang in there if you need his more technical and programming-related expertise on PEX 2.x if 2.x solves a specific problem you have.

If you want to go back to 1.23.4, I'll do my best.  I've never used Bungeecord or Multiverse, so my helpfulness with those 2 plugins is also pretty limited.

**Comment by Ironic8b498** [comment]
My server never left 1.23.4. I tried PEX 2.0 on my testing server. I have 1.23.4 running fine, just essentials chat is not displaying the correct group format for some players since they have multi groups assigned to them. I have been looking at Deluxechat which seems to be able to fix my issue. Deluxechat handle group assignment by perms and I'm sure I can assign it to see the correct perm depending on the world they are in. 

My guess there not a command I can add to 1.23.4 to help essentials chat see the correct group for when I'm on that server?

I'm assuming the last assigned group to a player would be the primary group in vault?

**Comment by Stormbow** [comment]
Are you currently using weight values on the 1.23.4 server?

**Comment by Ironic8b498** [comment]
yes, but some ranks have equal weights, I have 8 server one of those is the lobby which only has one rank the default one you get on first login. two other servers which have 2 ranks on each server.  The remainder of the servers have 7 groups each. All servers have their own ladder.  I use Autorank to instantly rank up players to the group used on the server they joined. I have tested each server for the chat format if it works if the player has only the rank meant for that server. Chat format works fine with only the one group.  so maybe assigning the weight in a way might fix my problem

**Comment by Stormbow** [comment]
Ok.  Let me know how that works out.

**Comment by Ironic8b498** [comment]
I couldn't get weights to let the proper ranks to display, I now understands weights much better, I decided on the plugin DeluxeChat and I was able to make custom chat formats for each server that worked great since it relies on perms not placeholders of a rank.

**Comment by Stormbow** [comment]
Issue resolved?

**Comment by Ironic8b498** [comment]
I thought I closed this. Yes issues resolved if you call using the 1.23.4 version and not 2.0.

**Comment by Stormbow** [comment]
Cool.  Thanks for the update.
