### ISSUE TITLE
Server crashing on join

### ISSUE THREAD

**Issue by TimoCrafter** [PEXPlugins/PermissionsEx#2713]
Hello,
I am using Pex 2.0 Bukkit.

Getting this crash report when joining:

https://paste.timocraft.at/avayugajim.css

Help please!!!

**Comment by TimoCrafter** [comment]
Thanks for doing something, @Stormbow . But it is really urgent. It worked before, but suddenly it works nowhere! I used a MySQL backup - nothing changed.

**Comment by TimoCrafter** [comment]
Update: Does not work in any way. Using a fresh installed spigot.jar, newest version from jenkins, also self-built version. Always crashing when interacting with backend.

#ShowStopper

**Comment by Stormbow** [comment]
Since PEX 2.x has not been officially released, the only person who can tell you anything about it is zml.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
