### ISSUE TITLE
Pex keeps shutting down!!

### ISSUE THREAD

**Issue by SeanyBoy1000** [PEXPlugins/PermissionsEx#2719]
Hey Everyone,

So I have been making servers for a while now and I love using PEX on all my Projects and when to download it and then as soon as I put my Perms in and hit reload it just did not work. It still did not work even after a complete shutdown. So I redownloaded it and tried it again and it worked but soon as I wanted to add more perms I made sure to Shut the server down. Soon as I got back on it still not working. It's like it works for one reload then it shutdown.

If there is anyone that could help me or Mabey tell me what's going on?

Mabey another plugin is affecting its work. Here's a List of the plugins.

1. ChestShop
2. EasyWarp
3. Essentials
4. iConomy
5. mcMMO
6. Multiverse-Core, Portals, and SignPortals
7. "PEX"
8. PluginMetrics
9. Updater
10. Vault
11. WorldEdit
12. WorldGuard

Please Help...

**Comment by Stormbow** [comment]
Any errors in the server startup log?  Copy the full startup log to [Pastebin](http://pastebin.com) and leave the link in this thread.

Which version of PEX?  Copy your full permissions.yml file to [Pastebin](http://pastebin.com) and leave the link in this thread.

Are you running a Bungeecord server?  (I can't help you with those.)

Are you using SQL?  (I can't help you with that.)

**Comment by SeanyBoy1000** [comment]
Hello,

Thx for the help. Here is all the info to your questions "Stormbow"

Here's the Startup - http://pastebin.com/f2kCbHsk

Here's the Permissions.yml - http://pastebin.com/NrCz96mv

No, this server is not a Bungeecord Server. It is a CraftBukkit 1.8

No, I don't believe I am using SQL.

I believe as well I'm using the "Essentials" reload function.

If there is anything else that you need to figure the issue out please list below.

**Comment by Stormbow** [comment]
• Your server version is _actually_ "1.8.8".  It's very important to be specific on this because plugins for "1.8" may not function on a server that is "1.8.8".

• Because you're running a Craftbukkit server, it's important to make sure your plugins are also for Craftbukkit and not actually for [Spigot](https://www.spigotmc.org/), which can sometimes be a problem.  This may be a problem for you too; see below.

Because the official "Craftbukkit" server wrapper— which was from the "Bukkit" website —was shut down by one asshole coder who DMCA'd (claimed copyright infringement against everyone else on the "Craftbukkit" project) the entire thing out from under the entire Minecraft community, you're better off running a Spigot server since the whole DMCA thing can't happen to Spigot.

• You have a corrupted PermissionsEx file.  Download PEX 1.23.4 from [right here](https://dev.bukkit.org/projects/permissionsex/files/909154).  (This seems to be the solution for previous "invalid plugin.yml" errors.)  This is the primary reason your server is not functioning correctly.

• It appears you have iConomy 7 for Minecraft "1.10" on your server.  This should not be expected to function properly on a "1.8.8" server until it has been completely tested.  The original "iConomy" plugin was discontinued about 8 years ago or so; most Minecraft servers today have "EssentialsX" handle their economy needs.

• It appears you are actually attempting to use "EssentialsX", and your version is is for Spigot "1.11.2" servers.  This, also, should not be expected to function properly on a "1.8.8" server until it has been completely tested.  "Essentials" for "Craftbukkit" was discontinued at version 1.8 by the original author (KHobbits) after the DMCA issues I mentioned above.  Since Spigot became the primary server wrapper, a user took up the "Essentials" name and created "EssentialsX" to run on Spigot servers.

• Your mcMMO plugin is also for "1.11.2" Spigot servers.  This should not be expected to function properly on a "1.8.8" server until it has been completely tested.  The final release for "Craftbukkit" was for "1.7.9" servers.

Once you have addressed all of these issues, post another server startup log for me to review if you are still experiencing problems and I'll help you get those straightened out too.

**Comment by SeanyBoy1000** [comment]
Dude, Thank you.

I will give them a try and I will get back to you.

Thanks Again!

**Comment by Stormbow** [comment]
You're welcome.  Good luck!

**Comment by SeanyBoy1000** [comment]
Dude, Dude, Dude

You are a Master at what you do!! XD

Thx Again, everything is working!!

Keep Helping People!!

**Comment by Stormbow** [comment]
Fantastic!  Have fun.  :)
