### ISSUE TITLE
Command suggest

### ISSUE THREAD

**Issue by SaitDev** [PEXPlugins/PermissionsEx#2721]
PEx 've already had a useful command: `pex user <user> group add <group> [world] [lifetime]`

But incase we run this command again for a user with same group, the lifetime will be overridden with new lifetime. It would be great if there's a command like `pex user <user> addtime <group> <lifetime> [world]`
to give more time for that user to be in a group

**Comment by Stormbow** [comment]
No new features will be getting added to PEX 1.x, but @zml2008 may consider doing something like this for PEX 2.x since it's still in development.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
