### ISSUE TITLE
PermissionsEx 2.x Documentation

### ISSUE THREAD

**Issue by EmanYm** [PEXPlugins/PermissionsEx#2723]
Greetings.

This might seem like a strange or silly question to some, but I am truly curious.

I'm trying to set up a server, and documentation for the 2.0 branch of PEX is lacking.
Will the PEX nodes on [this page](https://github.com/PEXPlugins/PermissionsEx/wiki/Commands) work for the Sponge version of PEX2?

**Comment by Stormbow** [comment]
Since PEX 2.0 is still in development, the documentation isn't very complete yet.

The page you linked is for PEX 1.x, up to [PEX 1.23.4](https://dev.bukkit.org/projects/permissionsex/files) which works on 1.11.2 servers.  Unless PEX 2.0+ has something you absolutely need on your server, you may want to consider using PEX 1.23.4 until 2.0 is ready.

**Comment by EmanYm** [comment]
I am trying to not sound demanding.  I understand that other things take priority and this is likely just a hobby for zml does for no real pay.
Would a user-based wiki work to get documentation going for the 2.0 branch?

It doesn't look like I'm left with much of a choice.  My preference is with 2.0, but since documentation is lacking I will have to use 1.23.4 until there's progress.

Just so I don't have to come ask later...
-Are all of the wiki pages are for the 1.23.x branch?
-Does that branch support MySQL?
-Will I need to rebuild my database (I have the permissions from all of the other mods already on the database.  I will backup the database before I switch regardless)

**Comment by zml2008** [comment]
The Ore page has links to more documentation for PEX.
