### ISSUE TITLE
PEX Commands won't work

### ISSUE THREAD

**Issue by vesko128** [PEXPlugins/PermissionsEx#2724]
Hey, i use pex from some time now and i come to the same problem again and again. the commands won't work. I watched a video where they say that i need to change the config file (permissions.yml to premissions.jar) this fixed the problem how ever not the permissions won't work. Here is my permission file- http://pastebin.com/4iNMwADR . I'm running spigot server. Sorry for my bad english

**Comment by Stormbow** [comment]
Your file is based on a bad example.

Use [this example](http://pastebin.com/8ZSHxauG) to organize your file's indentation and where everything goes.

**Comment by vesko128** [comment]
thank you so much i will try it out. Now i have some work so i will try it later.If it works i will close that issue.

**Comment by vesko128** [comment]
So i tried i added my permissions but nothing happened it's the same i will attach my server log (i have so many errors) http://pastebin.com/DqbSinBB. I cannot attach the server log i will place it in pastebin.
my log: http://pastebin.com/tty1C5mD .

**Comment by Stormbow** [comment]
Are you trying to run a Bungeecord server?

> [22:54:17] [Server thread/WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!

PEX requires the server.properties file to have `online-mode=true` or PEX will not function correctly.  Only on Bungeecord servers is that setting allowed to be false, and you would need to go to their documentation to learn how to set up a Bungeecord server correctly.

**Comment by Stormbow** [comment]
Other issues I have identified in your permissions.yml file:

• I don't know if it was an error caused during pasting or what, but you've got places in your file that are indented too far.  (See lines 1 and 49, for example.)

• To the best of my knowledge, "ChatEx" is not supported by PEX.  You will need to test every aspect of this plugin after you change the server back to `online-mode=true`.

• Line 48: blank permission node line needs to be deleted.

• Line 82: **Do not** give _anyone_, beside yourself, the node `permissions.*` as this node gives them the power to completely delete your permissions file.

• All of your groups (e.g., "VIP", "Donator", and "Builder") should have different "rank" and "weight" values unless they are on different ladders.

• All of your groups should have _one_ inheritance section.  (i.e., The "VIP" group should probably delete line 63.)

• Line 121-124: Fake permission nodes from my example file.  You can delete all of these.

• Line 167-171: PEX will never see these lines because line 166 gives the "Owner" group _every_ permission node on the server.

• Line 172: Blank line.  This should be deleted.

• Line 175: After the server is running in online mode, this will be your UUID.  To get this entered properly, you should delete your entry (lines 175-181) and let PEX fill this information into the file the next time you join the server.  After the information is entered, you can give yourself full access to the PEX commands by typing `pex user Stormbow add permissions.*` into your server console.

**Comment by vesko128** [comment]
Thanks I will try it. Can you give me a permission plug that works with onlinemod-false (and not berms it's so hard to make the perms file.

**Comment by vesko128** [comment]
Soon I will update the server to 1.9.4 and all of my plugins are for 1.9.2/1.9.4

**Comment by Stormbow** [comment]
> Can you give me a permission plug that works with onlinemod-false (and not berms it's so hard to make the perms file.

Nope.  I don't know of any that support hacked/illegal clients.

**Comment by vesko128** [comment]
i don't know what i'm doing wrong (sorry not new to a minecraft server but tottaly new to a permissions plugins)
permissions: http://pastebin.com/seJ9ZiZf
log: http://pastebin.com/GfkWcAsN
ignore the citizens error in the log

**Comment by Stormbow** [comment]
Is the server.properties file set to `online-mode=true`?  If not, nothing will work correctly.

[This file](http://pastebin.com/kwCudPxG) fixes all of your remaining syntax errors.

**Comment by vesko128** [comment]
it is in online mode you can look at the log i will try this now

**Comment by vesko128** [comment]
my final question
Why there is double owner (owner owner vesko128:message

**Comment by Stormbow** [comment]
> Why there is double owner (owner owner vesko128:message

Improperly configured chat management plugins.  (EssentialsChat/EssentialsXChat, ChatEx, Multiverse)

**Comment by vesko128** [comment]
oh essentials chat
ye sorry
i will remove it

**Comment by Stormbow** [comment]
> THANK U SO MUCH 

You're welcome. :)  Have fun.
