### ISSUE TITLE
SQL Error on Minecraft 1.8 server running PEX 1.23.2/2x(?) 

### ISSUE THREAD

**Issue by nopnse** [PEXPlugins/PermissionsEx#2726]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/7035ddf2b1f557bea34f)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
