### ISSUE TITLE
Too Many Arguments

### ISSUE THREAD

**Issue by Crueldog** [PEXPlugins/PermissionsEx#2729]
Running Sponge 1.10.2 with PEX b147 from Jenkins.
Whenever I type /pex (regardless what I type after, even /pex group or whatever), it only responds "Too Many Arguments"

**Comment by Yoniez** [comment]
I have the same issue, @zml2008 Can you help please?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
