### ISSUE TITLE
Mysql not syncing

### ISSUE THREAD

**Issue by woodzykiler** [PEXPlugins/PermissionsEx#2730]
So the Mysql part of this plugin is NOT updateing the other sub servers..
Config below in the link.
http://pastebin.com/VCP5NM6k
MC 1.11.2, Spigot, Bungee, Liunx Ubuntu 16 X64, Latest Mysql. Java 8
Pex 1.23.4
Also the chat Prefix isnt working right..
EssentalsX 2.0.1-B468
EssenalsChat

**Comment by Stormbow** [comment]
A couple notes I can help you on:

• Be sure you're using "EssentialsXChat" from [this download location](http://ci.drtshock.net/job/essentialsx/)
• Be sure you have [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) installed on the server since it is a dependency of "EssentialsXChat".

You'll need @zml2008 to help you with the SQL issue since I haven't used SQL in more than 5 years and I've forgotten almost everything about it.

**Comment by woodzykiler** [comment]
i have both of them installed. not to sure whats going on through.
on all server except the main HUB, should the permissions file be blank vs. preloaded

**Comment by Stormbow** [comment]
Sorry.  I can't help you with Bungee or SQL.  You'll have to wait for @zml2008 to reply.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
