### ISSUE TITLE
PEX 1.23.3 | Unix(?) | SQL issue

### ISSUE THREAD

**Issue by DraculaPrince** [PEXPlugins/PermissionsEx#2734]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/4da6e58ee3f767dfd559)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
