### ISSUE TITLE
[PEX 2.x] Ranking Ladder Issue

### ISSUE THREAD

**Issue by MrFoolz** [PEXPlugins/PermissionsEx#2739]
So I'm having trouble understanding how ranking ladders work. i would like to use ranking ladders to have a staff team easily promote and demote a user.

**Comment by Stormbow** [comment]
Which version of PEX are you running?

**Comment by Stormbow** [comment]
Basically speaking, rank ladders are collections of groups for which the promote and demote commands are used.  Each group in the rank ladder has a rank value, and PEX will promote or demote users up and down the ladder according to those values.

Since you're using PEX 2.x, you'd need @zml2008 to reply here if you need specific commands or have other more specific questions.

**Comment by MrFoolz** [comment]
Thank you, I'm almost certain i figured it out completely.

**Comment by Stormbow** [comment]
You're welcome.  If you're satisfied, you can close the ticket if you want.

**Comment by MrFoolz** [comment]
Another question is how would i set any new user to default ?

**Comment by zml2008** [comment]
Using the command `/pex default user parent add group <default group name>`
