### ISSUE TITLE
group inhartance not working

### ISSUE THREAD

**Issue by woodzykiler** [PEXPlugins/PermissionsEx#2740]
http://pastebin.com/93Qyc5Lv

its not taking perms from the lower rank groups

**Comment by Stormbow** [comment]
Which version of Minecraft and PEX are you running?

**Comment by woodzykiler** [comment]
Pex 1.23.4
MC 1.11.2-R0.1

the Schema-Version was never touched. ill fix it now
ok this is odd.. its doing some but not all of them. a Mod should be able to use world edit like the FoxVip+ guys. but the Mod cant. and the FoxVIp+ can.

On a side note, what about the Prefix colors and a plugin that will work for it. EssentalsX is what i use as a main

**Comment by Stormbow** [comment]
> a Mod should be able to use world edit like the FoxVip+ guys. but the Mod cant. and the FoxVIp+ can.

**Comment by Stormbow** [comment]
> a Mod should be able to use world edit like the FoxVip+ guys. but the Mod cant. and the FoxVIp+ can.

**The inheritance chain for the "Mod" group:**
Mod ← Helper ← Fox ← Foxfan ← Foxcub ← Guest ← No Inheritance (An inheritance is required in all groups as of Minecraft 1.9 and higher.  See line 19 of [this example](http://pastebin.com/8ZSHxauG) to correct this missing inheritance.)

Mod inherits from Helper, which inherits from Fox, which inherits from Foxfan, which inherits from Foxcub, which inherits from Guest.  So "Mod" would have everything of all of those groups.  Since no group in that chain inherits from FoxVIP+, members of "Mod" also do not inherit from "FoxVip+" and don't have access to "world edit like the FoxVip+ guys".

Also, even if "Mod" did inherit from "FoxVip+", "FoxVip+" does not have any permissions for the WorldEdit plugin either— "UltFox" does —so again, "Mod" would not have access to WorldEdit beyond the `worldedit.butcher` permission which is directly given to the "Mod" group.

As far as the `worldedit.butcher` command goes— if that command is not working, be sure you're using the command correctly as it has changed over the years.  (Arguments are now required elements of that command.  See the WorldEdit documentations for the correct usage of that command.)

----

On a somewhat related note to not giving out permissions correctly, your "Owner" group has the incorrect node of `essentials` on line 272.  That won't grant them anything.  See the EssentialsX documentation for the proper nodes, or use `essentials.*` to give the group _absolutely every permission node related to Essentials, including many undesirable nodes_.

----

Chat prefixes/suffixes and coloring will best be handled by [EssentialsXChat-2.0.1.jar](https://ci.drtshock.net/job/essentialsx/) + [Vault](http://dev.bukkit.org/bukkit-plugins/vault/).

**Comment by woodzykiler** [comment]
im very tipsy tonight. and that does make since! thank you@!
So the Rank: ### is only for the ladder stuff?

**Comment by Stormbow** [comment]
> So the Rank: ### is only for the ladder stuff?

Correct.

**Comment by woodzykiler** [comment]
so to have one rank use the permissisons from anouther rank i use the Weight: ### ?
and the ladder stuff is for promoting right?
and can the ladder be user for auto promoting, like play time on the server

**Comment by Stormbow** [comment]
> so to have one rank use the permissisons from anouther rank i use the Weight: ### ?

No, inheritance.  Weight values are for when a user in is multiple groups; the weight value decides which group will show its prefix/suffix in chat, for most chat management plugins.

**Comment by Stormbow** [comment]
Problems solved?

**Comment by Stormbow** [comment]
No replies from OP in almost a week.  Case closed.
