### ISSUE TITLE
PEX Not Enabled???

### ISSUE THREAD

**Issue by Sunboyz21** [PEXPlugins/PermissionsEx#2743]
So I downloaded PEX and everything. I made sure my config and permissions.yml were valid with no errors, but still, when I do /plugins, PEX does not show up.
Here is my log: http://pastebin.com/XkjggQ6i
Config.yml: http://pastebin.com/2VasQqi6
Permissions.yml: http://pastebin.com/qCGBv54p
Thank you for your time.
Chief_Sunboyz

**Comment by Stormbow** [comment]
• Download PEX 1.23.4 from [right here](https://dev.bukkit.org/projects/permissionsex/files).  Your current permissionsex.jar file is corrupted.

• Your permission nodes are messed up pretty badly.  For example, it's `essentials.msg.*`, not `essentials.msg*`— and you have done that quite a lot throughout the file.  You also have negated permissions (line 195) after global wildcards (line 194) so the negation will never be seen.  And some of your nodes don't even exist, like `essentials.gamemode.creative*`, so you need to refer to your plugins' documentation to learn the correct nodes.

• You're not likely to need "AdminEssentials" since you're using "Essentials".

• You're using the wrong version of "EssentialsSpawn".  Get the correct "EssentialsX" files for Spigot [right here](https://ci.drtshock.net/job/essentialsx/).

• Your Citizens plugin is outdated.

• Do you really need 3 (technically 4) anti-cheat plugins?  (AntiCheatReloaded, Orebfuscator, and Minesecure?)  That's quite paranoid, especially since you have CoreProtect which can rollback anyone you find out is cheating.  `¯\_(ツ)_/¯`

**Comment by Sunboyz21** [comment]
@Stormbow 
Update:
---------------------
Fixes:
Fixed permissions nodes
Fixed Inheritances
Fixed names//prefixes
Updated Citizens
Fixed Essentials Spawn (Removed//Not needed)
Anti Cheat slimmed down
---------------------
Not fixed//Dont'understand:
1. What tf do you mean be "You also have negated permissions (line 195) after global wildcards (line 194) so the negation will never be seen." I don't code much so....
2. PEX 1.23.4 is 1.11/1.10/1.9 but I'm running 1.8
3. Probably will update to 1.11 once I find a plugin that removes the combat delay (That my host provides/supports) and 1.8 support
---------------------
Also, the error I'm actually getting is this;
![capture](https://cloud.githubusercontent.com/assets/26012347/24338620/a805731a-125b-11e7-98b9-ca370c647656.PNG)
Thanks, 
Chief_Sunboyz

**Comment by Sunboyz21** [comment]
Here is the new permissions.yml (fixed): http://pastebin.com/ngEztACk

**Comment by Stormbow** [comment]
> What **the fuck** do you mean ...

Are you cussing at someone who is trying to help you?

**Comment by Stormbow** [comment]
> What **the fuck** do you mean ...

Are you really cussing at someone who is trying to help you?  You realize that's not a smart idea, right?

**Comment by Sunboyz21** [comment]
I am sorry and apologies, I'm was a bit overwhelmed by what you said. Please do not discontinue helping me because if my mistake. 
Also though, What do you mean by: "corrected some formatting issues. No content changes."

**Comment by Stormbow** [comment]
> I am sorry and apologies,

Apology accepted.  :)

> "corrected some formatting issues. No content changes."

When you submitted the post, this silly website made some of the text extremely large, so I fixed that stuff.  I didn't edit any of the other text/spelling/grammar/words/etc.

> https://github.com/PEXPlugins/PermissionsEx/issues/2743#issuecomment-289340296

I'm fixing your permissions.yml file now.  It's really, really messed up.

**Comment by Sunboyz21** [comment]
Ok thank you so much!

**Comment by Stormbow** [comment]
Ok, here ya go: http://pastebin.com/EXy6vJ8k

Take a look at it and you'll see a few recommended improvements too.  Most notably, I shortened many of your group names. (For example, "Sr Administrator" becomes "SrAdmin"; "Developer" becomes "Dev"; other names changed as well in the Moderator cluster)  There are multiple reasons I recommend these shorter names:

• Long names will be a pain in the butt for you to have to type out these big long names if you have to type them too often
• Some plugins can't handle long commands and long group names can make commands very long.  (You'll get an error message when the command gets cut off, and the command won't work correctly.)
• Some plugins can't handle names that have spaces, hyphens, or other special characters in them.  (The plugin won't see the group exists on the server, and won't be able to function for that group.)

---- 

> **Not fixed//Dont'understand:**
>1. What tf do you mean be "You also have negated permissions (line 195) after global wildcards (line 194) so the negation will never be seen." I don't code much so....
>2. PEX 1.23.4 is 1.11/1.10/1.9 but I'm running 1.8
>3. Probably will update to 1.11 once I find a plugin that removes the combat delay (That my host provides/supports) and 1.8 support

`1.` When you use wildcard permissions (like you'll see on line 271 of the file I made for you), PEX will stop looking for permission to do something if it finds that "global wildcard" line.  Since you had `- -punish.exempt` below that line in your original file, PEX would never know that the group was not supposed to be exempt from punishment.

What happens is, let's say you want to punish the CoOwner.  PEX would begin looking for your permission (as a member of the "Owner" group) to do that, reading from the top of the permissions.yml file to the bottom, and PEX would find that you can do absolutely everything on the server when it reads line 281 (of my file).  Then PEX would look at the target of your punishment to see if it can be applied to them (again, reading from the top of the file downward) and PEX would find the CoOwner could _not_ be punished because `punish.exempt` is included in the global wildcard permission node `- '*'` which was at the top of their permissions list (in your file) and PEX would stop looking for any other permissions related to what is going on.  PEX would never see the next line (of your file) which was `- -punish.exempt`.

2. PEX 1.23.4 will work on 1.8 servers.  The website hosting the files is just funky and doesn't let us set all of the correct versions the plugin will work on.

3. When you say "combat delay", I'm not sure what you're talking about.  Do you mean the cooldown between attacks that Mojang/Minecraft added to stop people from hitting others 50 times in 1 second for full damage on every swing?

**Comment by Stormbow** [comment]
Let me know if the file I made works for you.

**Comment by Sunboyz21** [comment]
Ok Thanks!!!!
UPDATE:
Perms work fine but no prefixes.....
-Chief_Sunboyz

**Comment by Sunboyz21** [comment]
Talk to me on Discord if you want regular live updates  Chief_Sunboyz#8751

**Comment by Stormbow** [comment]
> Perms work fine but no prefixes.....

If you kept EssentialsX, you can use [EssentialsXChat-2.0.1.jar](http://ci.drtshock.net/job/essentialsx/) to handle your prefixes/suffixes.

**Comment by Sunboyz21** [comment]
The problem is though, my host (Aternos for now; switching to Shockbyte later) does not have EssentialsXChat as a plugin available to download, would just regular EssentialsChat work?

**Comment by Stormbow** [comment]
I recommend contacting them as soon as possible to find out why they're not offering the full EssentialsX plugin and/or how to upload the file (from the link above) to your server.

**Comment by Sunboyz21** [comment]
Ok, in the meantime is there a chat plugin that you recommend that supports PEX's prefixes?

**Comment by Stormbow** [comment]
Nope.  I've always used Essentials, so I've always used EssentialsChat.  (And when Essentials+EssentialsChat ended at Minecraft 1.8, I moved to EssentialsX and EssentialsXChat.)

PEX doesn't support any of the "ChatManager"-named plugins, including "ChatEx".  (There are literally dozens of them, all programmed differently by different people and using the same plugin name.)

**Comment by Stormbow** [comment]
Problems solved?

**Comment by Stormbow** [comment]
No replies from OP in almost a week.  Case closed.
