### ISSUE TITLE
Order of grades

### ISSUE THREAD

**Issue by rodnicho** [PEXPlugins/PermissionsEx#2748]
Hello, I have 2 problem on the plugin
1)
- A player who is ranked "Member" then bought a grade (example Coal)
The shop adds its Coal grade. He can rankup rank B higher because the Coal rank is going first.
- How can I do for Coal grade passes in high school so that it can rankup B?

2) How can I put the "user" part in MySQL?

(When you read these problems quotes, do not think I've ever been to see the wiki before)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
