### ISSUE TITLE
PEX Prefixes Not Working

### ISSUE THREAD

**Issue by Sunboyz21** [PEXPlugins/PermissionsEx#2754]
Hello,
So, as you have requested StormBow. I contacted my host and asked why they did not include the full EssentialsX fork. They responded with 'They both do the same thing so why bother' 
Then, I downloaded EssentialsChat.
The server is in online mode (Even though the log might not say say, I provide a screenshot)
Everything is in valid YAML
But still, prefixes do not work. The only change is that everything I write is in green.
Help plz,
Sunboyz
(Here are the screenshots: http://imgur.com/a/K543H)
(Log: https://pastebin.com/hK0zd5kc)
(PEX permissions.yml: https://pastebin.com/ffJ9gNDv)
(PEX config: https://pastebin.com/sSuxQEVR)

**Comment by Stormbow** [comment]
> So, as you have requested Storm**b**ow. I contacted my host and asked why they did not include the full EssentialsX fork. They responded with 'They both do the same thing so why bother'

No, they don't.  The EssentialsChat  vPre2.14.3 file doesn't go with the Essentials v2.0.1-b370 file.  The first file is from [this plugin](https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/) and the 2nd file is from [this other plugin](https://ci.drtshock.net/job/essentialsx/).  "Maven project Spigot-Essentials" and "Project EssentialsX" are 2 completely different plugins, and they're forcing you to use the brains of the 2nd plugin with the guts of the 1st plugin.  It's like taking a human brain and slopping it inside the engine compartment of a car and expecting the car to run.  It just ain't gonna happen and you're going to keep getting this error on line 299 and 335 of your server log:

`[02:12:35] [Server thread/WARN]: [Essentials] ?4Version mismatch! Please update EssentialsChat to the same version.`

`[02:12:36] [Server thread/WARN]: ?4Version mismatch! Please update all Essentials jars to the same version.`

I would tell the server host that, and if they still can't provide me with the correct files or a way to upload the correct files to my server, they certainly don't deserve my money.

----

For a moment, we'll pretend that I haven't been running Minecraft servers for more than 6 years, that I don't know what I'm talking about when it comes to server plugins version matching, and we'll look at other stuff that may be causing the prefixes not to show up in normal chat.

• PEX will never function properly on a server which is running in offline mode, _**unless**_ you're running a Bungeecord plugin server.  In that case, you'd have to read the Bungeecord documentation to figure out how to set the server up correctly using `online-mode=false` in the server.properties file.

• The staff chat is getting their prefixes because that plugin (StaffEssentials?) is providing prefixes there.

• Look inside your plugins\Essentials folder for a config.yml file.  Look inside that text file and compare the sections you find in [this example](https://pastebin.com/eHCCcNuY) to the same settings inside your file.  Change your file as needed to match the example linked here.

Then test the server and let me know what happens.

**Comment by Sunboyz21** [comment]
Ok so I did all that with a few exeptions, (In the Essentials Config) and now it's like this:
![2017-04-15_14 16 29](https://cloud.githubusercontent.com/assets/26012347/25066809/33880e36-21e6-11e7-9ed2-7e5aa7b31479.png)
You already have all my PEX files but here's my updated essentials config:
https://pastebin.com/CdhqPL3j

**Comment by Stormbow** [comment]
Excellent.  You're almost there!

The `{DISPLAYNAME}` variable is actually Prefix+Username+Suffix, all added together.

In your Essentials config file, you're telling Essentials to display the Group name, then the Prefix(which you have set to be the group name, in color)+Username+Suffix.

To correct this, chance your Essentials config file lines 654-667 to [this format](https://pastebin.com/nMDEQAd4).  After you've saved that change, you can type `ess reload` into the server console or type `/ess reload` in-game, then type some text into chat to see the new formatting.

**Comment by Sunboyz21** [comment]
YAYAYAYAYYA I DID IT! Thanks SOOOO much!
![2017-04-15_14 39 17](https://cloud.githubusercontent.com/assets/26012347/25066937/47566a9a-21e9-11e7-82aa-09490d602757.png)

**Comment by Stormbow** [comment]
You're welcome.  :)  Have fun!

**Comment by 1-Lopzinc** [comment]
Hi! I've been having the same problem but the link to the example you linked no longer works. Any chance you're able to post it again? Thanks

**Comment by Stormbow** [comment]
Sorry. PEX is no longer supported.
