### ISSUE TITLE
Issues with creating groups

### ISSUE THREAD

**Issue by AceAI2** [PEXPlugins/PermissionsEx#2757]
So , i have a factions server , and the groups there are fine , 
Now i want to create a prison server , but it just wouldnt let me create groups , when im trying to 
/pex group A create , 
it says :
Autocomplete for <group> :
Assistant Administrator
Ive looked this error up and i just cant find anything , Can anyone help please?

**Comment by Stormbow** [comment]
You can most easily add the A, B, C, D, etc. groups directly into the permissions.yml file by using Notepad to open the file.

**Comment by Stormbow** [comment]
If you want to create the groups using commands:

Type `/pex group "A" create` in-game or `pex group "A" create` into the console.

(Notice the quotation marks around the group name.)

**Comment by AceAI2** [comment]
@Stormbow  The thing is , its saying Autocomplete for <group>: 
Assistant Administrator 
when im trying to create it from in game , i litteraly copy pasted ur command into the game , and it says that , thats the problem , its not letting me create the group because of that

**Comment by AceAI2** [comment]
@Stormbow I did get the autocomplete message after using the /pex group "A" create .

**Comment by Stormbow** [comment]
What version of PEX are you using?  I tested this on my 1.11.2 Spigot server before posting it here and the group named "A" was created with no autocomplete notice.

**Comment by Stormbow** [comment]
> >pex group "A" create
> [11:46:01 INFO]: Group "A" created!

**Comment by AceAI2** [comment]
server is 1.11.2 Spigot aswell , 
PEX is 1.23.4

**Comment by Stormbow** [comment]
Error messages?

Online mode?

**Comment by AceAI2** [comment]
Sadly,  only the head owner has the console , i dont , i have access to FTP if that helps , but idk when the owner will be back therefore , ill have to answer you later, Thanks for now :)

**Comment by Stormbow** [comment]
OK.  I'll check on this ticket later.

**Comment by AceAI2** [comment]
@Stormbow  09.04 15:36:36 [Server] INFO Autocomplete for <group>:
09.04 15:36:36 [Server] INFO Assistant   Administrator

**Comment by Stormbow** [comment]
Show me the full server log from the moment the server starts until text stops printing to the console and there is a message similar to "Done!".

**Comment by AceAI2** [comment]
https://ufile.io/6a2fa
thats the latest log , fully. there are done msgs there, thats what i got from the owner. (it wont let me just post it in here).
Virustotal scan (just incase u dont believe me) : https://virustotal.com/he/file/080fa7036be0cb83109b73d6e66e2bfe7779c1e12ea16ea992f7d5c11aabb200/analysis/1491835517/

**Comment by Stormbow** [comment]
A lot of outdated plugins, incorrectly configured plugins, mismatched plugins, and possibly some unnecessary plugins— but no PEX errors.

Show me the permissions.yml file found inside the plugins\PermissionsEx folder.  (Copy the file contents to [Pastebin](http://pastebin.com).)

**Comment by Stormbow** [comment]
I can't recreate this error on my server.

Have the actual server owner contact me  in this thread if they consider whatever you're experiencing to be a problem.

**Comment by AceAI2** [comment]
https://pastebin.com/v1uN8NPC
Sorry for the delay, the owner's computer messed up completely, anyways , this is the file uve asked for , 
The owner is dumb basicly and im the guy who does this for him , but i have 0 clue what's going on.

**Comment by AceAI2** [comment]
@Stormbow ive got full access to FTP now , so i can give u answers faster.

**Comment by Stormbow** [comment]
What's your Minecraft name in that file?

**Comment by Stormbow** [comment]
After a very brief, preliminary examination of your file, I can tell you it's a mess.  More details will come after I get your username.

**Comment by AceAI2** [comment]
Mine is AceAI @Stormbow

**Comment by Stormbow** [comment]
• Most importantly, line 784 (`schema-version; 1`) needs to be moved above the `users:` section (line 501).  This line being in the wrong place can cause PEX to malfunction.

• Avoid using special characters in group names.  Groups like "Jr.Moderator", "Sr.Moderator", and "Co-Owner" will not be recognized by some plugin features in extremely popular plugins like Essentials/EssentialsX.  You can use special characters in the prefix settings without worry.

• Many of the groups have extremely screwed up multiworld settings.  For example, look at lines 489 through 495.  None of that stuff is legit.  You'll need to go through every group to remove the bogus multiworld settings.

• Many lines in the `users:` section are extremely screwed up.  For example, look at lines 724-726, 745-748, and 755-757.  These should all be deleted.

• Line 91: It's kind of a dick move to remove a user's access to the /help command.  That command tells them how to use the plugins they have access to.  On a related note, when I joined the server, I could still use /help and /list (which you have negated on lines 86, 87, 91 and 92).  You will need to go through each group and verify any negated permission nodes.

• Your "Donator" rank contains benefits which are a violation of the Minecraft End User License Agreement and may result in the server owner Minecraft account(s) being terminated by Mojang.  The only things you're legally allowed to offer in a "Donator" rank are things which have no impact whatsoever on in-game activities such as chatting in color, custom titles, capes, hats, and particle effects when they walk.

• Line 201: `/gmc` is not a permission node.

• Line 234: There's no need to negate a permission node that a group doesn't gain from an inheritance or a wildcard.  I think a few groups do this sort of thing.

• Line 346: `essentials.kittycannon` is not a permission node.

• Throughout the entire file, `bukkit.command` "Vanilla" permission nodes may not function correctly as of Minecraft 1.6.4 (at the very least).  You will have to test every one of these that you've distributed to each group.

• Lines 361-368, 371-382: You need to specify all of the users, groups, and ladders on the server, or use wildcards instead of `<user>`, `<group>`, and `<ladder>` in all of these nodes.

• Since you gave the "Developer" group the global wildcard (`- '*'`) on line 385, there's actually no reason to list any granted permissions; you'd only need negations listed, and above the global wildcard.  Many of your groups have this problem.

• Since you've given out the global wildcard to many groups, all of those groups have access to **_every_** permission node on the server, including the power to delete all of the plugin settings across the entire server.

• Line 524: `coupons.commands.giveall.` is probably not a real permission node since no permission node ends with a period.  Check all of your users for correct permission nodes, prefixes, suffixes, and other settings.

----

You may want to abbreviate your excessively long group names.  For example, "Jr.Administrator" could become "JrAdmin".  Minecraft's chat window is too small for excessively long prefixes, so you may want to shorten all of those too.

----

**None of the above problems (aside from the schema-version line being in the wrong place) could make issuing the command `/pex group "A" create" tell you anything about autocomplete.**

Maybe @zml2008 can tell us both what's going on.

**Comment by Stormbow** [comment]
PS - That "gadget" thing taking up slot 5 on the action bar and not being movable is **extremely** annoying.

**Comment by AceAI2** [comment]
Gotta give a hugh thanks to @Stormbow for the help , he really did help me alot , setting the configs again , creating more groups through the notepad, just have to say , HUGE thank you to this guy ! , Altho yeah, Still need that autocomplete solution , but besides that , everything is good, Thanks!

**Comment by Stormbow** [comment]
I opened a ticket specifically for @zml2008 to respond to about this autocomplete issue.  (Github linked it above.)

Hopefully he can let us know if there is a way to get around the autocomplete because I think it will be problematic for issuing any commands to any prison group which has the same letter as a group on the server.

**Comment by AceAI2** [comment]
@Stormbow  Thanks,  but actually the prison plugin has a /pranks add <group> <price> So , i have it all set up , but yeah , it is annoying if i want to create another group, for another server maybe ,
And also , another two small questions;
1. whats the node to make a group the default group in a specific world ? because i want group A to be the default group,  which it isnt as of right now.
2. Can i make it so that the Tags from the groups wont follow along in all of the worlds? 
Because as of right now , lets say  i rank up to B , I will see : B AceAI in the hub , which i dont want , So i was wondering if theres anything i can do to make it in the hub be just AceAI , and in the prison server be B AceAI.
Thanks again!

**Comment by Stormbow** [comment]
`1.` PEX 1.x doesn't have per-world groups or other `options:` section settings; I think they're coming in 2.x though.

`2.` This relates to #1; the `options:` section doesn't apply to worlds in PEX 1.x and may be part of 2.x (which is still in development and I haven't gotten into yet).

**Comment by AceAI2** [comment]
Alright, Thank you!

**Comment by Stormbow** [comment]
Zml replied to the other ticket (#2762).  You can read about it over there.

**Comment by AceAI2** [comment]
@Stormbow Do you have any info on Pex 2.x ? really want the per world groups :) hehe

**Comment by Stormbow** [comment]
Downloads: https://ci.yawk.at/view/PermissionsEx/job/PermissionsEx/

Commands (WIP; not all documented yet): https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Command-Equivalency.md

Documentation (WIP; not all documented yet): https://github.com/PEXPlugins/PermissionsEx/blob/master/doc/Tutorial.md

I haven't used it at all yet.  The only thing I can tell you is that the permissions.yml file structure is completely different.

**Comment by zml2008** [comment]
A group 'exists' globally (to the extent that a group really exists beyond the data attached to it), but any data that can be assigned to a group can be restricted to a specific world. In commands, you'd use the `--context world=<world-name>` flag, and for a segment in the configuration file you would add

```json
"contexts": {
    "world": "<world-name>"
},
```

at the same level as the `options` and `permissions` keys.

**Comment by AceAI2** [comment]
Alright , dont really want to mess up so , lets say i have this  : 
` A:
    options:
      default: 'false'
      build: 'true'
      prefix: 'A '
      suffix: ''
      rank: '1000'
      rank-ladder: Prison
      weight: '1000'
    inheritance: []
    permissions:
    - permission.node.one`
Where do i insert the Contexts thing?

**Comment by Stormbow** [comment]
As I mentioned previously, that format/layout isn't used at all in PEX 2.x and I don't really have any experience, information, or resources to help with it.

You'll need to wait for Zml to answer any questions about that version.

**Comment by AceAI2** [comment]
@Stormbow is it 2.0? Zml didnt mention anything about 2.0 .
And @zml2008 If it is 2.0 , is there a way to do it in 1.? If not , Can i transfar my current config as is to v2.0 or ill have to remake it?
Thanks.
