### ISSUE TITLE
MySql

### ISSUE THREAD

**Issue by mrmiijo** [PEXPlugins/PermissionsEx#2760]
I need help... I want to connect pex to mysql, because I have bungeecord server. Just it does not work. T
This is my config.yml
https://pastebin.com/iACD6DWu
When I run the server writes this error:
https://pastebin.com/CX2p2HEM

And plugin doesn't work - command /pex, doesn't work.
What I doing bad? Thanks

Sorry for my english.

**Comment by pegberink** [comment]
The plugin doesn't work because there is no backend available for your system.

It can be 2 things, one your MySQL host is not valid or the credentials for your database is not correct. I don't have any problem with the exact same config only different host / credentials.

Since you receive the following errors:

> ru.tehkode.permissions.exceptions.PermissionBackendException: Unable to connect to SQL database

> The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

I am assuming its your MySQL host.

**Comment by BannerGames** [comment]
Hi mrmijo (I'm not English too, I'm Portuguese) in the config.yml on backend: sql, change the sql to YAML.

**Comment by pegberink** [comment]
@BannerGames He wants it connected with MySQL instead of YAML. 

@mrmiijo I think this is an issue with your MySQL host / the credentials you have received.

`Your configuration must be fixed before PEX will enable
Details: Unable to connect to SQL database`

**Comment by mrmiijo** [comment]
Okay.. my problem is solved.. On my mysql hosting was blocked creating tabs...
