### ISSUE TITLE
The Group name is showing up as the prefix and can't be configured.

### ISSUE THREAD

**Issue by Luckexeric** [PEXPlugins/PermissionsEx#2763]
When i try to configure the PermissionEx's prefix, it just adds another prefix to the prefix I set. And that prefix added is the group name. Any ways to fix this? I tried to find a setting in the config but I couldn't find anything. Please help.
<img width="1193" alt="screen shot 2017-04-13 at 3 11 48 pm" src="https://cloud.githubusercontent.com/assets/27400321/24991054/a05a2aee-205b-11e7-9f3a-d46e8267c495.png">

**Comment by Stormbow** [comment]
PEX gives you a place to store the prefix, but it's actually your chat management plugin which makes them appear in-game.

Since most people run a [Spigot server](https://www.spigotmc.org/) and use [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/), [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) (which requires [Vault](http://dev.bukkit.org/bukkit-plugins/vault/)) is their chat management plugin.  In their case, the plugins\Essentials folder will contain a config.yml file which has the controls for the display of prefixes in-game.  (I'm one of those people, and the config settings for EssentialsChat and EssentialsXChat can be found [right here](https://pastebin.com/eHCCcNuY).)

It's important to note that many people also use [Multiverse](http://dev.bukkit.org/bukkit-plugins/multiverse-core/), and that plugin's config file(s) also contains some chat-management settings that can make the prefix display in-game look funky.  (I've never used that one, so you'd be on your own to figure out where and how to configure chat through that plugin.)

Which plugins are you using on your server?

**Comment by Luckexeric** [comment]
Ok, thanks for you help and I fixed it :). I had 2 chat management plugins, essentialsX and penchat. I removed pexchat and it was fixed :). thanks.

**Comment by Stormbow** [comment]
You're welcome. :)

Thanks for the update!

**Comment by Stormbow** [comment]
A wild problem has appeared!

Stormbow used "How can I help you?".

It's SUPER EFFECTIVE!

:)

**Comment by Stormbow** [comment]
Don't reopen tickets if there's no problem to post.  :wink:
