### ISSUE TITLE
[PEX 1.23.4] PermissionsEx permissions not working when changing world directory

### ISSUE THREAD

**Issue by Eldicor** [PEXPlugins/PermissionsEx#2766]
Hello,

I have new server that i cant configure. I have problem with PermissionsEx plugin for minecraft. I'm fighting with it 2 days but no effects. The problem is that the permissions plugin work in minecraft, i can use /pex menu add stuff etc, the prefixes work but ALL nodes dont work. 

The nodes WORK ONLY for OP players. But when normal player come to server, he gets the prefix but he cant do anything! I try already to install and old version of PermissionsEx, to uninstall other plugins like worldedit etc but nothing helps. The starting server log have no errors, the plugin /pl all is green.

my permissions.yml file https://pastebin.com/DyPuLVvt
my config.yml file https://pastebin.com/kBnNWB42

List of my installed plugins:

citizens,
Clearlag
Essentials 2.x
NocheatPlus
PermissionEx-1.23.4
RandomTP-noID
WOrldEdit bukkit 6.15
WorldGuard 6.2

Can you please help me?

I

**Comment by Stormbow** [comment]
Can you show me your server startup log via Pastebin?  That's all the text posted into the server console from the moment you start the server through the point where you see a message similar to "Done!".

**Comment by Stormbow** [comment]
The 3 problems that I see in your permissions.yml file are:

• The file is out of order.

• The groups are missing inheritance sections.

• Line 13 should not be blank.  (Line 13 is 4 spaces and no other content, so that's technically still "blank".)

You can take a look at [this example](https://pastebin.com/8ZSHxauG) to see which order each of the sections (`groups;`, `schema-version:`, and `users:`) should be in and how to assign inheritances to each of your groups.

If the server is running in offline mode (which I'm assuming it is because the `users:` section is missing all of the UUIDs, you haven't mentioned you're running a Bungeecord server, and you haven't listed Bungeecord in your plugins), PEX will never function correctly because is not supported by PEX.  Make sure the server.properties file has `online-mode=true`.

**Comment by Stormbow** [comment]
I guess this issue is resolved since Eldicor hasn't been back to comment.
