### ISSUE TITLE
PEX User being in multiple groups.

### ISSUE THREAD

**Issue by Hadesone11** [PEXPlugins/PermissionsEx#2767]
Hey guys, thanks for checking this out. I've been researching this all day and I can't seem to find a solid answer.

What I need to do is have two ranks, say, Admin and Donor. In the yml I have it set a prefix [Admin] under admin and suffix [Donor] under the donor group. I want to allow the Staff member to have the donor rank.
Currently when I use the pex command to 'set' my group to donor it sets my prefix to the default ranks prefix then the donor suffix works. Then if i set my group to a staff rank it gets rid of the Donor suffix.
P.S I have tried with rank ladder and without

I just want a definitive answer on what I need to do and what i'm doing wrong.

Heres my yml
https://pastebin.com/ccfMXBCJ

**Comment by Stormbow** [comment]
The "set" command— `pex user <user> group set <group>` —removes a user from all groups to which they belong, and places them into one group.

If you want a user to be in 2 groups at the same time, you would want to use the "add" command— `pex user <user> group add <group>` —instead.  You may also have to add `weight:` values to each of your groups to ensure the proper prefix is displayed in chat.  See [this example](https://pastebin.com/8ZSHxauG) to learn how `weight:` values should be assigned.

If that doesn't solve your problem, I'll need some more information:

• Which version of Minecraft are you running?

• Which version of PermissionsEx are you running?

• What chat management plugins are you using?  (Essentials, EssentialsX, TownyChat, Multiverse, something else?)

----

**Other issues I noticed in your permissions.yml file:**

• You need to increase all of your "`rank:`" values by 1 because "0" for the "Owner" group isn't a valid value.

• The group name "Co-Owner", which may not be recognized by some plugins' features.  I recommend you change the group name to "CoOwner" and you can leave the hyphenated name in the prefix.  Be sure to correct the inheritance for any group which inherits from "Co-Owner"/"CoOwner" too.

• If you're running Minecraft 1.9 or more recent, your group named "default" also needs an `inheritance:` section.  (Every group needs that section from Minecraft 1.9 onward.)  See line 19 of [this example](https://pastebin.com/8ZSHxauG) to give that group an "empty" inheritance.

----

**Comment by Stormbow** [comment]
Edited my previous comment.  You can see the changes on [the post](https://github.com/PEXPlugins/PermissionsEx/issues/2767#issuecomment-296002170).  (Edits don't get emailed to you.)

**Comment by Stormbow** [comment]
I did some _MAJOR_ edits on my [previous comment](https://github.com/PEXPlugins/PermissionsEx/issues/2767#issuecomment-296002170).  (Edits don't get emailed to you.)

**Comment by Hadesone11** [comment]
Thank you for your reply but it seems it still doesn't work. I added a weight field under the rank field with the same number as the rank (after I changed owner to 1 and incremented) and added the empty inheritance brackets.
![capture](https://cloud.githubusercontent.com/assets/27836576/25259786/d14dc1bc-260d-11e7-887c-d71df7770f4b.PNG)

**Comment by Stormbow** [comment]
Type out the exact result you're attempting to achieve:

`[World] [GroupA Prefix] [GroupB Prefix] Username [GroupC Suffix]` or whatever else you have in mind.

**Comment by Hadesone11** [comment]
[Prefix(Admin)] Username [Suffix(Donor)]
https://pastebin.com/cWBRGB43

**Comment by Stormbow** [comment]
And which plugins are you using on your server?

**Comment by Hadesone11** [comment]
![capture](https://cloud.githubusercontent.com/assets/27836576/25260202/40606436-2610-11e7-9c99-45cf20bd8b6e.PNG)

**Comment by Stormbow** [comment]
I don't think it's possible to assign specific group prefixes and suffixes with EssentialsChat or EssentialsXChat (which aren't listed in-game) and I've never used FactionChat, so I can't help you with that one.

Take a look at the [Essentials Chat Formatting page](http://wiki.ess3.net/wiki/Chat_Formatting) and you may be able to figure out how to setup the plugins\Essentials\config.yml file to get what you're after.

This isn't a PermissionsEx issue at all.  PEX only gives you a place to store prefix and suffix information.  The actual displaying of that information in-game is handled by— in your case —the EssentialsChat/EssentialsXChat and FactionChat plugins.  So you'll have to dig into their documentation to find out how they handle chat formatting.

**Comment by Hadesone11** [comment]
Alright thanks for your help 👍

**Comment by Stormbow** [comment]
If you can't get what you're after with those 2 plugins, you'll have to search around for another chat management plugin or abandon the concept you were attempting.
