### ISSUE TITLE
ModifyWorld

### ISSUE THREAD

**Issue by Techno3600** [PEXPlugins/PermissionsEx#2771]
Hello,

Does modifyworld. need its own plugin or is it incorporated into PEX.

**Comment by BannerGames** [comment]
ModifyWorld is a plugin and Pex is other.

**Comment by Techno3600** [comment]
So do I need Modifyworld to do the modify world. perms in the yml file

**Comment by Stormbow** [comment]
You can download Modifyworld [right here].

You can find the documentation for Modifyworld [right here](https://github.com/PEXPlugins/Modifyworld/wiki).

And because Modifyworld is an **_extremely_** complex plugin covers almost a dozen different features for _every_ block in Minecraft, you will need to know the [PEX Debug Procedure](https://pastebin.com/vhcWR2yK) to get the Modifyworld permissions correct on your server.

**Comment by Techno3600** [comment]
Hello,

This is the classic 'my prefixes aren't working", is there a plugin depedenndcy to make the prefixes work, I used the PEX commands to add the prefix so there is no config issue. Prefixes just don't work.
Know whats wrong?

Thanks
Techno3600

PS. Thanks for the permissions help it is working and I am very happy. Thanks again for helping!

**Comment by Stormbow** [comment]
> Hello,

> This is the classic 'my prefixes aren't working", is there a plugin depedenndcy to make the prefixes work, I used the PEX commands to add the prefix so there is no config issue. Prefixes just don't work.
Know whats wrong?

> Thanks
> Techno3600

> PS. Thanks for the permissions help it is working and I am very happy. Thanks again for helping!

PEX gives you a place to store prefix/suffix information.  It's up to a chat management plugin to actually display that information in-game.  Since most people run [Spigot](https://www.spigotmc.org/) servers and use [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/) to handle their basic commands, they also use [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) (which requires [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) to be on the server too) to handle their chat functions.

**Comment by Techno3600** [comment]
EssentialsX doesn't seem to be able to do any chat stuff. Do you if there is a certain setting that must be enabled. If there any alternatives?

**Comment by Stormbow** [comment]
> EssentialsX doesn't seem to be able to do any chat stuff. Do you if there is a certain setting that must be enabled. If there any alternatives?

EssentialsX does do all that "chat stuff", if you get the correct files (which I painstakingly and thanklessly linked for your convenience).

After you have the correct files, the plugins\Essentials folder will have a config.yml file and inside of that you'll change 2 different sections to something similar to [this example](https://pastebin.com/eHCCcNuY) (which you should customize to your server, of course).  If you can't find the 2 sections that I mention in the link in this paragraph inside your plugins\Essentials\config.yml file, delete the config.yml file you do have and the next time you start the server, EssentialsX will create the correct file there.

**Comment by Techno3600** [comment]
Hello,

Thanks very much for helping me, I am still very sorry to bother you again but I still have one more problem: the permission node ["-modifyworld"](https://pastebin.com/wi2TEX3d) does not take affect. Do you need the ModifyWorld plugin or is it already incorporated in the PEX plugin.

**Comment by Stormbow** [comment]
I [answered that question](https://github.com/PEXPlugins/PermissionsEx/issues/2771#issuecomment-296858912) for you already.   ;)

Modifyworld is it's own plugin.  (Download link is in the above post.)  If you want to prevent someone from doing absolutely everything, the node would be `- -modifyworld.*` in the group or user's permissions.

**Comment by Stormbow** [comment]
If you need any more PEX help, don't hesitate to ask.

You can still post in this thread; I'm just taking it off the open tickets list.
