### ISSUE TITLE
MySQL connects 1 server but not another

### ISSUE THREAD

**Issue by tmoflash** [PEXPlugins/PermissionsEx#2773]
I am lost because it works and has been working fine up to this point.

I have 3 servers - server-1 is where the database is located and bungeecord

I have server-2 using pex and server-3 using pex

server-2 no issues however, server-3 keeps telling me that it cannot connect.

https://pastebin.com/FTKvivbj

Here is my config file

https://pastebin.com/BjeuJcvG

Again same file is being used in server-2 multiple servers using pex works fine....seriously scratching my head on this one.

**Comment by Stormbow** [comment]
SQL and Bungeecord issues will need @zml2008 to answer.

**Comment by tmoflash** [comment]
I think I found the issue. Although I was using the DNS name for some reason it would not resolve on server-3 - so I changed it to the IP - it seems to be working.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
