### ISSUE TITLE
Too Many Arguments

### ISSUE THREAD

**Issue by Yoniez** [PEXPlugins/PermissionsEx#2779]
Everytime i tryo to type /pex or /pex user, i get the same error saying too many arguments. No matter what i type either through console or in game, if i type /pex at all, the errors gets displayed

05.05 18:33:40 [Server] Server thread/INFO Usage: /pex [debug|reload|import|ranking|[--context|--contexts|-c] [-transient] subject permission-default|delete|options|info|permission|parents|[-transient] subject-type list [filter]] 
05.05 18:33:40 [Server] Server thread/INFO Too many arguments!
YoItzSnuk ran command: pex user Yoniez add * 

Please Help, I Am Running

PermissionsEx [Jenkins] #147 on Spongeforge-1.10.2-2254-5.2.0-BETA-2272.jar

Can someone tell me a build of Pex and a sponge version for 1.10.2 that works?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
