### ISSUE TITLE
MySQL and establishing SSL connection problem.

### ISSUE THREAD

**Issue by KyattPL** [PEXPlugins/PermissionsEx#2780]
So please don't hate me because I'm new to MySQL and databases, but it seems that even when PEX connects to my database it doesn't change any values or something. I keep getting the same error: 

> Mon May 08 00:28:28 CEST 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

I don't know how to deal with that, help would appreciated so much!

**Comment by manjush** [comment]
just add useSSL=false

**Comment by ITzD3stiny** [comment]
How do you do that @manjush

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
