### ISSUE TITLE
Help, The console tells me that the permissions.yml file is missing!!

### ISSUE THREAD

**Issue by zVqlrio** [PEXPlugins/PermissionsEx#2783]
How can I fix the problem? Please, help me fix this problem!

Console (ScreenShot): http://prntscr.com/f75t9n

**] Edit by Stormbow: Removed permissions.yml file contents; doesn't need to be seen in this case. [**

**Comment by Stormbow** [comment]
That line actually refers to the permissions.yml in your server's root folder, and not the plugsin\PermissionsEx\permissions.yml file.  Only vanilla servers which use no plugins at all would use the file that line is referring to.

:)

**Comment by Stormbow** [comment]
If you run into any other PEX problems, you can still post in this thread.

**Comment by zVqlrio** [comment]
When I do /pl, can not see PermissionsEx! 

Sorry my english! :D

**Comment by Stormbow** [comment]
PermissionsEx is showing in red, or does not show up on the list at all?

**Comment by zVqlrio** [comment]
Now I reinstall it and is green, but after a reload It does not show me anymore

**Comment by Stormbow** [comment]
> does not show me anymore

Does not show what exactly?  Your user information?

**Comment by zVqlrio** [comment]
No does not show PermissionsEx in /pl and if I do /pex it say: Unkonw Command

**Comment by Stormbow** [comment]
What version of PEX are you using and did you download it from [this page](https://dev.bukkit.org/projects/permissionsex/files)?

**Comment by zVqlrio** [comment]
PermissionsEx-1.23.3, yes

**Comment by Stormbow** [comment]
Get 1.23.4 and test the server.  Do you get the same problem?

**Comment by zVqlrio** [comment]
Now PermissionsEx in /pl is red

**Comment by Stormbow** [comment]
Ok, that means there's a problem in your permissions.yml file.  Copy the permissions.yml file inside the plugins\PermissionsEx folder to [Pastebin](http://pastebin.com) and leave the link in this thread.

**Comment by zVqlrio** [comment]
https://pastebin.com/qPJygPCE

**Comment by Stormbow** [comment]
OK.  Give me a few minutes to look for the errors.

**Comment by zVqlrio** [comment]
Ok, thanks! :D

**Comment by Stormbow** [comment]
Your file is actually out of order for almost all of your groups' settings.

Begin by looking at [this example](https://pastebin.com/8ZSHxauG) and make sure all of your `options:` sections have the correct information in them.  By not putting the information in the correct place, PEX will malfunction.

You don't have to use _all_ of the `options;` settings in the above link.  Any of that information that you _do_ use in your file needs to be put into the correct place.  For example, almost all of your groups have the `prefix:` information outside of the `options:` section, so you'll need to move all of those into the correct location, under the `options:` section heading.

Also, you only have to use `default: true` in one group.  You don't _need_ to list `default: false` in all the other groups, but it won't hurt anything if you do.  (Doing so just makes your file unnecessarily long, like when you repeat the same permission nodes in every group.)

Since almost every group uses many of the same permission nodes that the "Newbie" group gets, you should consider making all of the other groups "inherit" the "Newbie" group's permissions:

```
    inheritance:
    - Newbie
```

As you see in [my example file](https://pastebin.com/8ZSHxauG), all of the groups inherit from the group before them, so even the "Admin" group in my example file gains the permission node `permission.node.one` (which is not a real permission node, from a real plugin— it's just an example of a permission node) that the "Guest" group has listed under `permissions:`.

Once you have your file organized correctly, according to my example, test the server again and let me know if you still need more help.

**Comment by zVqlrio** [comment]
Omg is working your example! Now i try to change something

**Comment by zVqlrio** [comment]
It's works! Thanks you a lot! :D

**Comment by Stormbow** [comment]
You're welcome.  :-)  Feel free to post here again if you run into any other PEX problems.
