### ISSUE TITLE
Build with the default is false

### ISSUE THREAD

**Issue by Helper1912** [PEXPlugins/PermissionsEx#2784]
Can i enable build with the default is false???
![image](https://cloud.githubusercontent.com/assets/21292391/26025286/6aaccc74-380e-11e7-81f5-146498f8c7bb.png)

**Comment by Stormbow** [comment]
The setting `default: false` is actually not required in any group.

The setting `default: true` is required in one group because PEX needs to know which group all newcomers to the server should be placed in.

You can see the complete list of options for a group in [this example](https://pastebin.com/8ZSHxauG).

**Comment by Stormbow** [comment]
**A word of caution:** Don't give the permission node `permissions.*` to a group on the server.  That node gives the group full access to all of the PEX commands, which includes the power to delete all of the groups and essentially destroy the server.

I recommend giving the node only to yourself (if you are the server owner) with the following command (replacing my name for your in-game, Minecraft name):

`pex user Stormbow add permissions.*`

**Comment by Helper1912** [comment]
So how i can limit permissions with the permission to build still works?
Bukkit

**Comment by Helper1912** [comment]
I don't want they use /kill, /effect or something like that. Just can /give, /time,..etc

**Comment by Helper1912** [comment]
my permissions.yml : https://pastebin.com/mUAEjaUq

**Comment by Stormbow** [comment]
Most of what you're giving out to your players are from the [Vanilla Permissions List](http://bukkit.gamepedia.com/CraftBukkit_Commands).  These permissions are not reliably controllable, and you will have to test every node you give out to find out if they work on your server.

Some of the permissions you're giving out don't actually exist.  The nodes `permissions.build` and `minecraft.build` don't exist in any official documentation that I have seen, so they don't do anything on your server or in your permissions.yml file.

All players, by default, can build and do everything else on a Minecraft server, as long as they are outside of the `spawn-protection:` radius.  The default for that radius is, I believe, 16 and is found in the server's server.properties file.  The spawn-protection radius is the distance outward from the first square everyone joins the server on that no one can break blocks, build, interact, etc.  Ideally, this setting should be set to 0, and then you would use other plugins— like [WorldGuard](http://dev.bukkit.org/server-mods/worldguard/) —to protect stuff you built and to prevent people from destroying your spawn area.

If you want to control what a group can do, have, hold, craft, pick up, interact with, and use on the server, you would install a plugin like [Modifyworld](http://dev.bukkit.org/bukkit-plugins/modifyworld/) and go through an extensive amount of testing and [PEX Debug Mode](https://pastebin.com/vhcWR2yK) use to get the permissions for each group setup the way you want them.  Most people just give a group access to the entire Modifyworld plugin (just like you did on line 12 of your file) and never do anything else with Modifyworld.

Setting up customized item use, crafting, interaction, and everything else is an _extremely_ advanced, and _extremely_ complicated process which you'll have to learn on your own.  Debugging (mentioned above) is super easy; deciding on what items, interactions, and everything else you want a group to be able to do is the complicated part and will require you to do a _**lot**_ of reading through the [Modifyworld documentation](https://github.com/PEXPlugins/Modifyworld/wiki).

For example, if you wanted to stop the "Player" group from doing anything with diamonds, you first want to change `use-material-names:` to `false` in the Modifyworld config file, then you'd look up the [Item IDs](http://minecraft.gamepedia.com/Data_values/Item_IDs) and maybe the [Block IDs](http://minecraft.gamepedia.com/Data_values/Block_IDs) for anything related to diamonds, and negate all of those activities (craft, drop, enchant, have, hold, pickup, use, have, hold, throw, take, and put) permission nodes through Modifyworld.  You might even decide to negate their ability to break diamond_ore blocks (Block ID: 56), so they'll never have the opportunity to mine their own diamonds (Item ID: 264), _and_ also negate their ability to pickup diamonds so they can't pickup their own diamonds or get diamonds from other people.

```
    permissions:
    - -modifyworld.blocks.destroy.56
    - -modifyworld.items.(craft|drop|enchant|have|hold|pickup|use|have|hold|throw|take|put).264
```

With just these 2 nodes, you've effectively stopped someone from getting diamonds and doing anything with them.

The 2nd node (above) is called a "RegEx", a "regular expression", and you can read more about those [right here](https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#pex-regex).

**Comment by Helper1912** [comment]
Is this an error?
![image](https://cloud.githubusercontent.com/assets/21292391/26032429/d9ae57b4-38bd-11e7-9f2f-c188303c7226.png)
server log : https://pastebin.com/Ai5pvQZZ

**Comment by Helper1912** [comment]
So confused :(

**Comment by Stormbow** [comment]
> [15:45:46] [Server thread/WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!

Your server is running in offline mode.  Unless you're running a Bungeecord server, PEX will not function correctly.  You will need to change the server.properties file to `online-mode=true` unless you're running a Bungeecord server, and if you are running a Bungeecord server, you will have to read their documentation on how to properly setup the server.

**Comment by Helper1912** [comment]
@@
PEX removed @@ i don't have money to buy the game :(
Wait..PEX still work with a Bungeecord server if online-mode of the server is false right?

**Comment by Stormbow** [comment]
I strongly recommend that you update your server to the latest version of Minecraft (1.11.2) also.

The main reason I say that is because the "Essentials" plugin that you're attempting to use for all of your basic and admin commands was discontinued at Minecraft 1.8 and there are no official "Craftbukkit" versions past Minecraft 1.8.

If you want to use Essentials (and really, who doesn't?), you'll need to run a [Spigot server](https://www.spigotmc.org/), then install [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/), [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/), plus [Vault](http://dev.bukkit.org/bukkit-plugins/vault/) to handle all of your basic/admin commands and your in-game chat formatting.

You can try using [these Essentials files](https://hub.spigotmc.org/jenkins/job/spigot-essentials/) on a Craftbukkit server, but I have never used them myself and have seen many, many people have problems with them.

**Comment by Stormbow** [comment]
> i don't have money to buy the game :(

I'm sorry to hear that.  PEX doesn't support hacked, pirated, or otherwise illegal servers.

> Wait..PEX still work with a Bungeecord server if online-mode of the server is false right?

Bungeecord connects multiple servers together and uses the `online-mode=false` setting; that's all I can tell you about it since I've never used it.

**Comment by Stormbow** [comment]
You can still respond here.  I've just closed the ticket since we're no longer talking about a PEX-specific problem.  (It's a server is offline problem.)

**Comment by ArhamR** [comment]
I was having the same issue players cant break blocks in the server but only if I OP them it will let them break blocks here is what I did:

groups:
  peasent:
    options:
      default: true
      prefix: '&7&lPeasent &r'
    permissions:
    - modifyworld.blocks.interact*
    - modifyworld.blocks.destroy*
    - modifyworld.blocks.place*
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.delhome
    - essentials.home
    - essentials.sethome.multiple.peasent
    - essentials.balance.others
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.afk
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.suicide
    - essentials.spawn
    - essentials.seen
    - essentials.seen.banreason
  magician:
    options:
      prefix: '&8&lMagician &r'
    permissions:
    - modifyworld.blocks.interact*
    - modifyworld.blocks.destroy*
    - modifyworld.blocks.place*
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.delhome
    - essentials.home
    - essentials.sethome.multiple.magician
    - essentials.balance.others
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.afk
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.suicide
    - essentials.spawn
    - essentials.seen
    - essentials.seen.banreason
  scientist:
    options:
      prefix: '&c&Scientist &r'
    permissions:
    - modifyworld.blocks.interact*
    - modifyworld.blocks.destroy*
    - modifyworld.blocks.place*
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.delhome
    - essentials.home
    - essentials.sethome.multiple.scientist
    - essentials.balance.others
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.afk
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.suicide
    - essentials.spawn
    - essentials.seen
    - essentials.seen.banreason
  mad scientist:
    options:
      prefix: '&b&lMad Scientist &r'
    permissions:
    - modifyworld.blocks.interact*
    - modifyworld.blocks.destroy*
    - modifyworld.blocks.place*
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.delhome
    - essentials.home
    - essentials.sethome.multiple.mad scientist
    - essentials.balance.others
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.afk
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.suicide
    - essentials.spawn
    - essentials.seen
    - essentials.seen.banreason
  builder:
    options:
      prefix: '&2&lBuilder &r'
    permissions:
    - modifyworld.blocks.interact*
    - modifyworld.blocks.destroy*
    - modifyworld.blocks.place*
    - essentials.tpa
    - essentials.tpaccept
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.delhome
    - essentials.home
    - essentials.sethome.multiple.mad scientist
    - essentials.balance.others
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.afk
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.suicide
    - essentials.spawn
    - essentials.seen
    - essentials.gamemode
    - essentials.seen.banreason
  admin:
    options:
      prefix: '&9&lAdmin &r'
    permissions:
    - modifyworld.blocks.interact*
    - modifyworld.blocks.destroy*
    - modifyworld.blocks.place*
    - essentials.tpa
    - essentials.tpaccept
    - essentials.gamemode
    - essentials.give
    - essentials.heal
    - essentials.tp
    - essentials.fly
    - essentials.speed
    - essentials.nick.others
    - essentials.nick
    - essentials.tpahere
    - essentials.tpdeny
    - essentials.delhome
    - essentials.home
    - essentials.sethome.multiple.unlimited
    - essentials.balance.others
    - essentials.balance
    - essentials.balancetop
    - essentials.pay
    - essentials.afk
    - essentials.mail
    - essentials.mail.send
    - essentials.msg
    - essentials.suicide
    - essentials.spawn
    - essentials.seen
    - essentials.gamemode
    - essentials.ban
    - essentials.kick
    - essentials.togglejail
    - essentials.unbanip
    - essentials.tempban
    - essentials.seen.banreason
  developer:
    options:
      prefix: '&a&lDeveloper &r'
    permissions:
    - '*'
  coowner:
    options:
      prefix: '&6&lCo-Owner &r'
    permissions:
    - '*'
  owner:
    options:
      prefix: '&5&lOwner &r'
    permissions:
    - '*'

**Comment by Helper1912** [comment]
Maybe they can't break blocks at the spawn point. Try to break the blocks is far from the spawn point

**Comment by Stormbow** [comment]
@ArhamR — You should open your own ticket.  ;-)

There are many different reasons people might not be able to do things on a server.  Open your own ticket and I'll get your issues straightened out.  (It's always bad juju to hi-jack someone else's ticket, spamming their email with replies to your issue(s).)

**Comment by Helper1912** [comment]
@Stormbow It's ok, I don't mind with his replies. I still want to learn about this plugin.

**Comment by Stormbow** [comment]
@Helper1912 : Alright then...  :-)

@ArhamR : First, take a look in the server.properties file located in your server's root directory.  This file contains the setting `spawn-protection=16` and prevents everyone who is not OP'd from doing anything within a 16 block radius from the square where they first joined the server.  Since you're using plugins on your server, you may want to set this setting to 0 and allow the plugins on your server to protect it properly, as they were intended to work.

Plugins which may be preventing people from breaking blocks include WorldGuard (a very common plugin and the 2nd most common culprit of "no permission" errors) and other region-defining plugins like Towny, Grief Prevention, and more.  I'd need a complete list of your plugins to see if any of them are causing people to not be able to break blocks.

You can also attempt to use [Debug Mode](https://pastebin.com/vhcWR2yK), a part of PermissionsEx, to find out why people are being denied permission and the ability to break blocks.  If you can't understand the server console output, copy it to Pastebin and I can interpret it for you.

**Comment by ArhamR** [comment]
they cant break blocks near or far away from spawn @Helper1912

**Comment by Stormbow** [comment]
Ok.  Time to start at the very beginning—

What version of Minecraft are you running?

What version of PermissionsEx are you using?

What plugins are you using on your server?  (You can show me a screenshot or just type out ALL of the plugins you have installed.)

Are there any error messages in the server console when you start the server?  (Copy the entire server log— from the moment the server starts, until text stops printing on the screen and you see a message similar to "Done!" —to [Pastebin](http://pastebin.com) and leave the link generated in this thread.

And finally, show me your permissions.yml file.  (Again, copy it to Pastebin and leave the link in this thread.)

**Comment by ArhamR** [comment]
Q1- What version of Minecraft are you running?
A1 - 1.7.10 on Serverminer.com

Q2 - What version of PermissionsEx are you using?
A2 - Cant Tell

Q3 - What plugins are you using on your server? (You can show me a screenshot or just type out ALL of the plugins you have installed.)
A3 - Grief Prevention, ClearLagg,  EssentialsProtect.jar, WorldEdit, EssentialsAntiBuild.jar, Essentials.jar, EssentialsSpawn.jar, SimpleHolograms, CratesPlus, Autorank, PermissionsEx, EssentialsChat.jar, Lift, Multiverse-Core

Q4 -  Are there any error messages in the server console when you start the server? (Copy the entire server log— from the moment the server starts, until text stops printing on the screen and you see a message similar to "Done!" —to Pastebin and leave the link generated in this thread.
A4 - No Error

Q5 -  And finally, show me your permissions.yml file. (Again, copy it to Pastebin and leave the link in this thread.)
A5 - https://pastebin.com/QAwL0gFS

**Comment by ArhamR** [comment]
I think I have to remove EssentialsAntiBuild.jar (did not see that before but it was there in the plugins folder)

**Comment by Stormbow** [comment]
> I think I have to remove EssentialsAntiBuild.jar (did not see that before but it was there in the plugins folder)

Because you're using a server host's choice of plugin files— you aren't downloading them directly and installing them on the server yourself —you may be getting Essentials files which aren't for your version of Minecraft.  The _original_ plugin is called "Essentials" and it was a package of files which included the EssentialsAntiBuild which you haven't configured in your permissions.yml file correctly for EssentialsAntiBuild.  (You're missing the `options:` setting `build: 'true'` as seen in [this example](https://pastebin.com/8ZSHxauG).)  This is why it's very important to read _all_ of the documentation about any plugins we're planning to use on our servers; these little hidden settings can pretty much shut down your whole plan.

On a somewhat related sidenote, [Modifyworld](http://dev.bukkit.org/bukkit-plugins/modifyworld/) is the plugin most people use to control what users can have, hold, pickup, drop, craft, interact with, use, and more.  Most groups would be given `modifyworld.*` permission, and then any block/item/etc that the server owner didn't want that user to access would be negated _above_ that node in the group's permissions list.

Showing me your server log would have shown me all of the server and plugin version information, and— in this case —show me if you're getting "bad" "Essentials" files, files which are not for your version of Minecraft or that were created by "vTeam City" and have been known to have many, many errors in the code.

And, a little history lesson:  "Essentials" itself was discontinued at Minecraft 1.8 because Bukkit/Craftbukkit could no longer be updated as one of the co-authors claimed copyright infringement against everyone else on the project for using code he wrote for the project and the entire thing was shut down.  After Minecraft 1.8, and because virtually everyone is running "Spigot" servers that can't be shut down by one jerkoff that decides to claim copyright infringement against it, "EssentialsX" is the new "Essentials" plugin, for Minecraft 1.8.1 and onward.

**Comment by Helper1912** [comment]
@ArhamR It's so hard right now ~.~

**Comment by ArhamR** [comment]
nnnaaaaaah @Stormbow made it easier :) thank You @Stormbow

**Comment by Stormbow** [comment]
You're welcome. :)

Let me know if you need help with anything else.

**Comment by Helper1912** [comment]
@Stormbow Can you make an example about limit permissions? I want they can't use /kill /effect /op. Only can use /give /tp and the other

**Comment by Helper1912** [comment]
With those permissions online-mode should be true, right?

**Comment by Stormbow** [comment]
> With those permissions online-mode should be true, right?

Unless you're running a Bungeecord server, `online-mode=true` is required for PEX to function correctly.  PEX doesn't support offline servers or hacked, pirated, or otherwise illegal servers.

**Comment by Helper1912** [comment]
![image](https://cloud.githubusercontent.com/assets/21292391/26784317/302f564a-4a27-11e7-9f39-4bc9ed7b9e11.png)
Can you give me a link? I don't see anything about that

**Comment by Stormbow** [comment]
https://www.spigotmc.org/wiki/bungeecord-installation/

**Comment by Helper1912** [comment]
Arigatou~

**Comment by Helper1912** [comment]
BungeePerms, right?

**Comment by Stormbow** [comment]
> BungeePerms, right?

I honestly don't know what that _exactly_ means.  You'll have to read through their plugin to find out more/anything about it.

**Comment by Helper1912** [comment]
Ok. Arigatou~
