### ISSUE TITLE
Owner rank changed to Annioen???

### ISSUE THREAD

**Issue by Ironic8b498** [PEXPlugins/PermissionsEx#2788]
below is a section on my logs where I noticed my rank had changed. I can not find anything in my logs which could say how it happened. I'm using Autorank but I searched the ranks.yml and no mention of Annioen. Is there a hack out that that can change others ranks?

https://hastebin.com/noveganisu.vbs

**Comment by Stormbow** [comment]
If there is a hack that would do this, I haven't heard of it (yet, if ever).

The best thing to do in regards to PEX access is to give it to yourself directly, and never give it to a group because anyone in that group could change your rank, delete groups, and otherwise really trash the server.

Use this command in the server console to give yourself PEX access:  **`pex user Ironic_8b49 add permissions.*`**

Generally, I recommend that no one on a server be given any amount of access to PEX unless you can physically go over to the person's house and beat their ass if they destroy your server.  (And always keep a backup of your permissions.yml file, in case anyone deletes the groups and everything else.)

**Comment by Ironic8b498** [comment]
yes everything is backed up every 30 mins, I'm the only one who has pex commands, thats why I was shocked why and how it happened

**Comment by Stormbow** [comment]
It's possible that AutoRank moved you out of your group accidentally and automatically based on rules you've setup for AutoRank.  I'm not 100% sure how that plugin works as I've barely used it on my server (and there, only to move users from Group A to B to C with very simple circumstances).

I can tell you, with 100% certainty, that PEX itself doesn't have any automation features at all (not even handling the placement of prefixes/suffixes in chat in-game).

**Comment by Ironic8b498** [comment]
OK I did search of perms for permissions.* and found I gave admins that perm but I have no one set at admin rank right now

**Comment by Stormbow** [comment]
Ok.  Get yourself in the correct group (again) and keep an eye on the server for the next few days to see if it happens again.  If it does, come back here and post in this thread (bookmark it for the next couple days).

**Comment by Stormbow** [comment]
The ticket is closed for now, in case the problem was a fluke and it doesn't happen again, and you can still post here if it does happen again.

**Comment by Stormbow** [comment]
You can also reopen the ticket, below, if the problem happens again and you want to officially reopen the ticket.  Otherwise, if you post here, I'll go through the server with you to see what else could be causing the change.
