### ISSUE TITLE
Pex Perms not working

### ISSUE THREAD

**Issue by sharpshooter037** [PEXPlugins/PermissionsEx#2790]
my pex is not working in my server for some reason the perms doesn't work I've left my code in the message any help would be appreciated :)
[permissions .zip](https://github.com/PEXPlugins/PermissionsEx/files/1008367/permissions.zip)

**Comment by Stormbow** [comment]
What permission(s), exactly, do not work?

**Comment by sharpshooter037** [comment]
@Stormbow most of them dont work like /msg /bal . /warp sometimes works but yeah most of them dont

**Comment by Stormbow** [comment]
Ok, when you start your server, copy all of the text printed into the console from the moment it starts until text stops printing to the window and you see a message similar to "Done!".  (This is called your startup log.)  Paste it all onto [Pastebin ](http://pastebin.com) and leave the link generated in this chat for me to look at.

Also, if your permissions.yml file has changed at all since you posted it the the other day, copy that file to [Pastebin ](http://pastebin.com) too and leave that link here.

**Comment by Stormbow** [comment]
As far as your original permissions file is concerned, there's one fatal error:

• Lines 122, 123, and 124 should be deleted.  The `schema-version: 1` line should appear in the file only one time, above the `Users:` section.

One major error:

• Line 7 should be `essentials.build.*`.  (Delete the 2nd asterisk.)

One potential error that may not actually be an error:

• Lines 70 and 101: Capitalize the group names for these 2 inheritances.  I'm fairly sure it doesn't _really_ matter as far as PEX is concerned, but it's better to be very strict when you enter data.

----

As for the 3 commands you mentioned:

> /msg /bal

These 2 commands don't work because you haven't given access to their associated/base slash commands.  You need to add `essentials.msg` and `essentials.balance` to the "Guest" group.

> /warp

This command should work because you've given out all of the correct permission nodes and have all the correct inheritances.  The previously mentioned schema-version and capitalization errors _might_ be causing this command to malfunction.  Ensure you've created the warp correctly and are spelling the warp name correctly while trying to use the `/warp LocationName` command.  If you have created the warp correctly and you are using the command correctly, you may have to use PEX's [Debug Mode](https://pastebin.com/vhcWR2yK) to find out what's interfering with the command.  (For most people, it's because they used the WorldGuard plugin, and didn't give a group or user permission to warp into or out of a specific WorldGuard region.)

**Comment by Stormbow** [comment]
# A Word of Caution

Don't give **`permissions.*`** to any groups or users that you don't completely trust.  That single node gives them access to _**all**_ of the PEX commands, including the power to delete groups and essentially destroy your server.  I can't stress how dangerous this one node can be to your server, in the wrong hands, so I highly recommend removing it from all groups (because there are allegedly hacks that let users put themselves in any group) and _only_ give it directly to yourself (and people you would trust with your deepest, darkest secrets).

It's also best to give `permissions.*` directly to yourself because if you move yourself to the "Guest" group to Debug permissions, you won't lose access to all of the PEX commands.  Type the following command into the console to give yourself direct access to all of the PEX commands:

`pex user sharp_shooter037 add permissions.*`

**Comment by sharpshooter037** [comment]
Okay thank you I'm currently away from my server pc but I'll pop the log in tomorrow thanks for your help

**Comment by Stormbow** [comment]
You're welcome.  I'll be here.  ;-)

**Comment by sharpshooter037** [comment]
And also I realised /warp works

**Comment by Stormbow** [comment]
> And also I realised /warp works

Groovy.

**Comment by sharpshooter037** [comment]
Okay just a quick question what's the difference between essentials.build.* and modifyworld.* ?

**Comment by sharpshooter037** [comment]
okay don't worry i've fixed the /msg and /bal commands by getting rid of the * at the end but im running bungee cord so ill keep this thread open till i've done all servers lol. but thanks for your help so far i don't think i need to send you the startup log but if you want it just ask. i've made all the changes you said to the permissions.yml and it was fixed but i still want to know the difference between essentials.build.* and modifyworld.* if you don't mind :)

**Comment by sharpshooter037** [comment]
Thanks for your help that has saved me 3 days of fixing

**Comment by Stormbow** [comment]
> Okay just a quick question what's the difference between essentials.build.* and modifyworld.* ?

EssentialsAntiBuild.jar is required for the Essentials-based access, and doesn't come in the Essentials.jar file.  Essentials was built in such a way that it needs to be updated for most version changes of Minecraft; Modifyworld doesn't.  The `build: true` setting in the [permissions.yml](https://pastebin.com/8ZSHxauG) file is an EssentialsAntiBuild setting and not part of Modifyworld.

> And for /msg and /bal these were in the permissions.yml under essentials.msg.* and essentials.balance.*
but i haven't tried them after fixing the other stuff give me a couple of mins ill have a try.

`essentials.msg.*` and `essentials.balance.*` don't actually grant access to the slash commands though.  They give access to other sub-commands related to messaging.

----

> Thanks for your help that has saved me 3 days of fixing

You're welcome. :-)  Good luck with Bungeecord and have fun!

**Comment by Stormbow** [comment]
What's up?

**Comment by sharpshooter037** [comment]
Yeah hi im back i need a little check through on my admin and owner perms they appear to not be working

updated perm file: https://pastebin.com/PK3Q4e4M

**Comment by Stormbow** [comment]
What exactly doesn't work?

**Comment by sharpshooter037** [comment]
just the entire commands from the mod rank up im owner not op i can do mod commands but not owner perms.*

**Comment by sharpshooter037** [comment]
i was looking in the log i says this:

User sharp_shooter037 checked for permission '*', regex-matched a value of undefined from cache.

**Comment by Stormbow** [comment]
What command are you attempting?

**Comment by Stormbow** [comment]
Change line 121 to:

```
    inheritance: []
```

**Comment by sharpshooter037** [comment]
i got some news i get this when i log on and more so much doesen't fit on consle

https://pastebin.com/ignd2zK5

startp log: https://pastebin.com/sHkxveF7

plugins:
![plugins](https://cloud.githubusercontent.com/assets/28761395/26372895/5f0c77a2-3ff7-11e7-86aa-71714102e705.jpg)

thats all i can help with my internet is going down soon for change but thats all i can help with sry.

**Comment by Stormbow** [comment]
Change your owner group to this:
```
  Owner:
    options:
      prefix: '&f[&4OWNER&f] '
      default: false
    inheritance: []
    permissions:
    - '*'
```

and then type this into the console:
```
    pex user sharp_shooter037 add permissions.*
```

This will give the owner group _every_ permission on the server, and give you— directly —access to all of the PEX commands.

If you find any permissions you _do not_ want the Owner group to have, negate them _above_ the wildcard like this:
```
  Owner:
    options:
      prefix: '&f[&4OWNER&f] '
      default: false
    inheritance: []
    permissions:
    - -negated.permission.node
    - '*'

```

We put them _above_ the wildcard so they're seen first, by PEX.

**Comment by sharpshooter037** [comment]
Okay Ill try that at some point I'll say if it works

**Comment by Stormbow** [comment]
Right now, with your current file, your Owner group isn't inheriting from anyone, so all he had was PEX commands access.

**Comment by sharpshooter037** [comment]
Okay that makes sense I was using the admin rank for testing

**Comment by Stormbow** [comment]
I advise against giving PEX access to any groups because if someone accidentally or intentionally gets into those groups, they can delete all the groups on the server.  And, if you move yourself to another group to troubleshoot any problems there, you lose access to PEX— so we give ourselves direct access to PEX to help with that.

**Comment by sharpshooter037** [comment]
Okay I'll was going to remove pex access anyway and move it to my player. so what is the pex command node?

**Comment by Stormbow** [comment]
The command `pex user sharp_shooter037 add permissions.*` will give you, directly, access to all of PEX.

The node is `permissions.*`.

**Comment by sharpshooter037** [comment]
Okay thanks again for your help

**Comment by Stormbow** [comment]
You're welcome.  Let me know how it turns out; you can close the ticket if everything's fine.

**Comment by sharpshooter037** [comment]
Oh yeah I forgot to send the results back.

It all works fine again got a working server for my friends to join now 😁

**Comment by Stormbow** [comment]
Thanks. :)

Have fun!
