### ISSUE TITLE
Citizens timing issue

### ISSUE THREAD

**Issue by malonnnn** [PEXPlugins/PermissionsEx#2797]
So the following isn't the fault of PermissionsEx, but it is related.

A plugin is accumulating lots of "fake players" and Server.broadcastMessage() is iterating over them all, and I'm hoping there's a way I can use PEX to investigate the issue because it seems that PEX is in control of what's being iterated over (PEX looks like it overrides PermissibleBase.recalculatePermissions() in its Permissibles and has its own PermissionSubscriptionMap). I am unable to report the issue to the plugin author because I don't know which plugin it's coming from.

I also have an unanswered post on spigotmc.org
https://www.spigotmc.org/threads/lag-when-doing-server-broadcastmessage-how-can-i-tell-whats-causing-it.242634/

For details (and maybe more clarity on how it relates to PEX), you can read this thread here:
http://forum.enginehub.org/threads/lag-from-broadcast.16958/

**What I'm looking for**
Just a way to investigate the issue

**Comment by Stormbow** [comment]
Since this seems to be a programming-based question, I'll have to let @zml2008 answer since I don't handle any PEX programming.

In the meanwhile, here's a post [over here on the Spigot site](https://www.spigotmc.org/wiki/how-to-take-a-timings-report/) about how to do a timings report that may help you figure out what's causing the lag.

**Comment by Stormbow** [comment]
You can also look into something called ["Warm Roast"](https://bukkit.org/threads/warmroast-a-jvm-cpu-sampling-tool-to-figure-out-why-a-mc-server-lags.153336/), which may be able to help you figure out what is going on.   (I don't know how to use this application at all.)

**Comment by malonnnn** [comment]
Okay I did a timings report (it's all that was really needed) and most of the lag appears to come from Citizens Templates, which i use very heavily.

I hope this helps. If this is not enough information, I can try Warm Roast

https://timings.aikar.co/?id=95c77400498949c88959f2b558008097

**Comment by Stormbow** [comment]
Since Citizens is causing the lag, you may want to try [their Discussion page](https://www.spigotmc.org/threads/citizens-paid.99505/) to see if anyone knows how to reduce it.  Personally, I don't really know how to read a timings report and never used Citizens extensively— I had 2 statues and a couple handfuls of other characters on my server.

**Comment by malonnnn** [comment]
Yes, the timing reports helped me narrow it down. I did some learning on how timing reports work (super helpful, glad I learned) but the lag spikes are def coming from citizens, so i will continue to work with them unless the situation changes.

thanks!

**Comment by Stormbow** [comment]
You're welcome.  Good luck and have fun!
