### ISSUE TITLE
Rank Up

### ISSUE THREAD

**Issue by ArhamR** [PEXPlugins/PermissionsEx#2800]
Hi, I need help with pex, Is there a way to set up ranks so that when the user has played on the server for a particular amount of time then they get the reward for example when someone plays for 12Hours they get a rank then if the play for 24 hours then they get a new rank??, If So how can I do it

**Comment by Stormbow** [comment]
What you're looking for is called [AutoRank](https://www.spigotmc.org/resources/autorank.3239/).

Instructions for setting it up can be found on the above page.

Good luck and have fun!

**Comment by ArhamR** [comment]
Thank You

**Comment by Stormbow** [comment]
You're welcome. :)  Have fun!

**Comment by ArhamR** [comment]
also I am using Permsex to do the ranking stuff so will I use the group name or the prefix for the group and will I edit simple config or advanced config I edited simple config and put in the rank prefix did I do it correctly or wrong

**Comment by Stormbow** [comment]
After you have read _**all**_ of the [documentation for AutoRank](https://github.com/Staartvin/Autorank-2/wiki), you can decide what config to use and how you want people to be able to promote themselves.  It is a fairly complex plugin, capable of offering a very large variety of ways people can rank up, so be sure to read everything on the page above, and the links on the right side to the permissions and commands.

**Comment by Stormbow** [comment]
The prefix/suffix being displayed in-game is handled by a chat management plugin, not PermissionsEx or AutoRank.  Since most people are running [Spigot servers](https://www.spigotmc.org/), and using [EssentialsX](https://www.spigotmc.org/resources/essentialsx.9089/) for the basic commands, they also use [EssentialsXChat](http://ci.drtshock.net/job/essentialsx/) (+ [Vault](http://dev.bukkit.org/bukkit-plugins/vault/)) to get prefixes displayed in-game.
