### ISSUE TITLE
PLEASE HELP [Prefixes Broken]

### ISSUE THREAD

**Issue by broodjie** [PEXPlugins/PermissionsEx#2805]
I have looked on every forum tried every chat manager plugin please can someone help me with Pex prefixes When I use essentials chat it doesn't work or with chat EX, my prefixes did work however with group manager and essentials chat but I want to use Pex please can someone tell me if it is my config or maybe my version is wrong I don't know Here is the information I can offer I have essentialsX chat installed from what I know there is nothing wrong with my config Would be So happy if I can fix this problem.

https://pastebin.com/hb0FGKKD (it is just default config because I tried other configs and they didn't work)

**Comment by Stormbow** [comment]
First and foremost, it's important to distinguish between "EssentialsChat" and "EssentialsXChat" because "Essentials" was discontinued at Minecraft 1.8 (meaning it— and "EssentialsChat" —won't work in any later versions) and "EssentialsXChat" was created for Spigot and more recent versions of Minecraft.

For both versions of this particular chat management plugin, you'll want to compare your Essentials\config.yml file to [this excerpt of the file](https://pastebin.com/eHCCcNuY) that uses the correct settings to get prefixes/suffixes displayed in-game.

**Comment by broodjie** [comment]
Thanks But I do have vault and essentials Xchat installed because essentials doesn't work for me Also I have seen this excerpt before in one of the other forums I tried the config but I am not sure how to use the group formatting part 2 is this all I need to do to fix my prefixes please explain what this does or if it will help.

**Comment by Stormbow** [comment]
Show me your permissions.yml file and I can customize your Essentials\config.yml file (in the original post in this ticket) to give you the prefixes/suffixes in-game.

You can read about Essentials Chat Formatting [right here](http://wiki.mc-ess.net/wiki/Chat_Formatting).

**Comment by Stormbow** [comment]
No reply in 10 days.  Ticket closed.
