### ISSUE TITLE
I don't know what happened!

### ISSUE THREAD

**Issue by ICB2005** [PEXPlugins/PermissionsEx#2806]
https://gyazo.com/a3f59682acd35dfaf037bfa470fa7e0e
I am having a problem with presumably Pex but i don't know.
I removed factions because I have been having problems with the prefixes and suffixes and now it says {prefix} Name {suffix} when you chat do you know what plugin it is and how to fix it.

Plugins:
https://gyazo.com/e0d2ce864e85f71205db13dbeac30915

Fixed it if you are having problems too and you are you essentialschat then set change-displayname to true.

**Comment by Stormbow** [comment]
The correct configuration of EssentialsChat and EssentialsXChat can be found [right here](https://pastebin.com/eHCCcNuY).  (This is just the part that relates to prefixes and suffixes.  Make your full-sized file look similar to this example, in the corresponding places.  Don't delete everything out of your file and paste this excerpt into your file.)

Since you're using Multiverse, you have to look inside that plugin's config file to disable the prefix/suffix display so EssentialsChat/EssentialsXChat can handle your chat management and display the prefixes/suffixes.

Also, you can't use GroupManager and PermissionsEx.  They're both permissions management plugins and you'll be wasting a lot of time setting up and using both at the same time— if they work together at all.

**Comment by Stormbow** [comment]
No reply in 10 days.  Ticket closed.
