### ISSUE TITLE
PEX error: syntax incorrect

### ISSUE THREAD

**Issue by albyme** [PEXPlugins/PermissionsEx#2809]
Hi,
I'm having this problem repeatedley with PEX:

**] Edit by Stormbow: Removed monstrous wall of formatting bugged text. [**

I have the permissions.yml file here:
[https://drive.google.com/open?id=0B-SJAxZgkbfXaDBDTWVEazBJa28](url)

**Comment by Stormbow** [comment]
Your permissions.yml file was kind of a mess, but I don't have anything better to be doing at the moment, so I fixed everything in your file for you:  [https://pastebin.com/6AuPBmEz](https://pastebin.com/6AuPBmEz).

**Comment by Stormbow** [comment]
Your permissions.yml file was kind of a mess, and I don't have anything better to be doing at the moment, so I fixed everything in your file for you:  [https://pastebin.com/6AuPBmEz](https://pastebin.com/6AuPBmEz).

Test this out and see how everything works.

**NOTE:**  I changed "Co-Owner" to "CoOwner" because "Co-Owner" won't be recognized as a group on the server for some plugins.

And, as a nice little "screw you" to your "cheater" group, I removed _all_ of their permissions, so they can stand there, do nothing, and not even talk (in most cases).  LOL  (You can, of course, delete those 2 lines— 158 and 159 —if you don't like the idea.)

**Comment by Stormbow** [comment]
Side note:  The `option:` setting `build: false` / `build: true` only applies to servers using the EssentialsXAntiBuild or EssentialsAntiBuild plugin.

**Comment by albyme** [comment]
ok thank you very much!

**Comment by Stormbow** [comment]
You're welcome. :-)  Let me know if you run into any other problems.  (You can reply to this ticket, even though it's closed.)
