### ISSUE TITLE
PermissionsEx invlaid plugin.yml URGENT

### ISSUE THREAD

**Issue by Vladipiggy** [PEXPlugins/PermissionsEx#2823]
My plugin is messed up. It runs the first time but it says I don't have permission to use it. So then now that it created the files I stop my server, because it is on linux I cannot access the files without. I put the files in and restart and bam its now an unknown command. I have reinstalled like 5 different versions. I am competely stuck here. I have been trying for days now. I just need some help. I have been posting around to no avail. [update] Didnt work

**Comment by Vladipiggy** [comment]
That didn't work ugh.

**Comment by Stormbow** [comment]
Unfortunately, I can't really help you with anything related to Linux since I've never used it myself.

Let me tell you what I can help with, though, and maybe some of this will be pertinent and helpful.

First and foremost, the "invalid plugin.yml" error usually means that your download was corrupted or came from some unofficial source/website; re-downloading PEX from [this official download page](url) will usually correct that error.

As for the permissions...  After you've gotten past the "invalid plugin.yml" error, PEX will probably generate a PermissionsEx folder (inside the server's "plugins" folder) and a permissions.yml file inside that.  That file will be where you define all of your groups and the permissions they're allowed.

As far as accessing PEX permissions, I typically recommend every server owner give those permissions directly to themselves and never to a group because any unsavory person that gets into the group can literally delete all the users and groups from the server, give themselves permissions they shouldn't have, and even ban everyone.  Use the command `pex user Vladpiggy add permissions.*` in the server console to give all of the PEX commands to yourself.  (Use your Minecraft name, of course.)

With the plugin.yml and PEX access problems potentially solved now, we look at the "unknown command" issue.  What command, exactly, were you typing and where were you typing it?  (In-game or in the console?)

**Comment by Stormbow** [comment]
Close enough to a week with no response.  Case closed, I guess.
