### ISSUE TITLE
Could you add last version of PEX on maven repository ?

### ISSUE THREAD

**Issue by fabien91** [PEXPlugins/PermissionsEx#2826]
Hello,

Could you add last version of PEX on maven repository please because, the version "1.23.2-SNAPSHOT" won't compile with the integrated bukkit updater :

"Failed to collect dependencies at ru.tehkode:PermissionsEx:jar:1.23.2-SNAPSHOT -> net.gravitydevelopment.updater:updater:jar:LATEST -> org.bukkit:bukkit:jar:1.6.4-R2.0: Failed to read artifact descriptor for org.bukkit:bukkit:jar:1.6.4-R2.0: Could not transfer artifact org.bukkit:bukkit:pom:1.6.4-R2.0 from/to bukkit-repo (http://repo.bukkit.org/content/groups/public): repo.bukkit.org: Unknown host repo.bukkit.org -> [Help 1]"

This is normal because bukkit repo is not available anymore.

Thank you,
Fabien

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
