### ISSUE TITLE
Not enough permissions

### ISSUE THREAD

**Issue by Elementkingaming** [PEXPlugins/PermissionsEx#2833]
Hey, im using PermissionsEx 1.23.4 (the latest i asume) and when i typed /pex to get some command help it just told me what version it is, so i had a look on the web at the commands and then after i typed in another command it said "sorry, you dont have enough permissions." I am set as an owner in my world/server but i cant use most my Commands. What can i do??

**Comment by Stormbow** [comment]
Be sure to give yourself direct access to PEX commands by typing `pex user Stormbow add permissions.*` into the console.  (But use your Minecraft name, of course.)

If you still have problems accessing PEX commands after that, post your permissions.yml file on [Pastebin](http://pastebin.com) leave the link in this thread, and I'll take a look at it for you.

**Comment by Elementkingaming** [comment]
I am now able to use PEX (Thank god!) But my other commands on my server still wont work, there basically doing the same thing as PEX did before, and my Username still has me under [MEMBER] not [OWNER]

https://pastebin.com/JA3B1Y63 - My Permissions.yml File

**Comment by Stormbow** [comment]
One big thing to know first:

Your "Guest" group must have an `inheritance:` section, as of Minecraft 1.9, and you can see how to give a group an "empty" inheritance— since they don't actually inherit from any other groups —on line 19 of [this example](https://pastebin.com/8ZSHxauG).  Missing an `inheritance:` section in any group can cause PEX to malfunction.

After that, your file is slightly out of order.  Move line 111— `schema-version: 1` —up to line 98; it should come before the `users:` section.

Next, we need to clean up your user data.  Leave the server, delete everything after `users:` in the file— remembering that `schema-version: 1` should now be above the `users:` line— then save the file, type `pex reload` into the console, re-join the server, and type `pex user ElementK1ng add permissions.*` into the console again.

If you still have problems with commands— which command(s), _exactly_ are you attempting to use?

----

On an unrelated side note, line 81 of your file gives the "Owner" group absolutely _every_ permission on the server.  When PEX reads the file from top to bottom, it will find that line, know that "Owner" gets _everything_, grant access to _everything_, and never read lines 82 through 92.  When using the "global wildcard", `- '*'`, you'll only need to _negate_ any permission nodes the group _does not_ get/want, and that will be done _above_ the global wildcard, as you see in [this example](https://pastebin.com/8ZSHxauG).  And since the "Owner" group is using the global wildcard, you can also give it one of those "empty" inheritance sections, like I mentioned on line 19 of my example file.

**Comment by Stormbow** [comment]
Also, did you mean that you're displaying `[Member]` and not `[Owner]` in chat?

**Comment by Elementkingaming** [comment]
Yea, i am branded as "[MEMBER] ElementK1ng" not "[OWNER] ElementK1ng" also what i did is deleted the server files and the re-created it, that way i could get these first problems out the way.

https://pastebin.com/5BEXpZr9

And now i did what you said, reloaded it, moved line 112 and added inheritance to line 28. now when i get in i can use all the commands, but my tags member and when i use the console to promote me (to get me to owner) it says "user are not in this ladder".

What else can i do??

**Comment by Elementkingaming** [comment]
https://pastebin.com/ujTahBAS (new file out come)

**Comment by Stormbow** [comment]
For some unknown reason, your `users:` section is still a train wreck.
```
users:
  minecraftnamehere:
    group:
    - Owner
    permissions:
    - permissions.*
    options:
      name: MINECRAFTNAMEHERE
  dceff7b9-3582-4850-ac32-9c13936d752f:
    permissions:
    - permissions.*
    - permissions
    options:
 
      name: ElementK1ng
```

Notice the double permission node and the blank line?  Those need to be deleted.

Also, in the 'new file', you're not in the "Owner" group, so of course you show "[Member]".  ;-)  Only "minecraftnamehere" is a member of "Owner", and that user's data should be deleted entirely.

**Comment by Elementkingaming** [comment]
schema-version: 1
users:
  ElementK1ng:
    group:
    - Owner
    permissions:
    - permissions.*

Like that?

**Comment by Stormbow** [comment]
> when i use the console to promote me (to get me to owner) it says "user are not in this ladder".

You're using the wrong command. :-)  You're using `pex promote ElementK1ng` when you haven't actually established any rank-ladders or rank values.  You can see those in [my example file](https://pastebin.com/8ZSHxauG).  The correct _promote_ command, with no ladders or rank values defined, would be `pex promote ElementK1ng default` (I believe).  A more accurate and specific way to get someone into a single group would be `pex user ElementK1ng group set Owner`.

**Comment by Stormbow** [comment]
Like this:
```
users:
  dceff7b9-3582-4850-ac32-9c13936d752f:
    permissions:
    - permissions.*
    options:
       name: ElementK1ng
```

**Comment by Elementkingaming** [comment]
AH! ok,

https://pastebin.com/1KcTAMMP

so like that? i looked back at your example and mine and tried that. now if thats correct then how has my "User are not in this ladder" back?

Thank you alot for all this help btw

**Comment by Stormbow** [comment]
> so like that?

Nope.  Line 104 is indented too far.  The user's still in the `default: true` group (Guest, with a [Member] prefix), since the syntax/formatting of this data was wrong.

> Thank you alot for all this help btw

You're welcome. :-)  This is what @zml2008 (the PEX programmer) added me to the team for.  :-D

**Comment by Elementkingaming** [comment]
https://pastebin.com/gicETY97

is that far in enough?

**Comment by Stormbow** [comment]
Copy this and paste it into your file:
```
users:
  dceff7b9-3582-4850-ac32-9c13936d752f:
    options:
      name: ElementK1ng
    group:
    - Owner
    permissions:
    - permissions.*
```
This has the proper formatting.

**Comment by Elementkingaming** [comment]
OMG THANK YOU Setting it to Owner has settled my other plugin problems, THANK YOU SO MUCH!!!

**Comment by Stormbow** [comment]
You're welcome. :-)  Have fun, and don't hesitate to come on back if you run into any other PEX problems.
