### ISSUE TITLE
[Mc 1.8.8][PEX 1.23.3] SQL error

### ISSUE THREAD

**Issue by carefree0216** [PEXPlugins/PermissionsEx#2839]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/ee7f2d8b7e122fb49f99)

**Comment by Stormbow** [comment]
Do you have the same error when using [PEX 1.23.4](https://dev.bukkit.org/projects/permissionsex/files)?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
