### ISSUE TITLE
Feature Request: Rank-Ladder Hopping

### ISSUE THREAD

**Issue by August-Earth** [PEXPlugins/PermissionsEx#2841]
I'm wondering whether or not there is potential for PEX to forcefully move a user into a **different** rank-ladder to the one they are currently in, with a specific command. (I really do hope this does not already exist, otherwise I'm going to look like a bit of a doofus). 

I'll provide a bit of context..

[This is my example permissions file](https://pastebin.com/8RFpDqQZ)

Notably, there are 4 separate rank-ladders here; Default, PathA, PathB, and PathC.
All new users are defaulted to the Default rank and rank-ladder. However, I wish for users to decide which Path they would like to take, initially - and then continue on that chosen Path.

As we know, a simple **/pex promote user ladder** or **/pex user group set** would not suffice as both rely on the user being already allocated to that ladder.

Again, I apologise if I have overlooked an existing function. However, if I haven't.. I look forward to potential discussion.

**Comment by Stormbow** [comment]
I'm hoping I understand what you're asking about...  Let's start from the beginning:

When a user joins such a server, they begin as a member of "Default", according to your example file.

From there, you would need to— as you said —`/pex user group set` the user into PathA, PathB, or PathC.  If a player were part of multiple groups in the path— such as PathA1 (a regular player), PathA3 (a chat moderator), and PathA5 (a YouTuber) —you would use the command  `/pex user group add groupname` to get them into all 3 groups.

Once they were in a PathA, for example, you could use `/pex promote user ladder` to move them up that Path to PathA1, PathA2, PathA3, etc. and `/pex promote user ladder` to move them down that Path— PathA3 to PathA2 to PathA1.  (If they're a member of multiple groups, this command may make things tricky to keep straight.)

If someone was in PathA2, and wanted to _move_ to PathB, you would use `/pex user group set` to remove the user from any and all groups there were associated with along PathA— because a user could _potentially_ be in groups PathA1 (a regular player), PathA3 (a chat moderator), and PathA5 (a YouTuber) —into the new group, and keep in mind the new group can be at any level in any Path.  On a similar note, if you're using the Paths as ladders for teams or cities, and someone earns the rank of being a Moderator for one team/city (say, PathA9) and you wanted them to remain a Moderator on the server, but attach them to a new team/city, you could `/pex user group set` the user into PathB9, the group which is a Moderator for the other team/city.

After that _move_, you could then again use `/pex promote user ladder` to move the user up and down the new Path.

Does that answer what you're looking for?

**Comment by Stormbow** [comment]
Significant editing done to my previous comment.  Be sure to read [the post](https://github.com/PEXPlugins/PermissionsEx/issues/2841#issuecomment-310089369) as it will be different than what you received in email.

**Comment by August-Earth** [comment]
Mate.. somewhat of an embarrassing oversight on my behalf.

For some reason, even though I thought I had, I had not properly utilized /pex promote user **ladder**.

So thank you for that.. and, you've also inadvertently answered further questions I know I would have asked further on.

Really appreciate your quick response, thank you.

**Comment by Stormbow** [comment]
My pleasure to be of assistance.  :-)

Don't hesitate to come on back if you have any other questions.  I can answer just about everything that doesn't have to do with PEX 2.x, programming, or SQL.  (I have to leave all those for the PEX programmer, @zml2008.)
