### ISSUE TITLE
yml files not generating?

### ISSUE THREAD

**Issue by Galadriel1640** [PEXPlugins/PermissionsEx#2844]
Hello!  I am using the newest version of PEX for sponge and have been trying to figure out how to make groups using config files rather than commands, but the only two files that generated were permissionsex.conf and permissions.json; I am basically just unsure if I need to create my own or not, and if I do, where to put it?  The json file technically has my name in it along with the groups I created by using the provided tutorials, but it seems extremely different than the config tutorials provided, but it seemed messy and only some of the permission nodes appeared properly.  Would I just need to make a yml file and specify it in the backends section of the permissionsex.conf?

**Comment by Stormbow** [comment]
Unfortunately for you, since PEX 2.x hasn't been officially released yet, I don't have any examples to base your files on, like I have for PEX 1.x versions.

You'll need @zml2008 to reply to this ticket, if there are any available resources.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
