### ISSUE TITLE
PermissionsEx Disables on Restart

### ISSUE THREAD

**Issue by 1mccreeper** [PEXPlugins/PermissionsEx#2845]
I have permissions ex on the server I am developing. It works we can add prefixes permissions and what not. The only problem is when the server restarts, Pex no longer exists in /plugins nor does any of its commands exist. I did some testing to see if tinkering with configs was breaking it but I found that when i installed it started the server it worked. but once i shutdown the server then started it back up Pex no longer worked. 
If anyone could help me i would appreciate it.

(When we restart the server, the Server Owner says he is Clicking Stop then after its stopped completely he clicks Start)

**Comment by 1mccreeper** [comment]
Plugins:
Announcer
antimobspawn
autosaveWorld
Buycraft
ChestCommands
Combatlog
Coreprotect 2
Crackshot
customjoinitems
easysetspawn (essentials spawn error fix)
Enchantactivepack
enchantmentapi
enchantpassivepack
enchantpotionpack
enchanttrappack
Enjinminecraftplugin
essentials - antibuild chat geoip protect spawn XMPP
Firstjoinplus
firstspawn
forcefield
GAListener
HeroBounty
JNoDrops
JoinCommands
JoinDate
Killstats
Kingkits
Kitessentials
MaxBans
Multieverse-Core
MyItems
MyMOTD
NoCheatPlus
NoMoreHunger
PermissionsEx-1.23.3
PerWorldPlugins
PingPlayer
PlayerTracker
RandomWarp
RegionPreserve
Serversigns
ServerTokens
SignEdit
SimpleRename
Torture
VoidGenerator
Votifier
VPNGuard
WGCustomflags
WGEssentialFlags
WGRegionEffects
Worldedit
worldGuard
Forgot to add the list of plugins so here it is.

**Comment by Stormbow** [comment]
Ok, I'm going to start from the very beginning of the troubleshooting process:

What version of Minecraft are you running?

What version of PEX are you using?  (Copy the entire permissions.yml file to [Pastebin](http://pastebin.com) for me to examine.)

Are there any errors in the server console when the server is first started?  (Copy the entire server startup log to [Pastebin](http://pastebin.com) for me to examine— everything from the moment the server starts until a message similar to "Done!" is posted on the console.)

Are any other plugins removed from the plugins list in-game after the restart?

**Comment by Stormbow** [comment]
On an unrelated sidenote, it looks like you're using 3 plugins for kits.  Essentials (and EssentialsX) are both phenomenal at creating starter/first join kits, regular kits, and even kits containing various potions and extensively specialized items with custom lore.descriptions, item names, enchantments, damage levels, and more.  You can even include an amazing server rulebook in the kit that Essentials/EssentialsX can give your brand new players.

Take a look at my ['Newbie'](https://pastebin.com/4gfNncxq) and ['Stormbow'](https://pastebin.com/E4Y7AXRW) kits as an example of what you can do.  (And only users/groups with `essentials.kits.newbie`  and `essentials.kits.Stormbow` would have access to these kits, respectively.  The book for the newbie kit is defined in the book.txt file, for Essentials/EssentialsX.  I can't share that example since it's proprietary to my server.)

**Comment by 1mccreeper** [comment]
I dont have access to console because the owner doesn't want to give me his personal info so i can't give you that. The permissions.yml file is default as it shows. and I can't remove the KitEssentials because thats the one he wants to use because it has a kits GUI Selection 
`groups:
  default:
    options:
      default: true
    permissions:
    - modifyworld.*
schema-version: 1
`

**Comment by Stormbow** [comment]
KitEssentials hasn't been updated since Minecraft 1.7.4, so unless he's attempting to run a really outdated server, that plugin wouldn't work for him anyway.

**Comment by 1mccreeper** [comment]
the server is 1.8.9 and still kitessentials works but i have to wait for him to get on to start the server then i will be able to tell you if this worked. Thank you for the help!

**Comment by Stormbow** [comment]
You're welcome.  I'll close the ticket for now and you can re-open it if you guys still need help.
