### ISSUE TITLE
Help with PEX and MYSQL

### ISSUE THREAD

**Issue by theISSUEfinder3** [PEXPlugins/PermissionsEx#2846]
hello guys, i need help with setting up a mysql.
i run newest version of pex
i have the sql on XAMPP
i have made a user:

Username : Frej
Host : localhost
Password : ***

and  it have all priviliges
and i made a database called frej

But when i set it up to pex it is not working? can u please help me:
PEX config:
```
multiserver:
  use-netevents: true
permissions:
  debug: false
  allowOps: true
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: sql
  informplayers:
    changes: false
  basedir: plugins/PermissionsEx
  backends:
    file:
      type: file
      file: permissions.yml
    sql:
      type: sql
      uri: mysql://localhost/frej
      user: Frej
      password: ***
updater: true
alwaysUpdate: false

```
and here is the console output:
https://pastebin.com/xPcDAcgd

**Comment by Stormbow** [comment]
Unfortunately, I have to leave SQL issues for @zml2008 to respond to since I haven't used SQL in 5 or 6 years and have forgotten pretty much everything I ever knew about it.  Sorry.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
