### ISSUE TITLE
/promote doesnt work /pex promote does

### ISSUE THREAD

**Issue by GoodOldJack12** [PEXPlugins/PermissionsEx#2852]
Simple as that. the authorized ranks have the ```permissions.user.promote.default``` node,
but ```/promote``` gives a 'you do not have permission' error. I might be missing something but well.

**Comment by Stormbow** [comment]
`/promote' is not a [PEX Command](https://pastebin.com/Kd269wd7).  `/pex promote <user> [ladder]` and `/pex demote <user> [ladder]` are.  :-)

**Comment by GoodOldJack12** [comment]
I figured as much. Yet /promote does use pex. so what permission node would I need to grant? I can not find it anywhere

**Comment by Stormbow** [comment]
Which plugin is giving you a `/promote` command?  Their documentation should give you the correct permission nodes.

Otherwise, you can use [PEX Debug Mode](https://pastebin.com/vhcWR2yK) to find out if such a permission node exists in any of the plugins you're using.  (And if you have any trouble interpreting the Debug Mode output in the console, Pastebin it here and I'll help ya out.)

**Comment by GoodOldJack12** [comment]
apparently it's ```permissions.user.rank.promote```. strange. anyways, thanks for the really fast reply!

**Comment by Stormbow** [comment]
Ahhh!  There ya go— an alias.  :-)

**Comment by Stormbow** [comment]
For what it's worth, I did an extensive write-up on the /promote command back around Minecraft 1.7.2 in the [PEX Wiki](https://github.com/PEXPlugins/PermissionsEx/wiki)— [Ranks-(Promotion-and-Demotion)](https://github.com/PEXPlugins/PermissionsEx/wiki/Ranks-(Promotion-and-Demotion)) —and somewhere around 1.8 all of that documentation was deleted by one of the original authors/members of the project so I was under the impression it was removed since PEX doesn't print that command in the commands list in-game/in-console anymore.

Thanks for the ticket!  I learned something new, more or less. :-)
