### ISSUE TITLE
Event Handling for Developers

### ISSUE THREAD

**Issue by kNoAPP** [PEXPlugins/PermissionsEx#2856]
It would be super awesome if you added EventHandlers for developers. Nothing too fancy, really all I am looking for at this second is:

PlayerRankUpdateEvent
  -When a Player's group/permission is updated.

**Comment by zml2008** [comment]
Which version of PEX are you working with? PEX 1 has events already, and PEX 2 doesn't exactly have a public API yet.

**Comment by kNoAPP** [comment]
I am running PEX 1. I didn't see any EventHandlers in the Wiki so I assumed there were none. My bad if that's the case!

**Comment by zml2008** [comment]
Yeah, the wiki is mostly targeted towards users, since 98% of the integrations people want to do with PEX are probably better done with Vault or Bukkit's permissions API. If you need to listen to changes to a PermissionsEntity, the event you need to work with is https://github.com/PEXPlugins/PermissionsEx/blob/1.23.x/src/main/java/ru/tehkode/permissions/events/PermissionEntityEvent.java -- it works like any other Bukkit event.

**Comment by kNoAPP** [comment]
Awesome sauce! Thanks for the rapid reply.
