### ISSUE TITLE
Still need help... so confusing

### ISSUE THREAD

**Issue by QueenKisaki** [PEXPlugins/PermissionsEx#2868]
Hi again, I'm having a problem on how to promote within the Member ladder and also randomly add users to the Guild ladder. My players rank up within the Member ladder, there's no problems there. The problem comes when they choose their guild and are added into a guild ladder, it removes them completely from the ranking ladder (Member). Here is my perms: https://pastebin.com/PP16mVe8

I am not sure on the commands to use when doing this correctly. When they complete quests for ranks, I use the command /pex promote <user> Member and it works fine. But later on they have to choose a guild and I use the command: /pex group (Fire,Water,Earth, or Air) user add <user> which then takes them out of the Member ladder completely. Can you tell me what I'm doing wrong please, this is still terribly confusing. They do not ever rank up within the guild ladder (I even tried not having a ladder for guilds)

**Comment by Stormbow** [comment]
`pex user Stormbow group add Air` would be the correct command to add Stormbow to the Air Guild.

Then you'd want to try— because I've never had users in more than one ladder myself —the `/pex promote <user> [ladder]` command to move them up the ladder and `/pex demote <user> [ladder]` to move them down the ladder.

----

On an unrelated sidenote, you don't need to color and underline every letter of the Owner prefix.  `prefix: '&d&lO&d&lw&d&ln&d&le&d&lr '` is literally just `prefix: '&d&lOwner '`.

Also, many special characters in prefixes— like line 152's `♔` —are not visible in-game.  (It comes up as a question mark in Notepad, {Notepad++}, and on my test server.)  If you've discovered how to display these in-game, I'd love to hear it so I can share the info with others.

**Comment by QueenKisaki** [comment]
Thank you I will try that command instead. Its only the Member ladder that gets promoted/demoted. As for the Master rank, yea it comes up in chat just like that with the icon, I literally just copy and pasted from a site with the icon:
![prefix](https://user-images.githubusercontent.com/22261674/28190253-9e4a4dc0-67ef-11e7-8745-b6a2146f0538.png)

**Comment by Stormbow** [comment]
Interesting.  I wonder why that works for you and not for me...  (I copied and pasted too.)  Which site did you use?

**Comment by QueenKisaki** [comment]
I just tried the hearts on this page too and it worked: https://tutorialzine.com/2014/12/you-dont-need-icons-here-are-100-unicode-symbols-that-you-can-use

I coped the icon, not the code :) I use venturechat now but it even worked when I was using townychat and essentials chat, too.

**Comment by Stormbow** [comment]
Ahhhh!  I forgot to change `File > Encoding > UTF-8` when I reinstalled Notepad++ on this computer.

Thanks for the page link, that helped.  :-)

**Comment by Stormbow** [comment]
Let me know how the commands work out.  :-)

**Comment by QueenKisaki** [comment]
Yes thank you so much it works perfectly now :D

**Comment by Stormbow** [comment]
You're welcome. :-)  Have fun!
