### ISSUE TITLE
Minecraft PemissionsEX Not Working

### ISSUE THREAD

**Issue by TexorYT** [PEXPlugins/PermissionsEx#2881]
I Got A Few plugins a while ago, and i thought it all went good. but my pex turned on me.
when i type /pl everything fine but pex. (in red)
i cant do any "//" commands
cant even do /help!
i used yaml thing and didnt work.
i dont even have acces to /plugins | /pl
my server is 1.12

plugins>> https://gyazo.com/26be196de6607be0cba0f61a9b007d27
permissionex folder >> https://gyazo.com/f08d17fd4fcefde9873716a6dff119e9
permissions.yml >> https://pastebin.com/ZHM7WrXf

pls help

(it said in my console to come here and paste the issue)

**Comment by Stormbow** [comment]
Try [this paste](https://pastebin.com/Gkh3hYVX) as your file.  I corrected multiple permission node syntax issues for you, added the required inheritance structure, and condensed your permissions down to unique nodes.

As each group inherits from the previous group, they gain all the nodes of the previous group, so there's no need to replicate all the nodes— like `essentials.msg` in each group.  Since Admin inherits from MVP, they get all the MVP permissions, VIP permissions, and default permissions— because all of the groups inherit the nodes from the previous group too.

----

One thing you will need to work on is ensuring that all of your permission nodes are real permission nodes.  For example, you had `essentials.essentials` in one group, and that node is not on the [Essentials Permission Nodes List](http://wiki.ess3.net/wiki/Command_Reference/Perm).  (I removed that one node, and I didn't remove any other nodes that were 'fake', so you can get some experience with the permission node list.)

I also added `essentials.kit` to the default group, so everyone would get access to the /kit command.  Be sure you get all of the prerequisite permission nodes for your groups as you look through the above list.

----

Let me know if you run into more problems.  If everything's fine, you can close the ticket below.  :-)

**Comment by Stormbow** [comment]
If you would like to see a more complete example of a permissions.yml file, you can check out [this link](https://pastebin.com/8ZSHxauG).

**Comment by TexorYT** [comment]
*Sigh*

>> https://gyazo.com/ef6995621acbfeadda58c3a1cfca741a

**Comment by Stormbow** [comment]
OK, copy your entire console log from the moment the server starts until text stops printing to the console, and pastebin it.

**Comment by TexorYT** [comment]
sooo, when i run the server, go into /texcraft/log/latest.txt?

**Comment by Stormbow** [comment]
Yep.

**Comment by TexorYT** [comment]
Here. i think i did it right

>> https://pastebin.com/avHs8NNr

**Comment by TexorYT** [comment]
did i do it right?

**Comment by Stormbow** [comment]
OK, here's what the errors mean:

• NoSwear.jar needs to be downloaded again because it was corrupted when downloaded the first time.

• There's a syntax error in the \Announcer\config.yml file.

• Line 320-338: AnimatedScoreboard has not been properly programmed for 1.12 servers.  It's attempting to do something (in a bad way) which PermissionsEx does (in a better way).  The author is aware of the issue and attempting to fix it.  You will need to remove the plugin from your server until it's fixed.

• LibDisguises is messed up in ways that I don't quite understand.  Basically, I think it's looking for information to let people disguise themselves as stuff, but can't find the information needed to do so.  You will have to talk to that plugin's team to find out what's gone wrong.

• ChestShop wants to use sqlite and you haven't configured ChestShop correctly.

• CratesPlus is outdated.  You'll need to get a version of the plugin which is for 1.12 servers.  (You're using a 1.11.2 version.)

• WarpSigns looks like it's for Minecraft 1.8; I'd delete this plugin entirely anyway since Essentials can handle your [warp signs](http://wiki.mc-ess.net/wiki/Sign_Tutorial#Warp_Sign).

• ChatControl also appears to be outdated, not for 1.12 servers.

♦ ChatManager typically (99% of the time) is not supported by PermissionsEx.  Test the plugin you have thoroughly to see if you've found one of the dozens of "ChatManager"-named plugins which is compatible with PEX.

**Comment by Stormbow** [comment]
After you get all of these issues addressed, test the server and let me know if you need additional help.

**Note:**  Removing AnimatedScoreboard is all that's _absolutely_ required, to get PEX to stop being red in-game.

**Comment by TexorYT** [comment]
im srry for troubling you, but nope. still red.

**Comment by TexorYT** [comment]
wanna join my server?

**Comment by TexorYT** [comment]
hello? still there?

**Comment by Stormbow** [comment]
> im srry for troubling you, but nope. still red.

No need to be sorry.  I'm here to help. :)

> wanna join my server?

I usually only join servers if I have to see something from in-game.

> hello? still there?

Sorry, we all have to sleep sometime.  ;-)

**Comment by TexorYT** [comment]
haha but you know how to fix this? still red

**Comment by Stormbow** [comment]
Show me the most recent console log and permissions.yml file.

Be sure you're _not_ using the permissions.yml file which is in the server's root directory (with a file called server.properties) because that file should be completely blank.  The file you should be editing is the permissions.yml file inside the plugins > PermissionsEx folder.

**Comment by TexorYT** [comment]
here>> https://pastebin.com/u8Xdh3UD

i also tried some editing. which one do i use?

Number 1 (original)>> https://pastebin.com/PRvqPWWh

Number 2 (after editing)>> https://pastebin.com/xkuhp2zc

**Comment by Stormbow** [comment]
BuildTools.jar is not a plugin.  It's what's used to make a Spigot.jar file.

**Comment by TexorYT** [comment]
thanks so much. you have discord?

**Comment by Stormbow** [comment]
Yep.  I'm on https://discord.gg/KQgWc68 for PEX Help.

**Comment by Stormbow** [comment]
I'll be back in another couple hours.

**Comment by Stormbow** [comment]
So is everything done in this ticket?

**Comment by TexorYT** [comment]
Ya I guess. Thx bro

**Comment by Stormbow** [comment]
Excellent.  You're welcome.  :-)  Have fun!

**Comment by TexorYT** [comment]
https://github.com/PEXPlugins/PermissionsEx/issues/2899
