### ISSUE TITLE
Pex don't sync ranks only permissions.

### ISSUE THREAD

**Issue by ToFastForYou** [PEXPlugins/PermissionsEx#2885]
I have a problem with pex version 1.23
I have connected it with a mysql database but when I change a players rank from the lobby server the rank isn't updated on other servers in the network.

All servers do /pex reload every minute.

**Comment by Stormbow** [comment]
Do you have Netevents installed as well?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
