### ISSUE TITLE
Permissions.yml not working

### ISSUE THREAD

**Issue by Dromdude** [PEXPlugins/PermissionsEx#2891]
I cannot figure out why my permissions ex is not working. After adding some donator ranks to my permissionex.yml i am no longer able to use any pex commands on my server. When i type a command in it gives me no errors or anything. I've read through it like 5 times and do not see any errors or mistakes. Here's my permission file https://pastebin.com/eNegBveR

**Comment by Stormbow** [comment]
Corrected all issues:  https://pastebin.com/DNw1aJih

The way inheritance works, in this corrected paste, is that "Member" is not inheriting from anyone, so they have an "empty" inheritance section (which is required by Minecraft 1.9+).  You then had "Donator" inheriting from "Member", so I removed the duplicate permission nodes— `essentials.help`, `essentials.rules`, and `essentials.motd` because they're all in "Member" and inherited —from the "Donator" group.  Similarly, "VIP" inherits from "Donator", so it gets all of "Donator"'s permissions (which includes all of "Members" permissions), so we list only "Donator" as the inheritance for "VIP".  This same pattern continued through the rest of the file, so I made it a single chain of inheritance up to "Admin", since you wanted everyone to get everything that the previous groups had.  The "Owner" group gets absolutely everything (including nodes you don't know that you don't want it to have yet), so it also gets an "empty" inheritance like the "Member" group had.

**Be Warned:*  Anyone in the "Owner" group can delete all the groups on the server, since they also get access to all the [PermissionsEx Commands](https://pastebin.com/px4CFB2C).  Normally I recommend only giving `permissions.*` to yourself (with `/pex user Stormbow add permissions.*`, using your name instead of mine).  If you want to remove this permission node from your "Owner" group, change the group to look like this:
```
  Owner:
    options:
      prefix: '&6[&4Owner&6]&f '
      default: false
      build: true
    inheritance: []
    permissions:
    - -permissions.*
    - '*'
```

And one final note:  you have a group called "memeber" which I couldn't tell if you wanted that to be some kind of "meme" related group, so I left it in the file.  Someone probably meant to add those to the "Member" group, and just didn't spell it correctly, but I left it in the file and you can correct it as desired.

**Comment by Stormbow** [comment]
Test the above corrected file, and let me know if you have any additional issues you need help with.

**Comment by Dromdude** [comment]
It worked but now i have the issue of names for the donator ranks are not colored and it does not show the prefix's like [Donator] or [Vip] before there names either. It also now says [world] before a persons name now. the ranks themselves work though. i can set a person to a rank and they can use the permissions from that rank.

**Comment by Stormbow** [comment]
Excellent.  We're moving in the right direction.

Next up, you need to configure your chat management plugin.  In this case— EssentialsChat.  Use [this guide](https://pastebin.com/eHCCcNuY) to get the prefixes and suffixes setup.

Also, look in the Multiverse folder and make sure prefixes are disabled in the Multiverse config.yml file.

**Comment by Dromdude** [comment]
I read through the guide twice and i'm having trouble understanding it. I made the chnages that are in the guide and that doesn't seem to have fixed it I also changed the prefixes for multiverse to false but every time i reload the plugin or restart the server it changes it back to true.

**Comment by Stormbow** [comment]
OK, let me see your console log from the moment you start the server until text stops printing to the screen and you see a message similar to "Done!".

**Comment by Stormbow** [comment]
And while you're at it, show me your most recent permissions.yml file and your Essentials config.yml file.

**Comment by Dromdude** [comment]
Essentials config https://pastebin.com/dR9eHNVH
Permission https://pastebin.com/gbMaWVj2

**Comment by Stormbow** [comment]
Corrected Essentials config.yml file: https://pastebin.com/i5WhjpFd

For the best results, be sure to stop the server before replacing your config.yml file with the filed linked above.

**Comment by Dromdude** [comment]
Console https://pastebin.com/rrsSKXuW
i'll check if that config works

**Comment by Stormbow** [comment]
This file should get all the prefixes displayed in-game, then you can work on adding [Color Codes](http://www.minecraftwiki.net/wiki/Classic_server_protocol#Color_Codes) and [Formatting Codes](http://minecraft.gamepedia.com/Formatting_codes) to lines 703-711 of the Essentials config.yml file, and the permissions.yml file.

**Comment by Stormbow** [comment]
The server console looks pretty good.  ChestShop looks like it's outdated or not configured correctly ("you seem to not be using the Xerial SQLite driver.  See ORMLite docs on SQLite: http://ormlite.com/docs/sqlite"), and you're missing the [ProtocolLib plugin](https://www.spigotmc.org/resources/protocollib.1997/) (which is a dependency of the "PAC.jar" plugin.

**Comment by Dromdude** [comment]
Getting closer. But now the donators have a slight issue. they have [member] their names. For examples <[Donator]>Killer[Member] that's what it looks like for all Ranks except Owner

**Comment by Stormbow** [comment]
Yep.  That's because you didn't give the Donator or other groups a suffix, but you did give Member a suffix.

Give Donators and others groups this:
```
      suffix: '&r'
```
That will assign them a blank suffix, removing the Member suffix.

Alternatively, you could delete the line for the Member suffix.

**Comment by Stormbow** [comment]
The `&r` is just a "reset" code, changing the color and formatting back to the default (white, with no underline, bold, etc.).

**Comment by Dromdude** [comment]
Yep Fixed how. Thank you so much for the help!

**Comment by Stormbow** [comment]
You're welcome. :-)  Have fun!
