### ISSUE TITLE
New Spigot update causing Pex to use lots of resources

### ISSUE THREAD

**Issue by AdamTragedy** [PEXPlugins/PermissionsEx#2892]
https://timings.spigotmc.org/?url=giwarifoqi

The newest 1.12 Spigot update as of this morning, is causing issues with numerous plugins. I have attached the timings report showing PEX using a lot of resources.

```
       0.00%	  93.54%	  0.05 s	    46.77 ms	 0.0	       0.0k	    RegexPermissions$EventListener::onPermissionSystemEvent(PermissionSystemEvent)
       0.00%	   3.78%	  0.03 s	     1.89 ms	 0.0	       0.0k	    SuperpermsListener::onPlayerQuit(PlayerQuitEvent)
       0.00%	  53.12%	  0.03 s	    26.56 ms	 0.0	       0.0k	    SuperpermsListener::onSystemEvent(PermissionSystemEvent)
```

**Comment by Stormbow** [comment]
Are there any errors in the server log?

Has spigot been notified of the issue?  (Nothing has changed in PEX 1.23.4, so it doesn't appear to be a PEX issue, at a glance.)

**Comment by Stormbow** [comment]
I honestly don't know much about reading timing reports, but I can't see "PermissionsEx" on [that page](https://timings.spigotmc.org/?url=giwarifoqi).

I do see a lot of plugins, but not one specifically named "PermissionsEx".  >.>

Is "PermissionsEx" actually installed on the server?  (I have to ask, because I can't see it.)

**Comment by AdamTragedy** [comment]
Yeah, spigot made a ton of changes lately which is causing a lot of plugins to freak out. And yes, permissionsEX is listed on there, and I copied in the specific timings for pex as well. 

Spigot has been notified by numerous devs due to this craziness. 

Adam Wolf

**Comment by Stormbow** [comment]
Sounds like it's entirely on Spigot's end then, if it's affecting so many plugins.

Thanks for the head's up.

----

@zml2008 can close this ticket if he's done with it.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
