### ISSUE TITLE
[SQL][PEX 1.23.4][PaperSpigot 1.8.8] Crash when trying to delete group

### ISSUE THREAD

**Issue by Fleodas** [PEXPlugins/PermissionsEx#2893]
When I use this command: /pex group moderateur+ delete the server crashes in a few seconds with this error: https://hastebin.com/jeqawavamu.md

I'm using Spigot 1.8.8 and Pex v1.23.4.

**Comment by Stormbow** [comment]
Since you're using SQL, you'll need @zml2008 to reply to this ticket.  Sorry.  (He has much more experience with SQL than I have.)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
