### ISSUE TITLE
Pex and GriefPrevention

### ISSUE THREAD

**Issue by Jav0330** [PEXPlugins/PermissionsEx#2894]
1st off, I looked to use the forum button on the bukkit page and it does not appear to work.. So I am asking here.

I am looking to execute a console command when ranking a player up on the default ladder. Specifically adding claim blocks for a user with GriefPrevention. The console command is "acb playername 500".. Which sets players bonus claim blocks to 500.  _(Although in plugins  I believe its "acb %player% 500".)_

Next level up the rank ladder would probably be "acb playername 1000".

I am wondering how one would go about setting that up. I have looked through the wiki's and such and find myself coming up empty.

Any guidance anyone could provide, would be GREATLY appreciated. (I really need to automate this in some way.)

Thanks in advance for all your time and attention..

-J

**Comment by Stormbow** [comment]
Unfortunately, PEX itself doesn't have any sort of automated features that would accomplish what you're looking for (or that could automate anything, really).

I believe [this thread](https://bukkit.org/threads/griefprevention-help.292310/) from the GriefPrevention plugin forum is what you're asking about, but I'll warn you in advance that it's not going to be good news.  The official GriefPrevention page had [this](https://www.spigotmc.org/threads/griefprevention.35615/page-195#post-2453378) to say on the same subject, and while the page for the plugin that _could_ do what you're asking doesn't load, the GriefPrevention author may be aware of another to handle the task.  (I found both of these links in less than 1 minute, total, because my Google-Fu is hella strong. ![Wink](https://vgy.me/d9BFPU.gif)

So, it looks like _you_ will need to find a plugin that listens for players to rank up, and then runs the command to adjust their claimblocks.  Sorry.
