### ISSUE TITLE
Color of Person's NameTag is not Changing

### ISSUE THREAD

**Issue by Techno3600** [PEXPlugins/PermissionsEx#2897]
Hello,

The problem I am having is I changed my NameTag coloring from Gold to Yellow, but it does not seem to actually change on the server.

EssentialsX Config: https://pastebin.com/wmRwtuDC
PEX Config: https://pastebin.com/k4XwGyEc

Here is the picture of what I see
http://imgur.com/a/ehpV1
I would like it to be like
http://imgur.com/ge2lyaz

Thanks
Techno3600

**Comment by Stormbow** [comment]
I gotta start off by saying that was one of the best, most informative tickets I've seen lately.  I don't have to ask for any extra information right away.  Awesome!

The solution to this problem is to change 1 line in your permissions.yml file:
```
      prefix: '&4&lOWNER&R&6 '
```

The `&6` at the end of that line is what colors your username gold.  To make your username yellow, you'll want to change that to `&e`.

Once you make that change, save the file, and type `pex reload` into the console or type `/pex reload` in-game.  When you talk after that, your username should be yellow.

Let me know if it worked out for you.

**Comment by Techno3600** [comment]
LOL, I changed everything but that. I can't believe that I did that.
Thanks, it is working now!

**Comment by Stormbow** [comment]
No problem.  :)

You're welcome!  Have fun!

**Comment by Stormbow** [comment]
(You wouldn't believe how often I rack my brain for hours trying to solve a problem, I go ask for help, and almost immediately figure out the answer myself before anyone replies to the help request.  LOL)
