### ISSUE TITLE
Pex Issue Default Group not being given to new Players [1.23.4]

### ISSUE THREAD

**Issue by rnateh** [PEXPlugins/PermissionsEx#2898]
Version 1.23.4
Minecraft: 1.2

Here is the permissions.yml
https://pastebin.com/wQ0xy1A4

Description: When a new player joins they aren't added to the default group. Instead they arent added to any group and get a default prefix
I am here as an intermediate for a friend that has no knowledge in this kind of stuff, so I'd thought I'd go ahead and ask for him.

**Comment by Stormbow** [comment]
Have them use [this example](https://pastebin.com/8ZSHxauG) as the template for their file.  Most of their stuff in your link is out of order, formatted incorrectly, and that's why it's not workin' for him.

Once you use the above example for your file, and have it customized more for your friend's server, let me know if you need additional help.  :-)

**Comment by rnateh** [comment]
So just out of curiosity, if I remove all the stuff under options besides default, prefix, and suffix, the file will still work? (up until inheritance I mean ~ I wouldnt remove that but stuff like weight etc.)

**Comment by Stormbow** [comment]
Yep, you can remove as much as you want.  Most of those are for fine-tuning stuff.

**Comment by Stormbow** [comment]
And, of course, the permission nodes are all fake, and my user info at the bottom won't actually do anything if I joined the server.  It's just for example purposes.

**Comment by rnateh** [comment]
Yeah I gotcha. I'm going to put it together and if its alright I'll send the finished product just to make sure I didn't mess something up if thats alright? Thanks again for all the support by the way!

**Comment by Stormbow** [comment]
You can also delete the white/blank spaces before the `#` hashtags, the hashtag itself, and the words after the `#` hashtags on each line; those are "comments" and PEX won't see them, but you may want to make the file look cleaner by removing them.

**Comment by Stormbow** [comment]
Sure thing.  I'll be here when ya finish up.  :-)

**Comment by rnateh** [comment]
https://pastebin.com/ca3eynBW I believe I converted correctly.

**Comment by Stormbow** [comment]
That looks pretty good.

The only part that may be a problem is the `users:` list.  Some of the users don't have a UUID next to their information.  That typically happens when a server is running in offline mode, for players using hacked/illegal copies of Minecraft, but can happen in other situations.

If the server is running in offline mode as part of a Bungeecord server system, everything would be fine.

If the server is running in offline mode for people stealing Minecraft...PEX wouldn't work correctly, no matter what you and I did with the PEX permissions.yml file.

Test the server, see how things work, and let me know if you need additional help. :-)

**Comment by rnateh** [comment]
It is an online server actually. It never convered those usernames I guess? Should I manually convert them before I try out the file?

**Comment by Stormbow** [comment]
If they're players that are currently playing on the server, PEX will update their info the next time they log in, so you can just ignore them for now.

The "online" and "offline" mode I was referring to is located inside the server.properties file for the server.  If `online-mode=` in there is set to true or false, you'll get the previously mentioned results.

**Comment by rnateh** [comment]
Yeah, I gotcha. I was letting you know that is set to true. Going to test it out now and let you know if it works. Thanks for all of the help!

**Comment by Stormbow** [comment]
Ok, cool.  You're welcome. :-)  Let me know how the test goes, if you don't mind.

**Comment by rnateh** [comment]
Seems to have worked. If we run into any issues we will let you know. Thank you again for taking the time for this!

**Comment by Stormbow** [comment]
Excellent!  :-)  You're welcome and have fun!
