### ISSUE TITLE
Issue when Building PEX 2.0 SNAPSHOT - CMD Screencap

### ISSUE THREAD

**Issue by CDAGaming** [PEXPlugins/PermissionsEx#2900]
![2017-07-30](https://user-images.githubusercontent.com/16328918/28759154-769be272-754e-11e7-8225-bc50054854d0.png)
Latest Maven and JDK are being used, with appropriate build command. Thanks in advance for assisting.

PS The reason im not using jenkins is that there is a pr with a fix to another issue i had when using the official jar.

**Comment by Stormbow** [comment]
Since PEX 2 hasn't been officially released yet, I don't have any experience with it and you'll have to wait for @zml2008 (the PEX programmer) to reply to this ticket.  Sorry!

**Comment by CDAGaming** [comment]
Ok, will do. I'll also revive the guy's PR that fixed the other issue as mentioned earlier as he took it down the day he posted it for unknown reasons.

**Comment by CDAGaming** [comment]
Actually @Stormbow Are you able to just merge the fix, i can link the pr that was previously submitted to you

**Comment by Stormbow** [comment]
Unfortunately, I don't handle any of the programming end.  Sorry.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
