### ISSUE TITLE
Pex groups not inheriting their parent's per world permissions

### ISSUE THREAD

**Issue by Firestar311** [PEXPlugins/PermissionsEx#2905]
I am an admin/developer on a server and we have a per world setup for permissions In the config, the Member rank has the permissions for a plot world called plots but the ranks up the inheritance ladder are not receiving those permissions. What can I do to solve this issue? 
permissions.yml

Example, the Member rank has the permission plots.claim in world "plots", however, the Admin rank doesn't receive the permission. However, when added directly to the Admin rank, it works fine (Per world setting as well)

permissions.yml file if needed
https://pastebin.com/G69mLSxf

**Comment by Stormbow** [comment]
If you have access to the server console, you may see that there's actually an error in the permissions.yml file.  The "HBT" group has a line which reads `rank: '7'` and it's not under an `options;` section.  As far as I'm aware, that would invalidate the file, even though the file parses cleanly when it's run through any YAML checker, so the server console should note that error.  At the very least, anything above that (ranks 7 though 1) wouldn't work fully/correctly, and it's more likely nothing would work correctly for any group while that error existed.

Another potential cause of things not working correctly would only matter if the server is running Minecraft 1.9 or higher.  If that's true, _every_ group on the server needs an `inheritance:` section, even if they're not inheriting from another group.  You can take a look at line 19 of [this example](https://pastebin.com/8ZSHxauG) to see how your "default" group should be given an inheritance.

Once those 2 issues are addressed, test the server again to see if the inheritance issue you encountered has been corrected.  Let me know if you need additional help.

----

On an unrelated note, you may want to consider removing all the duplicate "global" permissions from your groups.  For example, "SrAdmin" inherits from "Admin", so "SrAdmin" doesn't need `essentials.fly` listed in its own `permissions:` section.  If we wanted to give it to "SrAdmin" on only on one world, we'd list it under that world and negate it in the `permissions:` section, since it's inherited from "Admin" as a "global" (all worlds) permission.

----

**Comment by Stormbow** [comment]
Problem solved?

**Comment by Stormbow** [comment]
No reply from @Firestar311 in more than 7 days.  I guess this issue is resolved.
