### ISSUE TITLE
Cant Drop/Get Blocks?

### ISSUE THREAD

**Issue by TexorYT** [PEXPlugins/PermissionsEx#2910]
1. i think this is a node.
2. Idk Why, But When I Go Into /gmc, i Cant Take a block from inventory and into my hotbar.
i cant drop them either.

**Comment by TexorYT** [comment]
ok.
perm>>https://pastebin.com/EA7Ua7t4
server.prop>>https://pastebin.com/RYdrtnuN
this is happening to everyone.
group name?
everything

**Comment by Stormbow** [comment]
In the server.properties file, `spawn-protection=16` means that from the 1 block that everyone spawns on, outward in every direction for 16 blocks, no one can break any blocks, use doors, switches, or anything else.  Since most servers user WorldGuard to protect their spawn region, this should be `spawn-protection=0`.

Next up, since you're using Essentials, you may have also unknowingly included the EssentialsAntiBuild.jar file in your server's plugins folder.  If you're not using Essentials AntiBuild as the protection plugin for your server, delete that file from the plugins folder and everyone will be able to build everywhere.  If you want to keep EssentialsAntiBuild as your protection plugin, you will need to add 1 setting to every groups' `options:` section, and that 1 setting is:
```
  build: 'true'
```

If you still can't build or do anything else, you'll need to use [PEX's Debug Mode](https://pastebin.com/093Ep4VX) to find out why no one can do anything.

**Comment by TexorYT** [comment]
We can build. We just can’t get anything from the creative inventory.
We have to /give ourself it

**Comment by Stormbow** [comment]
What did Debug Mode tell you was going on?

**Comment by Stormbow** [comment]
Did you have EssentialsAntiBuild.jar on the server?

**Comment by TexorYT** [comment]
1. i couldnt tell too much crap:
https://pastebin.com/wbhidwqs
i have essentialsx so yea prob

**Comment by Stormbow** [comment]
SuperVanish is causing the errors you posted in [https://pastebin.com/wbhidwqs](https://pastebin.com/wbhidwqs).  That's not a PermissionsEx error.

Look inside your plugins folder.  Do you see EssentialsAntiBuild there?

**Comment by TexorYT** [comment]
So do I get rid of sv?
No I don’t have eantibuild

**Comment by Stormbow** [comment]
> So do I get rid of sv?

Unless you can stop the error, yes.

> No I don’t have eantibuild

Show me your full server log.  Something else you're not telling me about is stopping everyone from doing stuff.

**Comment by TexorYT** [comment]
1. how to i fix the error?
2. https://jpst.it/12HUH
3. can u just join my server? i can fully "show you the problem"

**Comment by Stormbow** [comment]
Did you intentionally pick the worst possible paste website to show me the log?  I think you did because you've seen dozens and dozens of pastes from me on [Pastebin](http://pastebin.com) by now, after all the tickets you've been sending in.

As I said in another ticket, I sincerely think you're just trolling.  You're not learning anything I've been teaching you.  You're not making corrections that I tell you about.  You're questioning almost every thing I tell you needs to be done to fix the dozens and dozens of problems that you have with running a server.

I don't get paid anything to help people with PermissionsEx, and I don't have time for one person who seems to be intentionally not trying to resolve their problems.  Is it an age thing?  Is it a language barrier thing?  I don't know.  All I know is that you seem to not really want to learn about how to run a server, and don't want to learn how to set one up.

So please stop wasting my time.  Go to Google.  Search for your problems there.  Read _a lot_.  Watch _a lot_ of videos about how to run a Minecraft server.  You can't have someone do everything for you for free.

**Comment by Stormbow** [comment]
You don't even reply to your tickets in a timely manner, which means every time you have a problem, it takes days and days to get it fixed.

**Comment by TexorYT** [comment]
Ok I’m sorry but I have a busy schedule. I can’t usr pastebin because oh the size limit. IM TRYING TO LEARN AND IM DOING ALL THE STUFF YOU TELL ME TOO. SO WHAT YOU DONT GET PAID? I DONT EITHER. SO IF YOU WANT, COME ON NY SERVER AND LISTEN. TO. ME. THEN YOU CAN HELP ME.
