### ISSUE TITLE
How do i use PEX with EssentialsX

### ISSUE THREAD

**Issue by DropSuit** [PEXPlugins/PermissionsEx#2913]
I recently switched from Essentials To EssentialsX, when i had Essentials i could use PEX just fine now that i have EssentialsX i can't use it when ever i make a prefix it doesn't apply to my name please help.

**Comment by Stormbow** [comment]
Essentials and EssentialsX use virtually the same exact config.yml file.  (As far as I'm aware, there is no difference at all.)

If you had prefixes programmed correctly in Essentials, that same config.yml file would work for EssentialsX.  (They both also use "Essentials" as the name of the plugin folder.)

And since you claim to have had prefixes programmed correctly in Essentials, you already know how to program prefixes correctly for EssentialsX.

[Short Guide to Prefixes in Essentials/EssentialsX](https://pastebin.com/eHCCcNuY).

**Comment by Stormbow** [comment]
You're welcome.
