### ISSUE TITLE
Error SQL

### ISSUE THREAD

**Issue by rodnicho** [PEXPlugins/PermissionsEx#2915]
Hello, I have a problem with the configuration of permissionsEX when I configure it in sql mode.

Server version & Bungee: 1.10.2
SQL Version: 5.6.17 (the bdd is managed by WAMPSERVER)

Config: https://hastebin.com/jawecejobi.sql
Error: https://hastebin.com/ecibehaguc.sql

**Comment by Stormbow** [comment]
Make sure there are no errors at all in your permissions.yml file before migrating to SQL.  It looks like something is wrong with the "utilisateur" group.

**Comment by rodnicho** [comment]
look: https://image.prntscr.com/image/0Bo1lN8vSU2e2oUNx-6OcA.png

**Comment by Stormbow** [comment]
Unfortunately, I don't know what I'm looking at there because I haven't used SQL in more than 4 years now.

You'll need to wait for @zml2008 to reply here.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
