### ISSUE TITLE
Error using MySQL

### ISSUE THREAD

**Issue by Loonyy** [PEXPlugins/PermissionsEx#2924]
https://pastebin.com/f129kUQP

**Comment by Stormbow** [comment]
Check your database for duplicate lines of `schema-version: 1`.

Delete one of them.

If that doesn't solve the problem, you'll need @zml2008 to reply to this ticket since he knows more about SQL than I do.

**Comment by Loonyy** [comment]
I'm not too clued up with SQL myself; I checked for `schema-version: 1` and couldn't find any traces of it in the PEX DB.

**Comment by Loonyy** [comment]
I have an issue with using SQL with this plugin too, it's not updating ranks correctly. 

If I set myself in a group on server 1, I'll have it on server 2. However, if I set myself in a group on server 2, I won't have it on server 1.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
