### ISSUE TITLE
Confliction with Spartan anti-cheat.

### ISSUE THREAD

**Issue by Velencious** [PEXPlugins/PermissionsEx#2928]
PEX seems to have a confliction with a popular anti-cheat. Is there any information on this or any branches which support a fix for this?

I know this isn't particularly your problem, however, I would appreciate any help at all. If the issue is not known is there anything I can do to provide information to help fix the problem. I believe the issue is when Spartan anti-cheat does a call to check for the correct permissions of users. I believe PEX has an issue where it bottlenecks on a high amount of file openings to check the user's permissions?

Again any help would be appreciated.

Thanks

**Comment by zml2008** [comment]
"a high amount of file openings to check the user's permissions" can confirm this is not the cause. If you'd like this issue fixed, find a real dev and get them to talk to the dev of Spartan.

**Comment by Velencious** [comment]
Thanks for your response.

If you could leave this thread open while I get a comment from the developer of the anti-cheat who is assuring me this is an issue with PEX. I'm just looking for a possible fix or the cause of the problem so I can get someone to fix it.

I'm not a developer so I may not have been clear.

**Comment by Vagdedes** [comment]
I never got aware of what was really causing the issue. However, I changed my permission system and I now cache each permission when requested and I only remove them from the memory when the player leaves or the plugin's configuration is reloaded. Since then, I haven't got any lag reports regarding this problem so I think we will be just fine.

~Spartan AntiCheat's Developer

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
