### ISSUE TITLE
SQL not updating

### ISSUE THREAD

**Issue by Loonyy** [PEXPlugins/PermissionsEx#2929]
As the title says, SQL isn't updating without me running /pex reload.

If I add myself into a group on one server and then go to another, I won't be in the group until I run /pex reload. Can this be fixed?..

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
