### ISSUE TITLE
/pex user <username> group set <groupname> does not work.

### ISSUE THREAD

**Issue by kyoukotsai** [PEXPlugins/PermissionsEx#2938]
I have done everything correct. I created the group using `/pex group <name> create` , then added permissions using `/pex group <name> add <permission>`, then I added a prefix to the group using `/pex group <name> prefix <prefix>`. Then the problem comes here, when I go to add someone to the group. I use the command `/pex user <username> group set <groupname>` and it says "User groups set!" but then when I type in chat there is no prefix and nothing shows up next to my name. I will also attach a screenshot of my PermissionsEx config and permissions YML files. Please let me know what is going on. I have ChatManager and MassiveCore installed. Do I need to configure something in ChatManager? 
![image](https://user-images.githubusercontent.com/31199862/29504713-b45bb1f6-860f-11e7-8440-93a22843efc5.png)

![image](https://user-images.githubusercontent.com/31199862/29504761-087297c8-8610-11e7-9568-0e33eaafa01c.png)

![image](https://user-images.githubusercontent.com/31199862/29504765-14a3ea88-8610-11e7-9b69-6db16480134a.png)

**Comment by Bomblerm** [comment]
Please dont use ChatManager - try ChatEx

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
