### ISSUE TITLE
How do i get perms

### ISSUE THREAD

**Issue by colman123** [PEXPlugins/PermissionsEx#2939]
everytime i do pex [name] add [permission it doesnt work

**Comment by david-bla** [comment]
### Hi unknown @colman123,
what a great example, posts like yours makes developers feel angry and let them quickly lose interest on answering issues.
but anyway, achieve these goals before you post ;)
_( / for ingame command, default permitted for OPs )_
* [ ] read https://github.com/PEXPlugins/PermissionsEx/wiki/Troubleshooting-and-FAQ#pex-help
* [ ] pex listed by /pl?
* [ ] does /pex work?
* [ ] version of pex and bukkit / spigot ?
* [ ] what other plugins are running?
* [ ] make sure to set proper filerights. _(to execute .jar file)_

If you still want to raise an issue, have the courtesy and write at least a few sentences.
Describe your environment, post the command you are entering and how do you.
Is there any output?
Try restart server, enter command and post log (http://pastebin.com/).

Thank you and do well!

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
