### ISSUE TITLE
Problem with timed permissions

### ISSUE THREAD

**Issue by BolsaFamiliaBR** [PEXPlugins/PermissionsEx#2940]
I'm trying to add timed permissions to a player with:

/pex user (user) timed add essentials.fly 100

But it's not working, when i put in console, it says:

`23.08 20:13:09 [Server] INFO Timed permission "essentials.fly" added!
23.08 20:13:09 [Server] INFO User "559b824e-edc3-3c29-a21f-257e11905dfa" get timed permission "essentials.fly" for 100 seconds from CONSOLE`

But the player still can't using /fly, what i'm doing wrong?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
