### ISSUE TITLE
Pex Groups Assignment

### ISSUE THREAD

**Issue by ItsSh4dow** [PEXPlugins/PermissionsEx#2941]
Hello! I have many groups in PermissionsEx. When I set a player's group with /pex user PLAYER group set GROUP, everything is good. But sometimes something strange happens, and the player gets two ranks (the one that I have and the default), as you can see here:

group:
- YT
worlds:
@World:
group:
- default

When this happens the player can only use default permissions

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
