### ISSUE TITLE
New players can't use kit

### ISSUE THREAD

**Issue by Memethanol** [PEXPlugins/PermissionsEx#2942]
I have an issue on a server that uses PermissionsEx and Essentials. Players that join the server for the first time can't use the starter kit and the Stone kit (Stone is the default rank). They can only use /kit after they've relogged. How can I fix this?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
