### ISSUE TITLE
 Hello, i have problem with PermisionEX

### ISSUE THREAD

**Issue by Juzio1357** [PEXPlugins/PermissionsEx#2944]
Hello, when the server is firing, PermisionsEx is working, but when the server is started it pops up such an error: [11:52:17 ERROR]: [PermissionsEx] Error occurred with PermissionsEx! Please post it to https://github.com/PEXPlugins/PermissionsEx/issues/new?title=&body=%23%23%23+Description+%23%23%23%0A%0A%5BInsert+description+of+issue+here%5D%0A%23%23%23+Detailed+Information+%23%23%23%0A%0A%5BIs+available+here%5D%28https%3A%2F%2Fgist.github.com%2Fcdb5c4dd8f99f56821e889d308428ba4%29%0A. Full error:
Please help

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
