### ISSUE TITLE
Removing user from group doesn't work.

### ISSUE THREAD

**Issue by MithrandirCraft** [PEXPlugins/PermissionsEx#2950]
https://hastebin.com/okakasoyir.md

As you can see, I removed the username jose66 from the group vip+.
On later inspection, he's still there.

**Edit:** I discovered it only happens with certain groups. I've noticed with my 2 vip groups up to now.
**Edit2:** Further info: Those two groups only accept UUID's as arguments. If you set a UUID instead of a name, it works (You can remove the user).

PEX: 1.23.4 (On mySQL)
Spigot: mc 1.12.2

**Comment by SimonOrJ** [comment]
The plugin in my server also doesn't remove a user from a specific group.  When I remove it, it says user removed successfully.  However, in my case, it doesn't remove the user by using UUID.

Pex 1.23.4 using YAML on Spigot 1.12.1.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
