### ISSUE TITLE
group prefix error

### ISSUE THREAD

**Issue by MCplayer11** [PEXPlugins/PermissionsEx#2951]
I recently found out about permissionsEX and loved what I saw but for some reason, it's not working. I've been trying to get it to work for about 2 weeks 

So just to summarize whats happening when I do /pl its green

When I type it says in green [guest] <"name">: and in gray "your test"

I am currently running 2 plugins one being PEX and the other ChatManager_Reloaded I removed about 25 others because I thought it may be causing the problem

My PEX permissions/config file:
https://pastebin.com/hraephjM

Hope we can find out the problem soon

**Comment by MCplayer11** [comment]
Okay, it's working now I just have one problem the ' are showing in the prefix.

**Comment by HappyMiel** [comment]
How did you make it work again?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
