### ISSUE TITLE
New to bungeecord. After setup, prefixes no longer appear.

### ISSUE THREAD

**Issue by gh422321** [PEXPlugins/PermissionsEx#2953]
Well, I just made my first bungee server. I'm not sure why, but for some reason my prefixes won't show even though they are set. Ideas?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
