### ISSUE TITLE
After my PEX auto-updates, it doesn't work anymore!

### ISSUE THREAD

**Issue by OldBo5** [PEXPlugins/PermissionsEx#2962]
Hello, When my PEX auto updates it breaks. I am running 1.8 and when it updates from Pex 1.23.3 to 1.23.4, it stops working. HELP!

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
