### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by DropSuit** [PEXPlugins/PermissionsEx#2963]
how do i remove the slashes from my prefix's when ever i do it in the permissions file, the plugin fails 

here is my permissions.yml file: 
https://pastebin.com/hCUP2L1E

**Comment by SrLeojaco** [comment]
Try to add your prefix between ' '

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
