### ISSUE TITLE
Crash while executing /pex promote s

### ISSUE THREAD

**Issue by mineyannik** [PEXPlugins/PermissionsEx#2964]
The server crashes while executing "/pex promote s"

config: https://pastebin.com/eqg0QHBm

The server log does not contain any information

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
