### ISSUE TITLE
PEX Prefix doesnt work

### ISSUE THREAD

**Issue by HappyMiel** [PEXPlugins/PermissionsEx#2965]
Pex prefix isnt working. Im now currently on a minecraft spigot 1.12.1 server with only permissionsex as plugin on the server. i created a group called admin, and wanted to give it a prefix but it doesnt appear.
Commands used:
/pex group admin create
/pex group admin prefix AdminD
/pex group admin user add Miel123
Its still not displaying i know its a 1.11 plugin but it appears green when i do /pl so i should work then right?

**Comment by angrynerd** [comment]
This feature of pex will not work without vault or a similer supourted plugin

**Comment by calebj320** [comment]
This same problem is happening to me, I do /pex user CalebTheExpert prefix (My Prefix). But, I have the Plugin Vault also installed? Is the a Config I need to edit? I am so confused..

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
