### ISSUE TITLE
Spigot

### ISSUE THREAD

**Issue by ScuroK** [PEXPlugins/PermissionsEx#2967]
First of all THANK you for this awesome resource! im using it for years <3

I wanted to ask you if you could post it on spigot aswell because bukkitdev is fked up and so broken.
It even downloads me weird files if i open a project page. xD

i think its good to put it on spigot so new people will still use it and find it.

**Comment by LickTheCheese** [comment]
i think that is a good idea too :3 

> 123456789098765432

**Comment by ScuroK** [comment]
yeah right? i think many of the good old devs didnt realize that bukkitdev is not the place to go anymore xD and bukkitdev is so buggy. it even downloads me some swf files when i go to a project page..

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
