### ISSUE TITLE
https://deckswap.com/s/oYln

### ISSUE THREAD

**Issue by mt5888** [PEXPlugins/PermissionsEx#2968]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/a156d5ced853bffe9144)

**Comment by LickTheCheese** [comment]
what is your problem? the detailed info just said your plugins & stuff, so i dont know what you need help with.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
