### ISSUE TITLE
The Give-All-Permissions (*) node isn't working in 1.12!!!

### ISSUE THREAD

**Issue by NinjaCat1226** [PEXPlugins/PermissionsEx#2969]
For some reason, the give all permissions node isnt working even though it says that pex supports it. Seems to add it fine but when I deop myself and try to use commands, it says access denied! Will show up in permissions with a \ before it.

**Comment by LickTheCheese** [comment]
dont you need to do `'*'` not `*` ? i heard somewhere that you need to do that (but im not shure)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
