### ISSUE TITLE
Not an issue, BUT

### ISSUE THREAD

**Issue by Fyrlex** [PEXPlugins/PermissionsEx#2970]
And i also dont know where the ideas part is.
But my idea is, well, can you make it so each permission is alphabetized, caps dont matter it will go a-z organized. im suggesting this because i am very bad at organizing and i have way too many permissions to do this. Please take my advice and do this.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
