### ISSUE TITLE
Weird Command Bug

### ISSUE THREAD

**Issue by LickTheCheese** [PEXPlugins/PermissionsEx#2971]
whenever i use a permissions file that has the same permission nodes multiple times in one group, the all PEX commands stop working. if doing this is a syntax error, it _should_ say "syntax error in permissions file", disable the plugin, or something like that, not make it not respond to commands.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
