### ISSUE TITLE
Stupid tag "[O] user The Best" above my head. Please help!!!!

### ISSUE THREAD

**Issue by sagenthings** [PEXPlugins/PermissionsEx#2972]
I have set groups and prefixes, i also have another plugin for the tab list. I am the owner and can't for the life of me get rid of that stupid tag above my head. Does anyone know anything about this?

**Comment by SrLeojaco** [comment]
Set weight to your ranks. Probably you're getting the perm refer to the [O] prefix.

In case you're using NTE, you should set the jerarquical order by setting the highest rank fist in the list (owner, admin, mod ...)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
