### ISSUE TITLE
PermissionsEX - Setting Prefixes and Suffixes

### ISSUE THREAD

**Issue by xDrag** [PEXPlugins/PermissionsEx#2974]
I am trying to create a group permission that allows any member of that group to edit a player's prefix and or suffix. The issue that I am having is, I am using the permission node permissions.manage.users.prefix.<user> but cannot figure out what to put under <user> that allows a player to edit any player prefix or suffix. Hopefully you guys can help me out with this, this is a permissions I really want my staff members to have.

**Comment by SrLeojaco** [comment]
/pex user  [user] prefix "[prefix w/color codes ]"

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
