### ISSUE TITLE
You are not permitted to interact with grass

### ISSUE THREAD

**Issue by Shiftkeyplayz** [PEXPlugins/PermissionsEx#2975]
Pex doesn't work on my server. You are not permitted to interact with anything. My code knowledge is limited but I used YAML phraser and still players can't interact or use anything.
The default doesn't work ->
groups:
  default:
    options:
      default: true
    permissions:
    -  modifyworld.*
schema-version: 1

**Comment by Yeeeeeeeeeeeee** [comment]
If you have Essentials Installed go to config, EssentialsAntiBuild and set "build" and "use" to "false".

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
