### ISSUE TITLE
ModifyWorld

### ISSUE THREAD

**Issue by alexdell2** [PEXPlugins/PermissionsEx#2976]
Is it working in the 1.12.2 update? Because It ain't for me...

**Comment by MinerRicher** [comment]
For me aswell

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
