### ISSUE TITLE
Crash Server

### ISSUE THREAD

**Issue by FrukTik** [PEXPlugins/PermissionsEx#2977]
Hello!
Is it possible to fix it?
https://pastebin.com/Deb2nbur
In one hour there were 2 server crashes With this error.

https://github.com/ChestShop-authors/ChestShop-3/issues/78
https://github.com/ProtocolSupport/ProtocolSupport/issues/728

**Comment by SrLeojaco** [comment]
Try updating chestshop to a developer build (despite it can be dangerous, they have fixed some bugs that the latest stable buildd has)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
