### ISSUE TITLE
Group timed add

### ISSUE THREAD

**Issue by SrLeojaco** [PEXPlugins/PermissionsEx#2980]
https://github.com/PEXPlugins/PermissionsEx/blob/STABLE-1.23.4/src/main/java/ru/tehkode/permissions/PermissionUser.java

When adding a user to a group for a certain time, it only adds time to current time, it doesn't take in account if the user has previous time.

Example:

29-10-17 00.00: pex user x group add y * 68400 <-- (1 day)
29-10-17 12.00: pex user x group add y * 68400 <-- (1 day)
30-10-17 12:00: The user x will be removed from group y

I added (in total) 2 days for the user, so his rank would end the 31-10-17, but due to current system, his rank will end 12hours before (because pex doesn't sum new group time to (if) previous group time).

**Comment by SrLeojaco** [comment]
up

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
