### ISSUE TITLE
Everyone still has all permissions on my server!

### ISSUE THREAD

**Issue by SweggyDucks** [PEXPlugins/PermissionsEx#2981]
I tried what was asked of me but everyone still has permissions to everything on my server, here is the current permissions config file: https://pastebin.com/zEzt2Ky0

**Comment by dogeGAMR** [comment]
you need to run /deop @s[name=!yourminceaftusername] (replace yourminecraftusername with your IGN)
make sure you do it in game so it works

**Comment by SweggyDucks** [comment]
Oh, thank you for the reply. I figured this out awhile ago though xD

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
