### ISSUE TITLE
"Permissions manager is not accessable. Is PermissionsEx enabled?"

### ISSUE THREAD

**Issue by Edgentex** [PEXPlugins/PermissionsEx#2982]
i have a server that has permissions Ex and it worked the other day and now it don't and idk why can some 1 plx help and it does it as soon as the server starts i have stopped it and started it but it wont work.i have deleted and re added the plugin and the plugin folder and paste the groups back in but it didn't work

**Comment by spooner01** [comment]
I had this issue too while setting up. I had some formatting issues (spaces where they shouldn't be) that a dev was able to find and fix. Double check your formatting in the config and permissions yml files

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
