### ISSUE TITLE
It dosen't work...

### ISSUE THREAD

**Issue by Tofy64** [PEXPlugins/PermissionsEx#2983]
It dose absoloutly nothing... the file is empty ._. im so confused help.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
