### ISSUE TITLE
Permissions in PEX don't work.

### ISSUE THREAD

**Issue by Yeeeeeeeeeeeee** [PEXPlugins/PermissionsEx#2985]
Hello, prefixes on my server work, but permissions do not.
Here is my permissions file: https://pastebin.com/TgiF99fS

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
