### ISSUE TITLE
PEX for Forge available - 1.12.2 Releases?

### ISSUE THREAD

**Issue by smmmadden** [PEXPlugins/PermissionsEx#2986]
Looking for a PEX Mod for Forge Servers.  The current plugin doesn't get picked up by forge so there are some differences to prevent it from working. Anyone know where I can get one that works for 1.12.2 releases?

Thanks,
Steve

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
