### ISSUE TITLE
Command to select all users?

### ISSUE THREAD

**Issue by GR1MSOULTAKER** [PEXPlugins/PermissionsEx#2989]
Wanted to know if there was a command that allowed me to select all users (dont wanna do it via default group)

Looking for a way to have the permission from all users removed and is then awarded to some other user,
then removed from all users and then to a new player and so on

 For ex - essentials has /eco give ** 1000 that selects all users

Thanks

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
