### ISSUE TITLE
Pex disables it self every time I restart the server

### ISSUE THREAD

**Issue by AsusMinecraft** [PEXPlugins/PermissionsEx#2991]
So, Im developing my server but pex disables it self each time I restart the server. I have pex 1.23.4 installed. 
the server is running 1.8. If you want all of the plugins then I will give you all of the plugins but please help

**Comment by AsusMinecraft** [comment]
Its okay im fixing it and almost done with it.

**Comment by spooner01** [comment]
What was the issue? I am having a similar problem at random (or seemingly at random)

**Comment by AsusMinecraft** [comment]
Okay so the line of code in pex is not done right so im not sure if i can post websites on here soo...

**Comment by MTS2313** [comment]
cara eu pex tambem nao ta funcionando eu configurei ele mais sempre que eu inicio o servidor ele nao aparece na lista e nem mesmo bloqueia os players de quebrar os blocos

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
