### ISSUE TITLE
Prefix doesn't work

### ISSUE THREAD

**Issue by viktortim** [PEXPlugins/PermissionsEx#2992]
Just watch this video.
https://youtu.be/Ql230AsNzFQ

**Comment by GoNotCougsWA** [comment]
You need a chat plugin that supports Pex

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
