### ISSUE TITLE
Prefix does not work

### ISSUE THREAD

**Issue by ChampionArts** [PEXPlugins/PermissionsEx#2993]
Hello, I aam currently runnning a 1.7.10 Paper spigot server, and my Prefix is not working :/. I set the prefix to '&f(&4&lOwner&f)&0:&f ' and it just show's it as this 
![image](https://user-images.githubusercontent.com/32317279/32985696-e0517ef0-cc85-11e7-99dc-977f320cc46c.png). Thanks for your time!

**Comment by GoNotCougsWA** [comment]
I don't think this supports paper spigot.

**Comment by GoNotCougsWA** [comment]
It might be your chat plugin.

**Comment by maarcuss** [comment]
If you have essentials/essentialsx you need to download essentials chat/essentialsx chat

**Comment by GoNotCougsWA** [comment]
That doesn't make any sense. If he/she has a chat plugin that fine.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
