### ISSUE TITLE
Weird Issue With Groups

### ISSUE THREAD

**Issue by GTApsycho** [PEXPlugins/PermissionsEx#2994]
I am running a Spigot server version 1.12.2. Pex works fine until I put my old custom ranks and permissions in to the permissions file. When I do that, pex stops working completely

**Comment by GoNotCougsWA** [comment]
I recommend copy the old custom ranks file called it "permission Copy" and then delete the "Permissions.yml"
then create a rank again with permissions.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
