### ISSUE TITLE
Prefix Not working 1.8.8

### ISSUE THREAD

**Issue by mhaas11** [PEXPlugins/PermissionsEx#2997]
Prefixes do not show up I have a lot of players on the server and this problem must be solved immediately
Spigot 1.8.8

I have PermissionsEx-1.23.4
I have EssentialsX 1.8
I have Essentials chat 2x
I have Essentials spawn 2x

**Comment by GoNotCougsWA** [comment]
We need more info. Like is there a errors? What command are you using?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
