### ISSUE TITLE
Pex group has a problem help please

### ISSUE THREAD

**Issue by Nicoli24** [PEXPlugins/PermissionsEx#2998]
watch the video and see the problem if u can help me please comment kthx https://youtu.be/wUsto37_fR0

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
