### ISSUE TITLE
22

### ISSUE THREAD

**Issue by sanko2017** [PEXPlugins/PermissionsEx#2999]
### Description ###

[Insert description of issue here]
### Detailed Information ###

[Is available here](https://gist.github.com/604687d76ae2d5b4ac0c)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
