### ISSUE TITLE
Modifyworld.* doesn't seem to work

### ISSUE THREAD

**Issue by KyattPL** [PEXPlugins/PermissionsEx#3000]
Here's my permissions file:
https://pastebin.com/uur5m8tb

Basics permissions work fine but - -modifyworld.* doesn't work. Default users still can destroy/place blocks etc.

**Comment by wherkamp** [comment]
I am pretty sure that was disabled in a previous version.
Anyway You might be able to find a plugin that does what you want for your? 
If you can't it wont be too hard to make. Contact me I will make it for your for free.

**Comment by GoNotCougsWA** [comment]
@Wherkamp please stop.

Anyway you need a plugin called ModifyWorld. It was in pex but was removed into there own plugin.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
