### ISSUE TITLE
Fault on init with spongeforge 1.12.2

### ISSUE THREAD

**Issue by colinrgodsey** [PEXPlugins/PermissionsEx#3002]
Pex never comes up fully on spongeforce 1.12.2, fails with an AbstractMethodError. I'm sure it's something to do with the sponge beta. This eventually leads to other depending plugins crashing, and eventually the server failing to start.

https://gist.github.com/colinrgodsey/ce01303cdfb05954743b557b7408333d

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
