### ISSUE TITLE
Permissions don’t work

### ISSUE THREAD

**Issue by maarcuss** [PEXPlugins/PermissionsEx#3003]
Hi i have PEX installad on my server and im using it with EssentialsX. I have created goups and added peole there. But when they try to do a command i gave them they can’t do it, there prefixes/suffixes work but not the permissions. Can someone help me? (As an example i gave mods essentials.fly.use and default essentials.back.use)

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
