### ISSUE TITLE
I can't add a permission from the console.

### ISSUE THREAD

**Issue by chorman0773** [PEXPlugins/PermissionsEx#3005]
On my server, I am locked out of the plugin (I don't have access to the actual files, because the host is bad but doesn't cost anything). I seemingly am unable to set my permissions from the console. I also can't do anything period from the console. 
I have tried adding a base permission, as well as a specific permission, but it all fails; as commands that are suposed to be dependant on those permissions fail with "Sorry, you don't have enough permissions". I have tried to enable all permissions for ops with /pex config permissions.enableOps true, followed by /pex reload, and also setting the permission with /pex user InfernoDeityInf add permissions. 
(InfernoDeityInf is my username)
The attempts provided no feedback of any kind, and had no effect that was apparent.

**Comment by chorman0773** [comment]
NVM about not having access to the files, but I think that the console should do something, or at least provide some feedback.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
