### ISSUE TITLE
Group name not appearing in-game

### ISSUE THREAD

**Issue by liammengler** [PEXPlugins/PermissionsEx#3007]
Everything seems to work fine except the name of the group (in my case: Founder) is not appearing. If someone could help, that would be great... Thanks
-LM

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
