### ISSUE TITLE
Per World Help

### ISSUE THREAD

**Issue by ArhamR** [PEXPlugins/PermissionsEx#3008]
Hi, i am a Dev/Co-Owner on a server and i am setting up per world perms so i read the base and i got that but i have a question as i have 2 worlds 1 being a factions and the other being a survival world but there are a few other wolrds i which i dont want ppl to be able to do the factions command so i was wondering if i can a group for 2 worlds but then make one of them apply to the others?

**Comment by ArhamR** [comment]
i tried doing this but nothing workd players are still allowed to do commands in survival that they should only be able to do in the factions world

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
