### ISSUE TITLE
Import Permissions File Does Not Import Prefix

### ISSUE THREAD

**Issue by Elxafil** [PEXPlugins/PermissionsEx#3009]
So it seems on file backend PermissionsEx works completely fine but when you import a backend file into a database and then try to load PermissionsEx and it tries to load the permissions just recently uploaded it returns a MySQL error saying that the option "prefix" is not found.

Correct me if I'm wrong but either the "prefix" option for ranks is not being added in proper through the `pex import file` command or the prefix option is stored somewhere else in MySQL?

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all issues are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
