### ISSUE TITLE
Support for MongoDB

### ISSUE THREAD

**Issue by jessestricker** [PEXPlugins/PermissionsEx#902]
I'm not sure if ya have heard of [MongoDB](http://mongodb.org) before, it's way faster than SQL and it would be cool if you would like to see this implemented.

I could do the work, do a PR and you will be fine.

Just tell me.

**Comment by zml2008** [comment]
Unfortunately PermissionsEx is currently unmaintained and no further updates are planned. Because of this, all pull requests are being closed. If you are looking for an actively maintained permissions plugin, take a look at [LuckPerms](https://github.com/lucko/LuckPerms/wiki). It is compatible with major server platforms and can import data from PEX.
